### ISSUE TITLE
Queensland Wildnet

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#10]
Access the Wildnet API to establish regular loads

**Comment by brynk** [comment]
questions via miles to wildnet:
surveys:

    do the survey.features.id values remain constant, or can they change between api accesses? (ie. are they safe to use as an identifier?)
    are there any absence surveys within wildnet? (if yes, how is this communicated?) or are they all presence only surveys?
    with regard to 'survey.features.properties.SiteID' and 'survey.features.properties.SiteCode' - are these values assigned by the wildnet system, or by the collecting institution itself?
    with regard to 'profile.Species.SupersededBy.TaxonID' - when a taxon supersedes another, does the newer 'taxon id' record include the surveys performed under the older 'taxon id'? (ie, the combination of two taxa, newer & older, would result in multiple copies of the one survey)
    eg: http://environment.ehp.qld.gov.au/species/?op=getsurveysbyspecies&species=assa+darlingtoni

projects:

    with regard to 'survey.features.properties.ProjectID' - is this value assigned by the wildnet system? what are the rules for grouping surveys 'under this banner' ? can one survey belong to multiple projects?
    could other surveys within the project be considered related some how? are there any other data representing this relationship?
    eg: (above 'a. darlingtoni' surveys list for a good example, 250-odd surveys, ~20 projects)

general:

    is there a way to determine when a particular record last changed? or must we cross-check previous values at the time of extract? (thereby deducing that the record changed some time since the last load)

**Comment by brynk** [comment]
wildnet completeness model:
(https://docs.google.com/spreadsheet/ccc?key=0AiNWJFdh4pHZdGlHSk5fTmFxbTZyc1lZWFhvTEhKeVE#gid=0)

sandbox sample, latest:
(http://sandbox.ala.org.au/ala-hub/occurrences/search?q=data_resource_uid:drt2698#tab_mapView)
(http://spatial.ala.org.au/?q=data_resource_uid:drt2698&dynamic=true&ws=http://sandbox.ala.org.au/ala-hub&bs=http://sandbox.ala.org.au/biocache-service)

sandbox sample, earlier:
(http://sandbox.ala.org.au/ala-hub/occurrences/search?q=data_resource_uid:drt2697#tab_mapView)
(http://spatial.ala.org.au/?q=data_resource_uid:drt2697&dynamic=true&ws=http://sandbox.ala.org.au/ala-hub&bs=http://sandbox.ala.org.au/biocache-service)

**Comment by M-Nicholls** [comment]
Bryn requested an export of wildnet  (the identifiers in the webservice aren't stable), They have been in touch to complete the process to produce an export for us.

**Comment by M-Nicholls** [comment]
followed up

**Comment by M-Nicholls** [comment]
running against the API
