### ISSUE TITLE
2023-2024 Mobilisation - RGBV NHV-AVH(Mel): dr376

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#1000]
Digitisation of  5000 unique algae specimens.

**Comment by rosemaryjoconnor** [comment]
19/12/2023
- [x] No contact or updates to date
- [ ] Follow up with JS

**Comment by rosemaryjoconnor** [comment]
**08/01/2024**
- [x]  03/01/2024 AV emailed re progress
- [x]  Project is progressing well, on track to exceed the target of 5,000 specimen records by about 20%.
- [x] Follow up with PN re identifying records in AVH (Mel) dataset - dr376

**Comment by nielsklazenga** [comment]
Just to tag on, 5,737 records are tagged in our database as having been databased as part of the Kraft Algae Project. The project ends on the 26<sup>th</sup>, so we will probably be overshooting the target plus 20 per cent. The data is already in ALA. We can identify the records as soon as we know which Darwin Core (or other?) term to use.

**Comment by nielsklazenga** [comment]
The best way to do this is through [`dwc:ResourceRelationship`](http://rs.tdwg.org/dwc/terms/ResourceRelationship). Then ALA can just provide IDs (and maybe even web pages) for all projects it funds and data providers can provide the funding source using the [Resource Relationship Extension](https://rs.gbif.org/extension/dwc/resource_relationship_2022-02-02.xml).

Having a field for it might seem easier, but it is actually harder for data providers, as there is nothing in Darwin Core so, if you use an IPT (like we do), you will have to use [`dynamicProperties`](https://dwc.tdwg.org/terms/#dwc:dynamicProperties), which makes it hard on everyone, including ALA. Resource Relationships can just be in a separate CSV file that gets zipped up with the other file(s) into the Darwin Core Archive, which makes it easy for organisations that do not have an advanced Collections Management System yet, as, when the project has finished, they never have to change the CSV file again, so they can just have it sitting there. And the way DwCA extensions work, you can use different CSV files for different projects.

Resource Relationships are the only way this can be done consistently and in a standards compliant way. They are also very useful for a lot of other things, so would be very good for ALA to have anyway.

**Comment by rosemaryjoconnor** [comment]
**07/06/2024**

- Target number of records based on data provided Jan 2024 - 6165 unique records
- Count today, of those 5466 have loaded in Prod

**Comment by rosemaryjoconnor** [comment]
**12/06/2024**

Records in Prod
