### ISSUE TITLE
Data load: City of Gold Coast Koala Sightings update

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#1017]
Ticket: https://support.ehelp.edu.au/a/tickets/192972

DR: https://collections.ala.org.au/dataResource/show/dr16872

**Comment by cha801p** [comment]
**Ticket Update:** January 22, 2023 (9 AM)
**Data Loaded Successfully.**

**Comment by cha801p** [comment]
There was an issue identified with dates by the data provider - Fixed the dates format and reloaded the data. 
This has been communicated with the data provider on **30 Jan 2024 at 2:14 PM**
**Data re-loaded Successfully**
