### ISSUE TITLE
Victorian Myrtle Rust

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#1022]

**Comment by peggynewman** [comment]
This dataset is ready to go to prod: 

https://collections-test.ala.org.au/public/show/dr22360

**Comment by cha801p** [comment]
**Ticket Update:** March 26, 2024 (7 PM)

**Issue:** New data load

**Solution:** Successfully load the new dataset into biocache

**Actions Taken:**
Successfully loaded the data on test and prod

 Data review
 DwcA created locally
 Loaded the data on collectory

**Loaded data for review:**
[Metadata](https://collections.ala.org.au/public/show/dr25806):
[data](https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid:dr25806)

**Logs:**
_INFO  [2024-03-26 07:55:36,338+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics.....
INFO  [2024-03-26 07:55:36,339+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Trying to write pipeline's metadata to a file - /data/pipelines-data/dr25806/1/uuid-metrics.yml
INFO  [2024-03-26 07:55:36,345+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Added pipeline metadata - newUuidsAttempted: 39, 
INFO  [2024-03-26 07:55:36,369+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Metadata was written to a file - /data/pipelines-data/dr25806/1/uuid-metrics.yml
INFO  [2024-03-26 07:55:36,370+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics written._

**Status:
Waiting for indexing**

**Comment by peggynewman** [comment]
Cheers Raj! Legend.
