### ISSUE TITLE
New Data Load : BIS Weeds (https://collections-test.ala.org.au/dataResource/show/dr22362)

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/data-management#1024]
**Ticket Update:** February 2, 2024 (2 PM)

**Issue:** Required to load a new dataset.

**Actions Taken:**
- [x] Ran Duplicate check- 128 Duplicate records deleted
- [x] Checked the date format
- [x] DwCA created locally 
- [x] DwCA verified 

**Status**: Waiting to be loaded on databox

**Comment by cha801p** [comment]
**Ticket Update:** February 8, 2024 (2 PM)

**Issue:** Required to load a new dataset.

**Actions Taken:**
Data loaded on databox

**Loaded data links:**
https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid:dr22362

**Status:** Waiting for data review and approval from Peggy

**Next step:**
Information to gather for meta
- [ ] Metadata
- [ ] License 
- [ ] Description 
- [ ] URL

**Comment by peggynewman** [comment]
Where is this data from? Is there a support ticket?

**Comment by peggynewman** [comment]
Data provider has been emailed

**Comment by peggynewman** [comment]
This is looking good in test. Emailing the data provider to tell them we're all good. They will build an API.

**Comment by peggynewman** [comment]
Data provider emailed back API details. Prepare a fetcher using these.

**Comment by cha801p** [comment]
**Ticket Update:** June 11, 2024 (8 PM)

**Issue:** Prepare fetcher to fetch data from BIS API

**Test Dataset:** [dr22362](https://collections-test.ala.org.au/public/show/dr22362)

**Steps:**
- [x] Sample dataset loaded on the test
- [x] A new feature branch created 
- [x] Fetcher code is ready 

**Issues Encountered:**
_2024-06-11 20:01:17,339 - root - ERROR - Failed to fetch data. Status code: 503_

**Status:**
1. Test the code again tomorrow
2. Write down an email to the data provider

**Comment by cha801p** [comment]
**Ticket Update:** June 12, 2024 (10:30 AM)

**Issue:** Prepare fetcher to fetch data from BIS API

**Test Dataset:** [dr22362](https://collections-test.ala.org.au/public/show/dr22362)

**Status:**
- [x] The above issue has been resolved and the fetcher is working now. 
- [x] The code is ready to be pushed to the databox.

**Comment by cha801p** [comment]
https://github.com/AtlasOfLivingAustralia/preingestion/pull/253

**Comment by cha801p** [comment]
The code has been tested and pushed.
Pull request: https://github.com/AtlasOfLivingAustralia/preingestion/pull/253

**Status: Waiting for the pull request to be approved.**

**Comment by cha801p** [comment]
Data successfully loaded on prod: https://collections.ala.org.au/public/show/dr27665
First loaded on - 19th August 2024
