### ISSUE TITLE
New data load: North East Link Matted Flax-lily translocated plants

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#1029]
https://support.ehelp.edu.au/a/tickets/195464

Occurrence data CSV and metadata DOC available in the first email in the thread.

**Comment by cha801p** [comment]
Databox - https://collections-test.ala.org.au/dataResource/show/dr22428
Prod - https://collections.ala.org.au/dataResource/show/dr25125

**Comment by cha801p** [comment]
Ticket Update: February 27, 2024 (5 PM)

Issue: New dataset to load on prod/databox

Solution: Successfully load the new dataset into biocache and prod

Actions Taken:
- [ ] Successfully loaded the data on the test environment
-  Data review
-  Deleted empty columns
-  Duplicate check ran
-  Date format check
-  DwcA created locally
-  Loaded the data on biocache-test

- [ ] Sent a link to the data provider for review
- [ ] Loaded the data on prod upon review

Logs:
UUID: INFO  [2024-02-27 03:37:28,130+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Checking for backups to prune..../data/pipelines-data/dr25125/1/identifiers
INFO  [2024-02-27 03:37:28,131+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics.....
INFO  [2024-02-27 03:37:28,132+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Trying to write pipeline's metadata to a file - /data/pipelines-data/dr25125/1/uuid-metrics.yml
INFO  [2024-02-27 03:37:28,133+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Added pipeline metadata - newUuidsAttempted: 420, 

Loaded data on prod:
https://collections.ala.org.au/dataResource/show/dr25125


Status: Waiting for the indexing

**Comment by cha801p** [comment]
**Ticket Update:** February 28, 2024 (11:30 AM)
**Status: 

- Data resource successfully loaded onto the prod.
- Links sent to the data provider.**
