### ISSUE TITLE
Lists - Identify duplicate lists

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#1031]
Script required to identify lists that have been duplicated

**Comment by peggynewman** [comment]
Let's discuss this. These are created by users in the spatial portal.

**Comment by TaniaGLaity** [comment]
can we just make them private as per the script to "clean up" lists that Dave ran a while back?

**Comment by rosemaryjoconnor** [comment]
Duplicate issue
Refer to:  https://github.com/AtlasOfLivingAustralia/data-management/issues/1100
