### ISSUE TITLE
dr22431 - Platypus eDNA - Freshdesk 195829

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#1033]
Qld Wildlife Preservation society have provided a small dataset of Platypus eDNA records

**Fresh desk: 195829** - https://support.ehelp.edu.au/a/tickets/195829

**Comment by rosemaryjoconnor** [comment]
- [ ] New DR in test **dr22431** created
- [ ] Testing load in databox
- [ ] Client emailed re metadata

**Comment by rosemaryjoconnor** [comment]
**01/03/2024**

**Databox dr22431 -** https://collections-test.ala.org.au/public/show/dr22431
- [ ] Data successfully in databox. eDNA-specific fields are appearing in Additional Properties.
- [ ] No records are excluded by the filters
- [ ] Client emailed with test link and also re metadata

**Comment by peggynewman** [comment]
License isn't coming through on occurrences, and I'm not sure why
Set content type to environmentalDNA in collectory so that it gets set against the occurrences

**Comment by rosemaryjoconnor** [comment]
**07/03/2024**

- [ ] Prod dr25165
- [ ] Data Load successful
- [ ] Index successful

- **Collectory:**  https://collections.ala.org.au/dataResource/show/dr25165
- **Biocache:** https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr25165
