### ISSUE TITLE
BDBSA data load: 03/2024

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#1034]
https://support.ehelp.edu.au/a/tickets/196312

The SA Department for Environment and Water has created an updated version of the SA Flora (BDBSA) and SA Fauna (BDBSA) records on the ALA FTP site.
Please update the datasets metadata with the month and year of this extraction - 03/2024

**Comment by rosemaryjoconnor** [comment]
**04/03/2024**

- [ ] - [x] 1. Data load complete
- [ ] 2. Index successful
- [ ] 3. Collectory dates updates

**Record counts:**

- dr365-SA Fauna: 
- dr366-SA Flora:
