### ISSUE TITLE
Freshdesk: #195848 BDBSA Fauna data load - extract FrogWatch records

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#1042]
Frogwatch SA - https://collections.ala.org.au/public/showDataResource/dr10043

This dataset will now be delivered via BDBSA.  Next time the SA Flora/Fauna data load happens, in about 3 months, extract the Frogwatch SA data from the Fauna file and load it into its own data resource.

The SA load is in a fetcher I believe.

**Comment by rosemaryjoconnor** [comment]
**27/03/2024**

BDBSA Fetcher currently caters for multiple drs - dr365/dr366. Adding Frogwatch  dr10043 will be easy to do here. 
Need verification as to how to filter Frogwatch records - possibly FAUNACODE? 

**To do:**
- [ ] Verify filter value to use
- [ ] Check existing Frogwatch fetcher for any additional data requirements
- [ ] Add dr10043 extract logic to config and fetcher

**Comment by rosemaryjoconnor** [comment]
**08/04/2024**
Emailed Lilian for information re Frogwatch files/data

**Comment by rosemaryjoconnor** [comment]
Duplicate issue - refer to:  https://github.com/AtlasOfLivingAustralia/data-management/issues/1055
