### ISSUE TITLE
Myrtle Rust - Qld Herbarium

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#1045]
https://collections-test.ala.org.au/public/showDataResource/dr21975

Has a CC-BY 4.0 Int license

Update license and put into prod

**Comment by cha801p** [comment]
**Ticket Update:** March 26, 2024 (5 PM)

**Issue:** New events dataset to load.

**Solution:** Successfully load the new dataset into biocache and events

**Actions Taken:**
- [x] Successfully loaded the data on prod
- [x]  Data review
- [x]  New columns added - basis of record = Human Observation
- [x]  Columns renamed
- [x]  DwcA created locally
- [x]  Loaded the data on biocache and events

**Loaded data for review:**
[Myrtle Rust - Queensland Herbarium](https://collections.ala.org.au/public/show/dr25704):
[biocache](https://biocache.ala.org.au/occurrences/search?fq=dataResourceUid:dr25704)
[events](https://events.ala.org.au/?datasetKey=dr25704&view=DATASETS)

**Logs:**
_INFO  [2024-03-25 03:41:19,876+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Pipeline complete.
INFO  [2024-03-25 03:41:19,876+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Checking for backups to prune..../data/pipelines-data/dr25704/1/identifiers
INFO  [2024-03-25 03:41:19,876+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics.....
INFO  [2024-03-25 03:41:19,877+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Trying to write pipeline's metadata to a file - /data/pipelines-data/dr25704/1/uuid-metrics.yml
INFO  [2024-03-25 03:41:19,878+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Added pipeline metadata - newUuidsAttempted: 15044, 
INFO  [2024-03-25 03:41:19,908+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Metadata was written to a file - /data/pipelines-data/dr25704/1/uuid-metrics.yml
INFO  [2024-03-25 03:41:19,909+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics written._

**Status:
Data loaded on prod**

**Comment by peggynewman** [comment]
Thanks!
