### ISSUE TITLE
New Data Load : Tisiphone abeona (spp: abeona & albifascia) collected specimen occurrence records (2002 & 2022)

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/data-management#1046]
**Ticket Update:** April 4, 2024 (12 PM)

**Issue:** New Data Load (https://collections-test.ala.org.au/public/show/dr22445)

**Solution:** Successfully load the new dataset into biocache/prod

**Actions Taken:**
- [x]  Data review
- [x]  Answered data providers queries regarding images 
- [x]  Waiting for updated CSV

**Ticket:**
https://support.ehelp.edu.au/a/tickets/198597

**Comment by peggynewman** [comment]
I LOVE these tickets and thorough documentation! Thanks!

- [ ] License needs to be added
- [ ] Coordinate precision looks fishy, should be something like: 0.00001 (see Sharing data with the ALA article on location)
- [ ] Occurrence status inferred from individual count flag set ... set occurrenceStatus to Present
- [ ] Collection code/institution codes don't map to a provider map:

_Supplied institution code "MQU, Sydney"
Supplied collection code "MCV"_
(check with @rosemaryjoconnor about provider maps!)
Is MCV an actual collection?

Thanks!

**Comment by cha801p** [comment]
**Ticket Update:** June 18, 2024 (6:30 PM)

**Issue:** Load data on Prod

**Solution:** Successfully ingested the new dataset onto prod

**Actions Taken:**
Successfully loaded the data on prod

 Data reviewed
 Columns deleted - licence
 Empty columns deleted
 DwcA created locally
 Loaded the data on collectory
 Ran preingestion on prod

**Loaded data for review:**
[Metadata](https://collections.ala.org.au/public/show/dr22687):
[data](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr22687)

**Logs:**
INFO  [2024-06-18 06:48:00,056+0000] [main] au.org.ala.pipelines.beam.ALAUUIDMintingPipeline: Writing metrics.....
INFO  [2024-06-18 06:48:00,057+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Trying to write pipeline's metadata to a file - /data/pipelines-data/dr22687/1/uuid-metrics.yml
INFO  [2024-06-18 06:48:00,058+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Added pipeline metadata - newUuidsAttempted: 184, 
INFO  [2024-06-18 06:48:00,078+0000] [main] org.gbif.pipelines.common.beam.metrics.MetricsHandler: Metadata was written to a file - /data/pipelines-data/dr22687/1/uuid-metrics.yml

**Status:
Waiting for indexing**

**Comment by cha801p** [comment]
**Data loaded on prod and email sent to the data provider.** 
https://support.ehelp.edu.au/a/tickets/198597
