### ISSUE TITLE
Data load: AD, AVH delivery v1.14 (May)

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#1053]
From https://support.ehelp.edu.au/a/tickets/201823:

Hi, I’ve uploaded an AVH delivery for AD (State Herbarium of South Australia):

dwca-adherb-v1.14

This is the first of monthly deliveries to be handled by a job scheduler on the 20th of each month.

After consultation with Niels, I have changed all id and occurrenceID triplets and homogenised collectionCode to resolve long-standing misinterpretations for these values. catalogNumber remains unchanged until the errant spaces can be dealt with in the future.

**Comment by peggynewman** [comment]
Now a scheduled job
