### ISSUE TITLE
Freshdesk: 195848 - Frogwatch via BDBSA

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#1055]
**Freshdesk:**  https://support.ehelp.edu.au/a/tickets/195848

BDBSA to have FrogWatch SA - https://collections.ala.org.au/public/show/dr10043 incorporated in their data feed. This data needs to be extracted and from the dataset and loaded to **dr10043** as part of the regular BDBSA update process.

Next extract containing FrogWatch data will be for load: **September 2024**

**Comment by rosemaryjoconnor** [comment]
- [ ] Review identification of FrogWatch data from BDBSA fauna dataset
- [ ] Update BDBSA fetcher to extract FrogWatch and load to dr10043
- [ ] Test - databox
- [ ] Pull request
- [ ] Production release

**Comment by rosemaryjoconnor** [comment]
**07/06/2024**

 **Code changes**

- [ ] Collectory dr10043
- Connection parameters 
  - **Protocol:** Custom Web Service 
  - **URL:**  s3://ala-uploads-source-data-production/uploads-server-sync/dewnr-sa/upload/dewnr-sa/
- [ ] baseConfig.py:
- Add dr10043 to dr_specific - 'dr10043': 'BDBSAFetcher'
- Add dr10043 to prefix in BDBSAService class:  - 'dr10043': 'safauna_all_'

- [ ] BDBSAFetcher.py:
- Add function extractFrogwatch
- Ensure all checks for dr365 - SA Fauna have dr10043 added also:     if self.uid == 'dr365' or self.uid == 'dr10043':

**Comment by peggynewman** [comment]
BDBSA went in for June but Frogwatch will be included next round

**Comment by rosemaryjoconnor** [comment]
**02/09/2024**

- [ ] New BDBSA dataset has arrived. 
- [ ] Create new develop branch for preingest - github

**Comment by rosemaryjoconnor** [comment]
**06/09/2024**

-[ ]  tested in databox successful
-[ ] LM notified to check the data

**Note:** all catalogNumbers for Frogwatch have changed so will have to update UUID avros in Production so there is no impact on GBIF

**Comment by rosemaryjoconnor** [comment]
**13/09/2024**

- [x] Update BDBSA fetcher to extract FrogWatch and load to dr10043
- [x] Test - databox
- [x] Pull request

Closing this issue - refer to issue:  https://github.com/AtlasOfLivingAustralia/data-management/issues/1103

**Comment by rosemaryjoconnor** [comment]
**16/09/2024**

**Databox**

- Successfully updated UUID avros
- Successfully re-ingested Frogwatch via BDBSA fetcher

**Production**

**To Do after pregingestion release:**

- [ ] Create new UUID avro file for Production
- [ ] Upload new avro to S3
- [ ] Re-ingest Frogwatch via BDBSA fetcher

**Comment by rosemaryjoconnor** [comment]
**27/09/2024**

**Production**

- [x] Create new UUID avro file for Production
- [x] Upload new avro to S3
- [x] Re-ingest Frogwatch via BDBSA fetcher
- [ ] Check records after SOLR Index on Monday night
