### ISSUE TITLE
dr15860 - CANB: AVH - Bulk Collections Images

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#1057]
Imaging the 35,000 bulk orchid card collection for existing occurrence records in **CANB: AVH - dr15860**

**Comment by rosemaryjoconnor** [comment]
Images are for existing occurrence records in CANB: AVH: **dr15860** 

Initially this will be a one-off upload to image service with an updated of the current CANB AVH DWCA.
We will then provide the multimedia.csv and meta.xml files that need to be added to the CANB AVH regular data feed.

**Process**
- [ ]  Download images from:  \nexus.csiro.au\csiro\NRCA\Australian National Herbarium\Digitisation\2024-Orchid-card-images\
- [ ] Manual upload of subset of images to images-test
- [ ] Update current DWCA, adding relevant multimedia files
- [ ] Test databox

**Comment by rosemaryjoconnor** [comment]
**31/05/2024**
Email received indicating images may be managed on their end. Our work to go on hold until notified.

**Comment by rosemaryjoconnor** [comment]
**02/07/2024**
Email sent to check on progresss

**Comment by nielsklazenga** [comment]
Database has moved from ANBG to NRCA, and to a different system, so the entire data delivery needs to be updated.
