### ISSUE TITLE
WELT data issues

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/data-management#1072]
The following issues were raised by the data provider: https://support.ehelp.edu.au/a/tickets/203321

**Comment by cha801p** [comment]
Issue forwarded to systems.

**Comment by adam-collins** [comment]
These are fixed in the pipelines version currently in the test environment. I think you can find existing github issues for both in biocache-service and/or biocache-hubs.

**Comment by cha801p** [comment]
**Ticket Update:** July 5, 2024 (12:30 PM)

**Issue:** WELT data issues

**Testing:**
_**Missing Collector Names: - FIXED**_
The recent data was reingested on Databox to test the missing collector names, which appear to be fixed on Databox.
https://biocache-test.ala.org.au/occurrences/2e0998f2-9d0c-4ffa-9c7d-7a9eae5e84db
Above is the same record mentioned in the issue (on Databox) which now has collector names separated by pipe ( | )

**_RecordedByID Field Issue:_**
The issue persists for _RecordedByID filed for the same record.

**Comment by peggynewman** [comment]
recordedByID seems to be behaving for these records: https://biocache-test.ala.org.au/occurrences/search?q=qid:1720147336737 (search: `catalogue_number:"SP119852"`)
Related issue : https://github.com/AtlasOfLivingAustralia/biocache-service/issues/848

**Comment by adam-collins** [comment]
the URL with pipe split failure is further documented here https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/602

**Comment by peggynewman** [comment]
Will the pipe split problem be able to be resolved with this pipelines release @adam-collins ?

**Comment by peggynewman** [comment]
Sorry Systems, didn't realised this was on your board.

**Comment by peggynewman** [comment]
... but looks fixed. closing again.
