### ISSUE TITLE
Ingest eBird

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#1075]

**Comment by peggynewman** [comment]
A couple of notes about this:
- Doug's code to create an event dataset is in databox
- Dave built the last ebird DwCA
- we had some issues with identifiers - you may have to manipulate them to make sure they match what's in our data
- we've had a request for better location precision - can you check the API for whether we can access this?

**Comment by cha801p** [comment]
**Solution:** Successfully load the dataset on biocache and events.ala

**Actions Taken:**
Environment set-up is done 
Sample data is downloaded from - https://ebird.org/data/download (This data is for the US)
Request sent to eBird for Data Access - **waiting for approval**

**Links:**
[Metadata](https://collections.ala.org.au/public/show/dr2009):
[data](https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid:dr2009)
[events](https://events.test.ala.org.au/?datasetKey=dr2009&view=DATASETS)

**Initial inconsistencies with the structure of the event:**
Restructure with eventType is required as it has an eventType 'Find'

**Status:**
Waiting for the request to be approved

**Comment by cha801p** [comment]
**Solution:** Successfully load the dataset on biocache and events.ala

**Actions Taken:**
Data received from eBird 
Setting up directories
Running the code locally 

**Links:**
[Metadata](https://collections.ala.org.au/public/show/dr2009):
[data](https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid:dr2009)
[events](https://events.test.ala.org.au/?datasetKey=dr2009&view=DATASETS)

**Status:
Reviewing the event's structure**

**Comment by cha801p** [comment]
**Ticket Update: July 23, 2024 (6:30 PM)**

**Issue:** New Dataset to be loaded on prod and events

**Solution:** Successfully load and test dataset on prod and events

**Actions Taken:**
- [x] Successfully loaded the data on prod and events 
- [x] Events structure reviewed - Looks alright 
- [x] Ran code locally
- [x] DwcA created locally
- [x] Loaded the data on s3 bucked (DwCA-imports)
- [x] Ran load_large_dataset on prod

**Loaded data for review:**
[Metadata](https://collections.ala.org.au/public/show/dr2009):
[data](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr2009)
[Events](https://events.test.ala.org.au/?datasetKey=dr2009)

**UUID Logs:**
24/07/19 08:12:54 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
24/07/19 08:12:54 INFO SparkContext: Successfully stopped SparkContext
24/07/19 08:12:54 INFO ALAUUIDMintingPipeline: Checking the percentage change in new UUIDs:
24/07/19 08:12:54 INFO ALAUUIDMintingPipeline: newUuids: 9906807.0, preservedUuids: 4.0594093E7, orphanedUniqueKeys: 348742.0
24/07/19 08:12:54 INFO ALAUUIDMintingPipeline: Percentage UUID change: 19, allowed percentage: 50, override percentage check: false
24/07/19 08:12:54 INFO ALAUUIDMintingPipeline: Backing up existing UUIDs to hdfs:///pipelines-data/dr2009/1/identifiers/ala_uuid_backup_1721376774667
24/07/19 08:12:54 INFO ALAUUIDMintingPipeline: Pipeline complete.

**Status:**
**Waiting for data indexing (index failed on Monday)**

**Comment by cha801p** [comment]
Data was ingested successfully!
