### ISSUE TITLE
Sharkbase

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#108]
You have probably all heard about the new shark citizen project called 'SharkBase' developed by Dr Ryan Kempster of UWA and Support Our Sharks.

He has now made available this link where you can, at any time, download data from the database: http://www.supportoursharks.com/SharkBase/Download/

The data is freely available to anyone that wants it, so please forward around your networks.

**Comment by sadeghim** [comment]
Loaded and waiting for the client's feedback:

http://collections.ala.org.au/public/show/dr2383
