### ISSUE TITLE
WA Naturemap updates

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#109]
look like there are lots of new data sets available via naturemap

**Comment by M-Nicholls** [comment]
see list in the naturemap directory on the internal fileshare

**Comment by charvolant** [comment]
Started mapping of Australian River Assessment System

**Comment by charvolant** [comment]
Most surveys also have soil/water sample data attached to the observations, which have rather cryptic names. It would be good to translate these into something that makes sense when read by a normal mortal. At the moment, I'm unable to contact custodians due to a captcha problem with the naturemap website -- will be fixed in a couple of weeks.

Doing the main mappings in the meantime.

**Comment by charvolant** [comment]
Captcha problem still unresolved. Paul is forwarding queries to the data custodians

**Comment by charvolant** [comment]
Captcha problem fixed. Queries sent to data custodians. Most have responded but need time to resolve the various queries.

**Comment by M-Nicholls** [comment]
looks like the data set list has been updated as of 24/11/2015, total available data sets 43

**Comment by charvolant** [comment]
Updating again. Sent initial queries for:

Australian River Assessment System
Avon Baselining - Invertebrates
Avon Baselining - Waterbirds
Banksia Woodlands Restoration Project Survey
Carnarvon Basin (Aquatic Projects) - Invertebrates
Natural Diversity Recovery Catchments - Invertebrates
Pilbara Biological Survey - Diatoms
Pilbara Biological Survey - Invertebrates
Pilbara Biological Survey - Stygofauna
Pilbara Biological Survey - Waterbirds
Pilbara Hyporheic Fauna Survey
South-west Forest Monitoring
State Salinity Strategy Wetland Fauna Monitoring - Invertebrates
State Salinity Strategy Wetland Fauna Monitoring - Waterbirds
Subregional Invertebrate Survey
Wetlands of the Swan Coastal Plain - Waterbirds
Wheatbelt Biological Survey - Invertebrates
Wheatbelt Biological Survey - Waterbirds

**Comment by charvolant** [comment]
Loaded

Berkeley region bats http://collections.ala.org.au/public/show/dr7703
Berkeley region birds http://collections.ala.org.au/public/show/dr7704

**Comment by charvolant** [comment]
Loaded

Banksia Woodlands Restoration Project Survey http://collections.ala.org.au/public/show/dr7729
Australian River Assessment System http://collections.ala.org.au/public/show/dr7732

**Comment by charvolant** [comment]
Loaded

Avon Baselining – Invertebrates  http://collections.ala.org.au/public/show/dr7807
Avon Baselining – Waterbirds  http://collections.ala.org.au/public/show/dr7808
Carnarvon Basin (Aquatic Projects) – Invertebrates http://collections.ala.org.au/public/show/dr7809
Berkeley subregion mammals - http://collections.ala.org.au/public/show/dr7810

**Comment by charvolant** [comment]
Sent initial queries for

Carnarvon Basin Terrestrial Fauna Survey
Carnarvon Basin Wetland Bird Survey
Kimberley Limestone Range Survey
Kimberley Rainforest Survey 1990
Nullarbor Regional Survey
WA Seabird Breeding Islands

**Comment by charvolant** [comment]
Loaded

Carnarvon Basin Wetland Invertebrate Survey http://collections.ala.org.au/public/show/dr7811
Natural Diversity Recovery Catchments – Invertebrates http://collections.ala.org.au/public/show/dr7812

**Comment by charvolant** [comment]
Loaded

Kimberly Islands Bats http://collections.ala.org.au/public/show/dr7813
Kimberly Islands Birds http://collections.ala.org.au/public/show/dr7814
Kimberly Islands Mammals http://collections.ala.org.au/public/show/dr7815

Sent initial query for Kimberly Islands Flora

**Comment by charvolant** [comment]
Sent initial queries for

Cane River Flora Survey
New Island Bay Priority Flora Survey
