### ISSUE TITLE
GBIF data update

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#115]
GBIF data reload : http://collections.ala.org.au/dataResource/show/dr695

**Comment by M-Nicholls** [comment]
refactor data load to use the GBIF API
load should create distinct data resources (with appropriate description and licensing) for the data sets within the  bulk load and load records to each resource

**Comment by charvolant** [comment]
GBIF API http://www.gbif.org/developer/summary

**Comment by charvolant** [comment]
The API can either be used directly, via REST or as a Java API http://gbif.github.io/gbif-api/apidocs/ Version 1 is stable, so changes to the RESTful interface are not expected, so embedding the java library shouldn't cause a great deal of pain. 

Downloads are created offline and then notified via mail. Downloads can be specified in terms of a predicate. As an alternative, it is possible to page through the RESTful interface, but this seems inefficient for anything other than a minor update.

**Comment by M-Nicholls** [comment]
additional process to apply GBIF id's to records in the ALA where a copy is in GBIF

**Comment by charvolant** [comment]
Additional this needs to be available to installers of the ALA, so it needs to be an actual piece of deployable code, rather than a Talend jobbie.

**Comment by charvolant** [comment]
API library uses Java 8

**Comment by charvolant** [comment]
Extend existing GbifService in the collectory to allow review and marking of datasets that should not be updated or already exist.

**Comment by charvolant** [comment]
First commit allows external IDs to be attached to collectory resources.
