### ISSUE TITLE
School of ants - UNE

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#123]
they are preparing their data and will look at adding their zoology museum data as well.

**Comment by M-Nicholls** [comment]
Data is well structured, they're sorting out licensing and will send through the full ants data sets when ready.

They also want to display ALA maps/records on their website

**Comment by ansell** [comment]
This has been added to ALA: http://collections.ala.org.au/public/show/dr4218
