### ISSUE TITLE
Image DwCA checker

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#127]
Pre-check a DwCA with images for suitable structure before feeding it into the gaping maw of the biocache loader. There are three places this could be:

* A stand-alone program (allows a quick check while working on something)
* A web service that takes a archive, checks it and produces a report (can be used outside the ALA, similar to the sandbox)
* An additional command in biocache-store with options for getting the file from a URL or checking a file already supplied to a data resource (easiest to keep in line with the actual loading code)

**Comment by M-Nicholls** [comment]
An option that is usable by others outside of the ALA, like the web service option, would be a good thing.

**Comment by sadeghim** [comment]
Is it something like this web service?
http://tools.gbif.org/dwca-validator/api.do

**Comment by charvolant** [comment]
Similar but specifically targeted to what we expect for an archive with images: the expected extension, a suitable identifier that either maps onto a URL or a file embedded in the archive, expected image metadata fields, sanity checks for titles and licences, etc. Also, I'd like to make it so that people can upload an archive that they've prepared.

**Comment by charvolant** [comment]
Initial version at https://github.com/AtlasOfLivingAustralia/dwc-archive-plugin

**Comment by charvolant** [comment]
Adding the archive transformation code needed by BDRS to make a more general plugin. See https://github.com/AtlasOfLivingAustralia/data-management/issues/45

**Comment by charvolant** [comment]
Committed savable archive transformation. This allows repeated mapping of archives with the term mappings savable in a JSON file. This means that you can automate updates for live datasets.

Currently, this service is only available via web pages. Next step is to allow a decentish web service to allow complete automation.

**Comment by charvolant** [comment]
Available on ala-dury as a service.
