### ISSUE TITLE
MDBA Sustainable Rivers Audit Fish and Macroinvertebrate Survey data Nov 2004 to Jan 2013

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#128]
more records - https://data.gov.au/dataset/sra-fishmacro2004to2013

**Comment by charvolant** [comment]
Contacted custodians, there's been a change of personnel and they're checking to make sure the distribution rules are the same.

**Comment by charvolant** [comment]
Permission received to load version 9

**Comment by charvolant** [comment]
Data mapped and loaded to sandbox for comment

**Comment by charvolant** [comment]
MDBA may wish to split the individual fish into separate occurrence records.

**Comment by charvolant** [comment]
Re-sent query as to how MDBA want to approach fish data

**Comment by charvolant** [comment]
Data loaded and indexed
