### ISSUE TITLE
TERN AEKOS collaborative data sharing

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#13]
collaborative data sharing

**Comment by M-Nicholls** [comment]
data set downloaded from AEKOS/shared and loaded as an example.  Request feedback from AEKOS and parks Aus on process and data display

**Comment by ansell** [comment]
The data resource for AEKOS where the 35,628 records are loaded is https://collections.ala.org.au/public/show/dr7858
