### ISSUE TITLE
AADC data sets

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#138]
New Download	macquarie_penguin_colonies.zip Macquarie Island penguin colonies [Macquarie Island] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=905
New Download	macquarie_seal_colonies.zip Macquarie Island seal colonies [Macquarie Island] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=906

**Comment by M-Nicholls** [comment]
New Download	ASAC_555_2.zip A Survey of the Freshwater Macroinvertebrates in Streams and Lakes of Macquarie Island. This dataset includes corrected site locations. [Science Datasets] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=1459

**Comment by M-Nicholls** [comment]
New Download	ASAC_2208_seabirds.zip Distribution and abundance of seabirds in the Southern Indian Ocean, 1978/1979+ - download of WoV database [Science Datasets]

**Comment by M-Nicholls** [comment]
New Download	HIMI_Demersal_Fish.zip HIMI Demersal Fish Update and Environmental Covariates [Science Datasets] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=4567

**Comment by M-Nicholls** [comment]
New Download	ASAC_2208_seabirds.zip Distribution and abundance of seabirds in the Southern Indian Ocean, 1978/1979+ - download of WoV database [Science Datasets] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=4548

**Comment by ansell** [comment]
Closing this after opening separate issues to track each of the referenced datasets here in their own issues to reduce confusion about which parts have been done.
