### ISSUE TITLE
Remove old BRI records from Biocache (and AVH)

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#149]
The records from the Queensland Herbarium (BRI) are duplicated in AVH. Could the old ones please be removed?

http://biocache.ala.org.au/occurrences/search?q=*:*&fq=data_hub_uid:dh2&fq=-first_loaded_date:[2014-07-31T00:00:00Z%20TO%20*]&fq=institution_code:BRI#tab_mapView

**Comment by M-Nicholls** [comment]
done
