### ISSUE TITLE
Data submission via sandbox

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#151]
https://github.com/AtlasOfLivingAustralia/sandbox/issues/22

**Comment by Tasilee** [comment]
FULLY agree. This is seriously needed if we want to encourage simple data submission. There will need to be a link to enable simple collection metadata to be filled in.

**Comment by Tasilee** [comment]
...and be given a DOI

**Comment by M-Nicholls** [comment]
managed in sandbox repo
