### ISSUE TITLE
Update sensitive species lists

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#155]
updates requested from custodians:

TAS - no changes
ACT - sending a preliminary list

**Comment by M-Nicholls** [comment]
WA - updates done
ACT - new list uploaded, done
SA - no change
VIC - no change

still need - NSW, QLD, NT

**Comment by M-Nicholls** [comment]
category is required in either the data or the list settings (category must have a small c)

**Comment by M-Nicholls** [comment]
QLD update sent - needs to be loaded
ACT species need to be processed

**Comment by sadeghim** [comment]
Processing ACT species is running.

**Comment by sadeghim** [comment]
Finished Processing the records.
