### ISSUE TITLE
EBird engagement

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#16]
The Atlas had a previous agreement with Eremaea to allow regular harvesting of their records, Eremaea has now moved to eBird and we don't have any agreement in place with them.

**Comment by M-Nicholls** [comment]
Requested information on licensing to make the data available via the ALA

can't split out old records (no identifiers), will have to load the new data set and delete the old Eremaea birds

**Comment by M-Nicholls** [comment]
licensing will just involve a link to their terms of use.

**Comment by M-Nicholls** [comment]
approval granted to load the records

**Comment by charvolant** [comment]
Sent sample to Australian manager

**Comment by charvolant** [comment]
Updated processing to strip HTML nasties

**Comment by charvolant** [comment]
Data to be loaded in off-hours

**Comment by charvolant** [comment]
Load failed over weekend. (Sampled and processed, didn't load) Trying again tonight.

**Comment by djtfmartin** [comment]
is this being loaded into prod or somewhere else ?

**Comment by charvolant** [comment]
Production. The didn't load was because the load step had been accidentally fubared. Should have made that clearer in the comment.

**Comment by djtfmartin** [comment]
was it kicked off with Jenkins ?

**Comment by charvolant** [comment]
Yes, the Ad-hoc load. Just a problem getting the command options correct (and the right commands running)

**Comment by charvolant** [comment]
Data loaded. Check after weekend re-index to make sure it appears in the index.

**Comment by charvolant** [comment]
Reindexed. First steps in removing Eremaea data: check to see what terms are present, check to see if there are any annotations, take a backup of all terms including dataset-specific ones if any using the Test State Export job, take a dump of annotations. Redirect to eBird dataset. Sit on things for a bit to see if we can think of a reason not to delete the extra records.

**Comment by charvolant** [comment]
Old Eremaea dataset (dr350) deleted.

Exploring eBird API for incremental uploads.

**Comment by charvolant** [comment]
eBird API at https://confluence.cornell.edu/display/CLOISAPI/eBird+API+1.1

This API only reports the most recent sighting of each species. Which makes it unsuitable for loading full occurrence data. The recommended way for getting complete data is to use the EBD releases.

**Comment by M-Nicholls** [comment]
Update to load

Downloaded new eBird records to dr2009-eBird/ebd_AU_201410_201508_relMay-2015 folder.  Download should only be records from October 2014 to August 2015.

**Comment by M-Nicholls** [comment]
data run through load, sample, process, will be indexed over the weekend.

**Comment by M-Nicholls** [comment]
index successful, reminders in calendar to refresh each quarter
