### ISSUE TITLE
Biocollect data feed

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#167]
Automate data feed from ALA biocollect using web services

**Comment by M-Nicholls** [comment]
Check on the functionality available in GBIF loader

Look at Biocollect web services to provide:
survey as a data resource (license it this level)
project as a data provider
institutions should already exist

when running a load from biocollect:
check institution exists (it should - biocollect can't create projects without a n institution in the collectory)
check if the project exists as a data provider (create if not)
check of the surveys exist as data resources (create if not) and are linked to the data provider and have the correct license

only load surveys with data
only load surveys from projects where data sharing is allowed
only load non-embargoed data

**Comment by sadeghim** [comment]
@pbrenton Could you please verify the loaded records are properly processed. If so, could you please comment and close this issue? 

Assigning the issue to you then you can have it in your list.

**Comment by sadeghim** [comment]
All good.
