### ISSUE TITLE
Empty NE records in AVH

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#169]
When I do a search on all AVH records (http://avh.ala.org.au/occurrences/search?q=*:*#tab_recordsView) I first get a whole bunch of NE records with no data in them. I suspect this has got something to do with the NE images that were uploaded recently (issue #162) and I suspect it is because the catalogue numbers lack a space between the IH acronym and the number, which all AVH records have. Can these records be removed please?

**Comment by sadeghim** [comment]
The empty records are deleted now.
