### ISSUE TITLE
Vic Biodiversity Atlas update

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#172]
exports requested waiting for data to be prepared on the Vic spatial data mart

**Comment by M-Nicholls** [comment]
loaded, sampled and processed, weekend reindex will bring everything up to date.

**Comment by M-Nicholls** [comment]
data loaded - unfortunately all the coordinates are now 0.1 degrees - double check flora 25 file loaded correctly

**Comment by peggynewman** [comment]
Also https://github.com/AtlasOfLivingAustralia/data-management/issues/619
