### ISSUE TITLE
BRI update for AVH

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#177]
new file on the uploads server

new export of the BRI AVH DwC Archive (BRI_20160112.zip).
 
This is a full re-index of the BRI-AVH dataset (~510K records, 60 MB) and should replace any BRI records currently present in AVH.

**Comment by sadeghim** [comment]
Loaded, awaiting indexing.

**Comment by sadeghim** [comment]
New records were indexed now. The whole dr will be re-indexed on the weekend.
