### ISSUE TITLE
Canberra Nature Maps

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#18]
they are setting up a web service to make data available

outline of sensitive data processing provided, recommended they just provide public data initially until we have a species list from the ACT

**Comment by charvolant** [comment]
CNM has chosen the full data provider agreement route.

Sent DPA document for drafting

**Comment by charvolant** [comment]
DPA and risk assessment sent to Katie Riseborough for assessment and have passed assessment.

**Comment by charvolant** [comment]
Created data set at http://collections.ala.org.au/public/showDataResource/dr1947 and uploaded data.
Checking on harvest interval.

**Comment by charvolant** [comment]
Harvest interval should be one week. A scheduled job would be the best option; it's possible to export the Talend job but it needs to be on a machine where running the job will not interfere with other, more important processes. Checking to see what can be used as a data management job runner.

**Comment by charvolant** [comment]
Weekly scheduled job on dury which will kick off an atlas load-sample-process. Indexing happens during the weekly re-index.
