### ISSUE TITLE
update list of download reasons

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#185]
review list of reasons for downloads
consider what happens with old list?

Is there one that someone has prepared earlier?

**Comment by Tasilee** [comment]
Suggested 4/11/2014:

ID, Current term, Suggested term
id: 0,	name: "conservation management/planning",	name: "conservation management/planning",
id: 1,	name: "biosecurity management, planning",	name: "biosecurity management/planning",
id: 2,	name: "environmental impact, site assessment",	name: "environmental assessment",
id: 3,	name: "education",	name: "education",
id: 4,	name: "scientific research",	
id: 5,	name: "collection management",	name: "taxonomy",
id: 6,	name: "other",	name: "other",
id: 7,	name: "ecological research",	name: "ecological research",
id: 8,	name: "systematic research",	name: "citizen science",
id: 9,	name: "other scientific research",	name: "restoration/remediation",
id: 10,	name: "testing",	name: "testing",

**Comment by M-Nicholls** [comment]
testing needs to stay at the bottom of the list - how to insert new reasons without adding them after "testing" ?

**Comment by M-Nicholls** [comment]
change numbering to decimal to allow inserts and keep testing at the end or add display order
add deprecated flag to usage stats view

no change to "collection management"
no change to "other"
no change to "ecological research"

add "citizen science" category
add "restoration/remediation" category
modify label for "systematic research" to "systematic research/taxonomy"

remove/deprecate  "other scientific research"

**Comment by nickdos** [comment]
I've deployed logger with changes to allow ordering of reasons and deprecated values. You can change the ordering via http://logger.ala.org.au/admin/logReasonType (click entry to edit) and you can view the current reasons here: http://logger.ala.org.au/service/logger/reasons. Current order is alphabetical but happy to group like reasons together...

**Comment by Tasilee** [comment]
Looks better!

Lee

Lee Belbin
Blatant Fabrications Pty Ltd
Tasmania

On Thu, May 19, 2016 at 4:13 PM, Nick dos Remedios <notifications@github.com

**Comment by M-Nicholls** [comment]
looks good
