### ISSUE TITLE
Queen Victoria Museum Art Gallery - update

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#19]
Getting updated records from QVMAG

**Comment by sadeghim** [comment]
contacted.

**Comment by m-hope** [comment]
Data has been uploaded... filename is: RecordsForUploadALA.xlsx

**Comment by m-hope** [comment]
Data has been processed and loaded into Sandbox (http://sandbox.ala.org.au/ala-hub/occurrences/search;jsessionid=E88EA91AB90760BBDC3918A0D2B6AE46?q=data_resource_uid:drt3571) for Mark G to check.

**Comment by m-hope** [comment]
Confirmed with Mark that 5 old records will need to be deleted as they are no longer valid (catalogue numbers: QVM:1939:1:0081, QVM:1958:3:0032, QVM:1989:3:0007, QVM:23:21277, QVM:23:21311).  Otherwise data is ready to upload into production.

**Comment by m-hope** [comment]
Additional data was loaded on 30-09-15, but required several attempts to re-index.  New collections were implemented and the QVMAG record counts are now as follows:
-	Invertebrates           41910
-	Birds                             8239
-	Mammals                   5196
-	Herpetology              2405
-	Ichthyology               2246
Total records:                    59996

**Comment by m-hope** [comment]
There is a new update file available on upload for QVMAG to be loaded: ALA_Upload_August2016-4.csv

This update has gone through several iterations of checking so should be pretty close to ready for final upload.

**Comment by sadeghim** [comment]
Done the upload, awaiting the indexing.

**Comment by sadeghim** [comment]
@m-hope Should I remove the old 110 records?
http://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr345&fq=last_load_date%3A%5B*+TO+2016-09-20T00%3A00%3A00Z%5D
