### ISSUE TITLE
School of Ants

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#192]
Data to load on the file store occurrence/School of Ants
Load to sandbox first
License and attribution to be confirmed

New data set
To be linked up to UNE - info in email

**Comment by M-Nicholls** [comment]
if possible would like data loaded prior to a workshop on the 27th of feb

**Comment by ansell** [comment]
I can't seem to open that email from the share drive in Outlook. Can you email me the text?

**Comment by ansell** [comment]
@M-Nicholls @charvolant the UNE School of Ants dataset has been created as a data resource in ALA, but I am not sure how the process functions from this point on. I have uploaded the file attached to it, but I am not sure how it works after that.

http://collections.ala.org.au/public/show/dr4218

If they want to use this on Friday, then I need to know today what steps to take to push it through today/tonight to verify it tomorrow.

**Comment by ansell** [comment]
Done

**Comment by ansell** [comment]
New records with catalog numbers 1607 to 2003 to be uploaded when ala-rufus comes back up.
