### ISSUE TITLE
Delete duplicate AVH records from DNA

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#197]
This is not an error, but a consequence of DNA changing the collection code of its collection in Alice Springs from 'DNA' to 'NT', as we have discussed. A new DNA data was uploaded last week. The following query gives all the records that were last updated before that:

http://avh.ala.org.au/occurrences/search?q=*:*&fq=last_load_date:[*%20TO%202016-02-22T00:00:00Z]&fq=institution_code:DNA

The few records I have eyeballed are all Alice Springs records. Could all those records be deleted please?

**Comment by sadeghim** [comment]
Hi Niels,

You mean all of the records of the above query should be deleted (which is more than 34K)?

**Comment by nielsklazenga** [comment]
Hi Mahmoud,
Yes, the high numbers are explainable. These are records from the Alice Springs herbarium (NT) that were previously provided with the incorrect collectionCode (DNA) and have now been provided with the collectionCode NT. As in AVH we prepend the collectionCode to the catalogNumber, this affects the record identifier, so new records were created in the BioCache. We knew this would happen. This was discussed with Miles sometime last year; it has just taken this long for the new data dump to come through. The entire DNA data set was re-uploaded on February 22 (which is why I put that date in).

I re-uploaded some other data sets last week, so there will be another request for deleting records. This should only involve a small number of records.

**Comment by sadeghim** [comment]
Records are deleted.
