### ISSUE TITLE
Delete discarded AVH records from CANB, CNS and JCT

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#199]
The CANB. CNS and JCT data sets were re-uploaded last week. The records in the result of the following query have been discarded at the provider end, so should be deleted from AVH:

http://avh.ala.org.au/occurrences/search?q=*:*&fq=last_load_date:%5B*%20TO%202016-03-01T00:00:00Z%5D&fq=(institution_code:CANB%20OR%20institution_code:CNS%20OR%20institution_code:JCT)

**Comment by sadeghim** [comment]
Done.
