### ISSUE TITLE
expand spatial intersection fields

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#209]
currently contextual and environmental fields in custom download are the cl.p and el.p fields - expand into separate fields

**Comment by nickdos** [comment]
@M-Nicholls please provide the list of fields to send through.

**Comment by adam-collins** [comment]
The current list of cl and el fields is an intersection of "id" in http://spatial.ala.org.au/ws/fieldsdb and "name" in http://biocache.ala.org.au/ws/index/fields.
