### ISSUE TITLE
ANIC data mobilisation

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/data-management#21]
Look into options for the update of ANIC data into the ALA... Issues to tackle include:
- updating ANIC metadata for data provider, collection and resource pages
- exploring connection to Biolink backend to download data directly from SQL (including getting access)
- developing process to automate upload

Other tasks include:
- assisting ANIC to upload Digivol data (including images)
- provide assistance/advice to reconcile independent databases/spreadsheets into Biolink
- also need to set up extract and upload of data to APPH hub

**Comment by M-Nicholls** [comment]
data has been updated as of April 2019
