### ISSUE TITLE
DwC download issues

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#210]
DwC download headers need to be properly formatted e.g. basis_of_record should be basisOfRecord

there should be up to 142 fields in the full download  - only 49 in sample download e.g. bibliographicCitaion is missing

DwC downlaod shouldn't include QA fields

**Comment by nickdos** [comment]
@M-Nicholls should the "full DwC download" contain all available fields or only all DarwinCore fields?

Not sure where the 142 fields is coming from?

**Comment by nickdos** [comment]
Here are all (196) the fields from http://biocache.ala.org.au/ws/index/fields marked as DwC...
Any below that should NOT be used?
```
acceptedNameUsage
acceptedNameUsageID
classs.p
classs
vernacularName.p
family
family.p
genus
genus.p
higherClassification
infraspecificEpithet
kingdom
kingdom.p
nameAccordingTo
nameAccordingTo.p
nameAccordingToID
namePublishedIn
namePublishedInID
nomenclaturalCode
nomenclaturalCode.p
nomenclaturalStatus
order
order.p
originalNameUsageID
originalNameUsage
parentNameUsage
phylum
phylum.p
taxonRank.p
vernacularName
scientificName
scientificNameAuthorship
scientificNameID
species
species.p
specificEpithet
subgenus
taxonConceptID
taxonID
taxonRank
taxonRemarks
taxonConceptID.p
scientificName.p
taxonomicStatus
verbatimTaxonRank
associatedMedia
associatedReferences
associatedSequences
associatedTaxa
behavior
catalogNumber
recordedBy
recordedBy
recordedBy.p
disposition
establishmentMeans
establishmentMeans.p
individualCount
lifeStage
occurrenceRemarks
occurrenceStatus
occurrenceStatus.p
occurrenceID
otherCatalogNumbers
preparations
sex
recordNumber
reproductiveCondition
recordedBy
associatedOccurrences
associatedOccurrences.p
previousIdentifications
basisOfRecord.p
bibliographicCitation
citation
collectionCode.p
collectionID
collectionCode
dataGeneralizations
dataGeneralizations.p
datasetID
datasetName
dynamicProperties
informationWithheld
informationWithheld.p
institutionCode.p
institutionID
institutionCode
language
modified
modified.p
ownerInstitutionCode
basisOfRecord
basisOfRecord.p
rights
rightsholder
type
continent
coordinatePrecision
coordinatePrecision.p
coordinateUncertaintyInMeters
coordinateUncertaintyInMeters.p
country
country.p
countryCode
county
verbatimDepth.p
verbatimElevation.p
footprintSRS
footprintSpatialFit
footprintWKT
geodeticDatum.p
georeferenceProtocol
georeferenceProtocol.p
georeferenceRemarks
georeferenceSources
georeferenceSources.p
georeferenceVerificationStatus
georeferenceVerificationStatus.p
georeferencedBy
georeferencedBy.p
georeferencedDate
georeferencedDate.p
higherGeography
higherGeographyID
island
islandGroup
decimalLatitude.p
locality.p
locationAccordingTo
locationRemarks
locationId
decimalLongitude.p
maximumDepthInMeters.p
maximumElevationInMeters.p
maximumDepthInMeters
maximumDistanceAboveSurfaceInMeters
maximumElevationInMeters
minimumDepthInMeters.p
minimumElevationInMeters.p
minimumDepthInMeters
minimumDistanceAboveSurfaceInMeters
minimumElevationInMeters
municipality
pointRadiusSpatialFit
geodeticDatum
decimalLatitude
locality
decimalLongitude
stateProvince.p
stateProvince
verbatimCoordinateSystem
verbatimCoordinates
verbatimDepth
verbatimElevation
verbatimLatitude
verbatimLocality
verbatimLongitude
verbatimSRS
waterBody
dateIdentified
identificationID
identificationReferences
identificationReferences.p
identificationRemarks
identificationVerificationStatus
identifiedBy.p
identifiedBy
dateIdentified.p
identificationQualifier
typeStatus
typeStatus.p
day
day.p
endDayOfYear
eventDate
eventRemarks
eventTime
eventID
fieldNotes
fieldNumber
habitat
habitat.p
month
month.p
eventDate.p
samplingEffort
samplingProtocol
samplingProtocol.p
startDayOfYear
verbatimEventDate
year
year.p
measurementType
measurementUnit
measurementValue
```

**Comment by M-Nicholls** [comment]
any fields that are raw values where a processed value is provided should not be included. e.g. samplingProtocol.p should be included but samplingProtocol should not (basically only processed values).  Otherwise it's not a darwin core field set.

this is list by display name:

family_raw
genus_raw
kingdom_raw
nameAccordingTo_raw
nomenclaturalCode_raw
order_raw
phylum_raw
vernacularName_raw
scientificName_raw
specificEpithet_raw
taxonConceptID_raw
taxonRank_raw
recordedBy_raw
recordedBy_raw
establishmentMeans_raw
occurrenceStatus_raw
recordedBy_raw
associatedOccurrences_raw
collectionCode_raw
dataGeneralizations_raw
informationWithheld_raw
institutionCode_raw
dcterms:modified_raw
basisOfRecord_raw
coordinatePrecision_raw
coordinateUncertaintyInMeters_raw
country_raw
georeferenceProtocol_raw
georeferenceSources_raw
georeferenceVerificationStatus_raw
georeferencedBy_raw
georeferencedDate_raw
maximumDepthInMeters_raw
maximumElevationInMeters_raw
minimumDepthInMeters_raw
minimumElevationInMeters_raw
geodeticDatum_raw
decimalLatitude_raw
locality_raw
decimalLongitude_raw
stateProvince_raw
verbatimDepth_raw
verbatimElevation_raw
dateIdentified_raw
identificationReferences_raw
identifiedBy_raw
typeStatus_raw
day_raw
eventDate_raw
habitat_raw
month_raw
samplingProtocol_raw
year_raw
