### ISSUE TITLE
update Reiner richer odonata dr692

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#212]
I have updated my dragonfly sightings to the end of 2015 and they could now be updated at your convenience. It has about 300 new entries.

http://collections.ala.org.au/public/show/dr692

I have attached the data but t can also be retrieved from the link below:
http://photos.rnr.id.au/dragonflies/Reiner%20Richter%20Odonata.zip

**Comment by ansell** [comment]
Data and images were uploaded to Cassandra/etc. and indexing will occur tonight.
