### ISSUE TITLE
Processed IdentificationQualifier

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#217]
Create an IdentificationQualifier.p
• Certain -   (contains any of: certain, confident, confirmed, positive, verified)
• Uncertain - (contains any of: cf., aff., ?, unknown, uncertain, uncertainty, incorrect, possible, probable, sp., sp, Sp., Sp, unnamed, unsure, forsan, near, x, X)
• Not recognised (value provided but it didn't match any checks) 
• Not provided (no value provided)

**Comment by patkyn** [comment]
Added more keywords to Uncertain:
not certain, negative, not sure, not confirm, not confirmed, not correct. 

The rules also applied to additional field: abcdIdentificationQualifier

**Comment by patkyn** [comment]
Added indexing and enable searching for processed identification qualifier.  
Also Certain and Uncertain keywords can now be configured via identificationQualifier.txt.

**Comment by nielsklazenga** [comment]
Most of the terms listed above – certain, uncertain, confident, confirmed, etc. – are not [identification qualifier](http://rs.tdwg.org/dwc/terms/identificationQualifier)s, but indicate identification confidence (or, in the case of 'confirmed', [identificationVerificationStatus](http://rs.tdwg.org/dwc/terms/identificationVerificationStatus). They might sometimes be delivered, but they are not standards (Darwin Core) compliant and should be excluded from processing, or be classified as 'invalid'. Also, the presence of an identification qualifier always indicates uncertainty, so the value of a processed identification qualifier can never be "certain".

I'd suggest not having a processed identification qualifier field at all, but create a new field, has_identification_qualifier, similar to the user_annotations field, which has the value TRUE when an identification qualifier has been delivered and FALSE when not. For most use cases, people will want to exclude records for which has_identification_qualifier is TRUE.

See https://github.com/AtlasOfLivingAustralia/avh-hub/issues/3.
