### ISSUE TITLE
Records having a " (double quote) in their rowKey

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#222]
The records are:
http://biocache.ala.org.au/occurrences/03842386-5aeb-47ce-8728-fb33865bfdfb
http://biocache.ala.org.au/occurrences/1262fb5c-3197-4cbc-b013-02514ae84926
http://biocache.ala.org.au/occurrences/3fe2536d-2985-46db-bd2c-419bb9ba2df1
http://biocache.ala.org.au/occurrences/6c3052cc-feaa-4864-95df-e8bc626fa97f
http://biocache.ala.org.au/occurrences/89c68c24-203b-4fca-a6f4-e1ac0161a304
http://biocache.ala.org.au/occurrences/b2191324-6e78-47be-9907-d340a54b7a0e
http://biocache.ala.org.au/occurrences/da3c7621-0f96-4d70-81e2-15d5c960ddad
http://biocache.ala.org.au/occurrences/dd1d144e-3e24-4f27-9a0d-10324066860b

**Comment by patkyn** [comment]
Reassigning this to @sadeghim after discussion, this could be configuration issue.

**Comment by sadeghim** [comment]
Resolved!
