### ISSUE TITLE
Add recordNumber to duplicate detection

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#228]
include recordNumber (the id given to the record by the collector in the field) to the duplicate detection process

some use of fieldNumber (actually the id for the event given in hte field) for this concept as well so need to check the data

**Comment by sadeghim** [comment]
In addition to that, maybe adding catalog number would be good as well.
Here is an example that I think they are duplicate records while are not detected:
http://biocache.ala.org.au/occurrences/search?q=Z002552

**Comment by temi** [comment]
@adam-collins Can you please check the below mentioned pull request?
https://github.com/AtlasOfLivingAustralia/biocache-store/pull/143
