### ISSUE TITLE
Murray Darling Basin Authority

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#23]
Investigate site http://www.mdba.gov.au for data and information suitable for sharing. e.g. sampling data bases

Contact to investigate collaborative opportunities

**Comment by charvolant** [comment]
Contacted Madeline.

The MDBA has a requirement to publish an environmenal assets and functions database. They're looking at some sort of federated system, possibly tapping into the ALA for some information as well as providing data to the ALA. They're currently collecting ideas for an implementation that is about 2 years away. Madeline met Miles and Dave last year to see how the ALA did it and also attended the ALA conference.

Also, the MDBA has an MS Access database at http://www.mdba.gov.au/kid/kid-view.php?key=1JNfIrnby2D0R0820ygL0hbY4H94nQUir1HLMlobnpY= with ocurrence data. Requested permission to upload into the ALA and a technical contact to help understand the structure and terminology.

Greg Longan and Lex Kogle are responsible for MDBA information sharing. Lex will contact me next week.

**Comment by m-hope** [comment]
As discussed, what MDBA are looking for sounds very similar to what the Dept of Environment is currently using MERIT for... perhaps if you find out more about their requirements it might be an idea to get Peter B to talk to them...

Just a suggestion.

**Comment by charvolant** [comment]
Worth mentioning, at least. I'll find out a bit more next week but they still seem to be in the gathering ideas phase.

**Comment by charvolant** [comment]
Contacted by Greg Long about the database. Dataset is also available at https://data.gov.au/dataset/sra-fishmacro2004to2010 Greg is interested in building an export.

**Comment by charvolant** [comment]
Trial mapping for Fish/Macros. There are two trables tblBio and tblCatch that seem to contain similar information with tblBio containing measurements for a subset of individuals from tblCatch. Clarifying the relationship between the two tables.

Methods may also be manual/machine, depending on method.

**Comment by charvolant** [comment]
Replied to query about species identifiers

**Comment by charvolant** [comment]
Data loaded to http://collections.ala.org.au/public/show/dr2244 institution set up as http://collections.ala.org.au/public/show/in94

**Comment by charvolant** [comment]
Update available. See https://github.com/AtlasOfLivingAustralia/data-management/issues/128
