### ISSUE TITLE
Empty NE records in AVH

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#235]
A new batch of image from NE was uploaded last Friday and again we have a whole bunch of empty records in AVH because incorrect catalogNumbers were used, just like last time (#169). Could these records be deleted and the Darwin Core Archive re-uploaded? I can fix the catalogNumbers in the DwC  Archive on the upload folder if that helps.

**Comment by sadeghim** [comment]
I'll have a look at it.

**Comment by sadeghim** [comment]
Niels, I checked the NE records but couldn't find any suspicious records. Could you please send me sample of problematic records?

**Comment by nielsklazenga** [comment]
Hi Mahmoud,
Thanks for looking into this so quickly.

All catalogue numbers in AVH have a space between the herbarium acronym and the number, so all 2364 records that were uploaded last Friday are wrong.

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=last_load_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]#tab_recordsView

However, only 122 of these where loaded for the first time:

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=first_loaded_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]#tab_recordsView

and only 763 records lack occurrence data:

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=last_load_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]&fq=-collector:[*%20TO%20*]#tab_recordsView

Also, of the few catalogue numbers I tested, I couldn't find the (correct) occurrence record in AVH, so there might be a problem with the NE BioCASe provider, or I might have mucked it up myself.

Let me have a better look at the NE data and get a new data dump from NE and we (weel, you really) can fix up the duplicate and empty records afterwards.

Niels


___________________________________________________________


Niels Klazenga
Programmer Information Technology, Biodiversity Information Officer

Royal Botanic Gardens Victoria
Birdwood Avenue
Melbourne, Victoria 3004
Private Bag 2000
South Yarra, Victoria 3141
Australia
Tel: (03) 9252 2346
Fax: (03) 9252 2444

e-mail: niels.klazenga@rbg.vic.gov.au


>>> Mahmoud <notifications@github.com> 7/07/2016 11:05 AM >>>

Niels, I checked the NE records but couldn't find any suspicious records. Could you please send me sample of problematic records?

**Comment by nielsklazenga** [comment]
Hi Mahmoud,
Just to update, I found 56 records in the AVH cache I have here that are not in ALA. I expect that would have been more before the images were uploaded. So I think that me re-sending the occurrence data will resolve the issue of empty records. I will do that tomorrow, along with the 56 records ALA doesn't have yet.

Am I correct that, when matching records to upload with existing records, spaces in catalogNumbers are ignored?

However, I did find one set of duplicate records that have the same catalogNumber apart from the whitespace. These are:
http://avh.ala.org.au/occurrences/00d18678-e596-45bb-819a-687b1b4c574e
http://avh.ala.org.au/occurrences/65876cdc-44fc-421c-bd84-a39e6a3a3e03

Could you delete the second one, which has neither an image, nor occurrence data?

Niels



___________________________________________________________


Niels Klazenga
Programmer Information Technology, Biodiversity Information Officer

Royal Botanic Gardens Victoria
Birdwood Avenue
Melbourne, Victoria 3004
Private Bag 2000
South Yarra, Victoria 3141
Australia
Tel: (03) 9252 2346
Fax: (03) 9252 2444

e-mail: niels.klazenga@rbg.vic.gov.au


>>> Niels Klazenga 7/07/2016 12:56 PM >>>

Hi Mahmoud,
Thanks for looking into this so quickly.

All catalogue numbers in AVH have a space between the herbarium acronym and the number, so all 2364 records that were uploaded last Friday are wrong.

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=last_load_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]#tab_recordsView

However, only 122 of these where loaded for the first time:

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=first_loaded_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]#tab_recordsView

and only 763 records lack occurrence data:

http://avh.ala.org.au/occurrences/search?taxa=&q=*%3A*&fq=image_url%3A[*+TO+*]&fq=last_load_date%3A[2016-07-01T00%3A00%3A00Z+TO+*]&fq=-collector:[*%20TO%20*]#tab_recordsView

Also, of the few catalogue numbers I tested, I couldn't find the (correct) occurrence record in AVH, so there might be a problem with the NE BioCASe provider, or I might have mucked it up myself.

Let me have a better look at the NE data and get a new data dump from NE and we (weel, you really) can fix up the duplicate and empty records afterwards.

Niels 


___________________________________________________________


Niels Klazenga
Programmer Information Technology, Biodiversity Information Officer

Royal Botanic Gardens Victoria
Birdwood Avenue
Melbourne, Victoria 3004
Private Bag 2000
South Yarra, Victoria 3141
Australia
Tel: (03) 9252 2346
Fax: (03) 9252 2444

e-mail: niels.klazenga@rbg.vic.gov.au


>>> Mahmoud <notifications@github.com> 7/07/2016 11:05 AM >>>

Niels, I checked the NE records but couldn't find any suspicious records. Could you please send me sample of problematic records?

**Comment by sadeghim** [comment]
Hi Niels,

Yes, you are right. For the AVH data, all the spaces from the keys will be striped. That is defined in the configuration of this data resource.

Regarding those duplicate records, the bare record doesn't have right information in the supplied data. If you have a look at the json data coming from biocache-service : http://biocache.ala.org.au/ws/occurrences/65876cdc-44fc-421c-bd84-a39e6a3a3e03 
you'll realise that it does have null string in the rowkey which is completely wrong. I'll delete it then.

**Comment by nielsklazenga** [comment]
Thanks Mahmoud,
I did a search for records with collectionCode=NE, so the records you just picked up were not in my download, which is why I missed them.

Haven't gotten around to send the data for the records that are correct yet.

Niels


___________________________________________________________


Niels Klazenga
Programmer Information Technology, Biodiversity Information Officer

Royal Botanic Gardens Victoria
Birdwood Avenue
Melbourne, Victoria 3004
Private Bag 2000
South Yarra, Victoria 3141
Australia
Tel: (03) 9252 2346
Fax: (03) 9252 2444

e-mail: niels.klazenga@rbg.vic.gov.au


>>> Mahmoud <notifications@github.com> 11/07/2016 3:01 PM >>>

Hi Niels,
Yes, you are right. For the AVH data, all the spaces from the keys will be striped. That is defined in the configuration of this data resource.
Regarding those duplicate records, the bare record doesn't have right information in the supplied data. If you have a look at the json data coming from biocache-service : http://biocache.ala.org.au/ws/occurrences/65876cdc-44fc-421c-bd84-a39e6a3a3e03 
you'll realise that it does have null string in the rowkey which is completely wrong. I'll delete it then.

**Comment by nielsklazenga** [comment]
Hi Mahmoud,
I sent that data yesterday and it is all in there now (except for one record) and the ones I checked all have the image as well. So, if you could delete those 122 records (I think they) that don't have a collection_uid, you can resolve the GitHub issue.

http://avh.ala.org.au/occurrences/search?q=*%3A*&fq=image_url%3A*&qc=data_hub_uid:dh2&fq=-collection_uid%3A*#tab_recordsView

I have checked those records and only two of them (NE 75993 and NE 91019) have duplicates in ALA. That's all I have in the cache and it is all I could get out of the NE BioCASe provider when I tried just then. I will let Jeremy know that he needs to make sure that the specimens are databased before he sends the images.

Niels


___________________________________________________________


Niels Klazenga
Programmer Information Technology, Biodiversity Information Officer

Royal Botanic Gardens Victoria
Birdwood Avenue
Melbourne, Victoria 3004
Private Bag 2000
South Yarra, Victoria 3141
Australia
Tel: (03) 9252 2346
Fax: (03) 9252 2444

e-mail: niels.klazenga@rbg.vic.gov.au


>>> Mahmoud <notifications@github.com> 11/07/2016 3:01 PM >>>

Hi Niels,
Yes, you are right. For the AVH data, all the spaces from the keys will be striped. That is defined in the configuration of this data resource.
Regarding those duplicate records, the bare record doesn't have right information in the supplied data. If you have a look at the json data coming from biocache-service : http://biocache.ala.org.au/ws/occurrences/65876cdc-44fc-421c-bd84-a39e6a3a3e03 
you'll realise that it does have null string in the rowkey which is completely wrong. I'll delete it then.

**Comment by sadeghim** [comment]
Resolved!
