### ISSUE TITLE
QLd Wildnet Data load

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#239]
QLD WildNet web service should be published by the end of September

**Comment by patkyn** [comment]
The dwca from wildnet had encoding of UTF-8 and this had caused an error during ingestion in databox. 
![image](https://user-images.githubusercontent.com/1606595/140236250-8de4243a-7669-4002-9a38-e70365514898.png)


Changed the encoding to ISO-8859-1 and reloaded successfully. 


Wilnet data loaded into databox https://biocache-databox.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1132&qualityProfile=ALA&disableAllQualityFilters=true

However, some records with basis of records 'Occurrence' is appearing as UNKNOWN
https://biocache-databox.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1132&disableAllQualityFilters=true&qualityProfile=ALA&fq=basis_of_record%3A%22UNKNOWN%22

![image](https://user-images.githubusercontent.com/1606595/140236535-89a520b6-fece-4715-a273-fd5f391817d0.png)

**Comment by peggynewman** [comment]
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1132 Data loaded successfully quite a while ago. Closing.
