### ISSUE TITLE
nominate image as representative

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#249]
Admin only button to nominate an image as representative of the species (adds it to the representative image list (ALA preferred images)

**Comment by patkyn** [comment]
Only Role Admin will see the button

**Comment by nickdos** [comment]
Just noticed a feature missing from image view on both BIE and Biocache, that could be added to this task... both need to provide a "next" and "previous" button on popup to allow the user to navigate to other images in the gallery. There is a gallery thumbnail navigation option for this plugin but not sure that is the best solution? See the [`galleryOptions` option](https://github.com/AtlasOfLivingAustralia/images-client-plugin#thumbnails-gallery-component).
