### ISSUE TITLE
Dave Kimble's Rainforest Photo Catalog

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#253]
https://davekimble.net/rainforest/catalog.htm
"Dave Kimble's Rainforest Photo Catalog" is a website of 2,657 photos taken by myself, mostly on "Lot 11", which is 8 acres adjacent to Hull River National Park in the Wet Tropics near Mission Beach.  The photos are intended to assist taxonomical identification, and the plant images' 
file names include Genus.Species.detail.

I would be happy to share this resource with ALA, but I cannot see an effective way of doing it apart from simply linking to my site.

Perhaps you could look at the site and decide on what is most appropriate?

**Comment by sadeghim** [comment]
Data in sandbox, contacted the client for feedback.
