### ISSUE TITLE
Missing records for ACT and conservation_status: endangered

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#254]
John reported this problem, where he has done this search in the past and got over 20 species listed but currently, the same search returns only 3 species:

http://biocache.ala.org.au/occurrences/search?q=*%3A*&lat=-35.278255&lon=149.11214&radius=5.0&fq=state_conservation%3A%22Endangered%22

* Golden Sun Moth	
* Spotted-tailed Quoll	
* Superb Parrot	

old results:

![image](https://cloud.githubusercontent.com/assets/532845/17683111/a2421eaa-6393-11e6-8dd1-e0b32a48b5af.png)

**Comment by charvolant** [comment]
Both http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:4c7edc4a-69df-428b-818d-6d90feebc579 and http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:b945b243-a500-4f66-a75d-fd6b0c077ab7 are listed as endangered in the ACT but don't seem to be in the SDS. Need to find out where the endangered flag is being set.

**Comment by charvolant** [comment]
Adam found it. Need to run

```
biocache update-conservation-data
biocache update-habitat-data
```

after re-matching lists. Looks like there's another re-process + re-index in the works.

**Comment by charvolant** [comment]
Updated. There are about 14 species lists, 10 of which have common names.
