### ISSUE TITLE
need a warning message when a user isn't logged in

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#258]
If a user isn't logged in the downloads just returns an error rather than asking the person to log in:

from the field picker click next when not logged in:

An error has occurred

    Error: unknown

**Comment by adam-collins** [comment]
Added uriFilterPattern for /download,/download/.* to redirect user to login page if not already logged in.

**Comment by M-Nicholls** [comment]
fixed
