### ISSUE TITLE
City of Sydney fauna records

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#259]
data update to load for dr1888

November 2015 _July 2016 file on share drive

**Comment by emilyrose** [comment]
All columns now have dwc headings.
Wasn't able to save it in the folder for some reason:

[Copy of November 2015 _July 2016.xlsx](https://github.com/AtlasOfLivingAustralia/data-management/files/1373725/Copy.of.November.2015._July.2016.xlsx)
