### ISSUE TITLE
Fungimap update

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#26]
in progress

**Comment by charvolant** [comment]
Contacted Sapphire. Interviewing for a new data manager next week.

**Comment by charvolant** [comment]
New data manager starts today.

**Comment by charvolant** [comment]
New data manager has supplied a new dataset with separated substrate and habitat fields. Transformed and loaded to sandbox. There is a query about how to handle living/dead host, which is important.

**Comment by charvolant** [comment]
Contacted Anthony. Expectation is to send a batch of data in about 4-6 weeks.

**Comment by charvolant** [comment]
Sample data received, mapped and loaded to the sandbox. Awaiting full update.

**Comment by charvolant** [comment]
Loaded full update. Images are loaded separately, since they're not connected to an occurrence record with a catalog number of the image name. There are some images missing from the supplied archive; reload once updated.

**Comment by charvolant** [comment]
Images re-mapped to correct file names and reloaded.
The images have source URLs that point to ala-dury. In the future, a permanent home for source images that have been provided via a dump should be found.
