### ISSUE TITLE
load Westmead Medical Mycology Culture Collection data 

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/data-management#265]
need to load the Westmead Medical Mycology Culture Collection database in the ALA... this data is part of the AMRIN hub.   Westmead has a Collection id (CO110) but no data resource id as there is currently no data in the ALA.

The data file and signed data provider agreement can be found here: 

\fsact01-cdc\CSIRO\CES\Share\Themes\Biodiversity\1173-BRABA\Projects\Current\R336601001 _ALA\ALA Data\File Store\Occurrence\Westmead Medical Mycology

Apologies but the data has been sitting in my inbox since March 2016...

Thanks,

Michael.

**Comment by ansell** [comment]
Created data resource and linked it to both co110 and dh5 (AMRIN data hub):

http://collections.ala.org.au/dataResource/show/dr6248

Data has been uploaded but not ingested yet.

**Comment by ansell** [comment]
Load/process/sample/index complete
