### ISSUE TITLE
Australian Antarctic Division Zooplankton data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#268]
The CSV file of the composition of zooplankton seems fair game. Metadata at https://data.aad.gov.au/metadata/records/BROKE_Fish_Zooplankton_RM8

This seems like it would fit the DwC Event type.

**Comment by ansell** [comment]
Found issue during conversion with the measurementValue in the files, but no obvious measurementType, so need to clarify the units for each measurement (which will be different for each of the three measurement types biomass/density/composition) to comply with DWC recommendations for use of measurementValue.

**Comment by ansell** [comment]
Data resource created for this at:

http://collections.ala.org.au/dataResource/show/dr6249

**Comment by ansell** [comment]
Load/process/sample/index complete
