### ISSUE TITLE
site and survey data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#27]
functionality to identify and use sites and survey events to find records.

E.g. repeat surveys
sites in an area or near here
identify data sets with surveys

**Comment by M-Nicholls** [comment]
indexes created - next step is to create site (locationID) and survey (eventID) records for a data set (ANIC look like a good candidate)

**Comment by M-Nicholls** [comment]
This hasn't come up as priority for users

**Comment by pbrenton** [comment]
This has been raised as a priority issue by DoEE and TERN. There are also several long-term monitoring citizen science projects for which site and survey context is important. The site-based context becomes much more important when looking at time-series data, especially when it is collected using standardised protocols.
