### ISSUE TITLE
DragonflyPix.com

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#272]
contact details in email on share drive /ocurrence/DragonflyPix/

I'm a keen photographer of damselflies and dragonflies and I've been studying your excellent website by way of preparing for what will, hopefully, be my next trip to Australia. I'm based in Italy but have visited Australia several times (in 2006, 2008/9 and 2011). During those trips I've shot about 800 photographs of Australian damselflies and dragonflies, which can be seen on my website www.dragonflypix.com.

With this email I would like to offer you the records of those photographs, which would include the species, date, location, and GPS coordinates (in WSG84 format) for each photograph. There wouldn't be quite 800 individual records - I tend to shoot several photographs of one and the same individual animal - but the number would be a bit high for entering them by hand in any case. I would also have to 'obfuscate' the exact location details in those cases where the information was given to me in strict confidence 

If you would be interested in my records, please do get back to me and I will prepare a list for insertion into your database.

With kind regards, and again, with compliments on your excellent website,

**Comment by ansell** [comment]
http://collections.ala.org.au/public/show/dr6435
