### ISSUE TITLE
Upload NZVH data for AVH-test

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/data-management#275]
A new data upload from Landcare Research NZ is now available here: 

"dr2153-NZVH\Sep 2016\dwca-nzvh-v2.63.zip"

This is a DwC archive and should be ready for final upload...

Note: this file is available for upload directly from Landcare Research's IPT service (see me for login details), so we could potentially automate this upload on a regular basis.

**Comment by m-hope** [comment]
Also note: once the data is uploaded we need to check that the SDS is correctly applying generalisation of coordinates for NZ sensitive species (based on this list: http://lists.ala.org.au/speciesListItem/list/dr2285;jsessionid=AE5A869FD8CFF935EEA2DCC7738C4F24)

**Comment by sadeghim** [comment]
Reprocessed for NZ sensitive species list to take effect.

**Comment by sadeghim** [comment]
@m-hope Is it a full dataset upload, and I should be deleting the old records and columns?

**Comment by m-hope** [comment]
@sadeghim - it should be a full dataset upload, but let me check with Aaron... has the new upload been completed?

**Comment by sadeghim** [comment]
Yes

**Comment by m-hope** [comment]
@sadeghim - Yes, any record that was not included in the latest update should be removed.  The previous dataset was a test upload so there will be some records that have been deaccessioned since.

**Comment by sadeghim** [comment]
Done!
