### ISSUE TITLE
AADC - southern right whale survey

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#277]
New or revised items since 29-Sep-2016
New Download    NESP_2015_SRW.zip 2015 Aerial survey data of southern right whales (Eubalaena australis) off southern Australia [Offline Data] 
http://data.aad.gov.au/aadc/portal/download_file.cfm?file_id=4659

**Comment by ansell** [comment]
Another link for this appears to be: https://data.aad.gov.au/metadata/records/NESP_2015_SRW

The link above fails with a message about logging in, even when you are logged in already.

**Comment by ansell** [comment]
Doesn't appear to be downloadable yet

<img width="865" alt="screen shot 2016-09-30 at 10 39 59 am" src="https://cloud.githubusercontent.com/assets/82365/18977023/462bcc94-86fa-11e6-9cd0-3fed20896b12.png">

It may only have metadata in the system but not data at this point.
