### ISSUE TITLE
IMOS Satellite tagging data

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/data-management#29]
Contact is Sebastien.Mancini. Email sent to @sadeghim and @M-Nicholls.
The metadata for this dataset resides here:
 http://catalogue-123.aodn.org.au/geonetwork/srv/eng/metadata.show?id=21812&currTab=simple

**Comment by sadeghim** [comment]
The data is uploaded and indexed successfully:
http://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1864&sort=first_loaded_date#tab_mapView
