### ISSUE TITLE
Missing ANWC bird call (sound) records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#296]
The ANWC bird call records are not coming through on biocache:

http://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A5ed80139-31bb-48a8-9f57-42d8015dacbb&fq=multimedia%3A%22Sound%22

only returning 5 records and none from ANWC.

**Comment by ansell** [comment]
The original ANWC data files have URLs that look like:

```
    http://www2.ala.org.au/datasets/occurrence/dr341/associatedMedia/X01860.mp3
```

Investigating how they are served and what may be the issue as they are not currently available.

**Comment by ansell** [comment]
After investigating this, there are 41955 ANWC Sound occurrence records which refer to 11845 unique URLs.

Taking the unique identifiers from those URLs and using them to interrogate the images.ala.org.au "/ws/findImagesByMetadata" API, it appears that there are about 3983 of the 11845 unique URLs that can be mapped using images.ala.org.au to sound files hosted by ALA. 

There is a clear point during the mapping (when done sequentially), where the mappings drop off, at X04337. This possibly indicates that a process which was working before that time (timestamps seem to indicate this occurred during 2014) stopped working.

There is a note on the ANWC records that all of these sound files are copyrighted and not licensed for third-party use, so it isn't clear what we should do with the 3983 images.ala.org.au files at this point. However, there are only 4 unique creator attributions, with one of them making up a large percentage  of the sounds (37974 out of 41955), so we may be able to renegotiate the licensing conditions for these files without too much hassle. @M-Nicholls, can you contact ANWC as part of your license cleanup and discuss the licensing for these sound files and whether we can get copies of the missing sound files that we don't currently have in images.ala.org.au.

**Comment by nickdos** [comment]
As a side note, I've noticed there are lots of records in images.ala.org.au that don't have explicit rights/license info on them... we might want to implement a script to populate missing rights/license from a Collectory lookup. Same goes for occurrence records. I don't think its good enough to expect users to soe how know that they have to go to another system (Collectory) in order to work out whether they can use the data/image/sounds they see in images.ala.org.au or biocache.ala.org.au

**Comment by ansell** [comment]
3414 sounds for ANWC now visible again in the index

**Comment by ansell** [comment]
TODO: check what the collectory definition for this parameter is, it should be looking in the archive for the sounds, but may not be if this parameter has been previously set in the collectory:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/40a6ddf6fe518238df5a913071edc99a04e5555e/src/main/scala/au/org/ala/biocache/load/DwCALoader.scala#L146

**Comment by ansell** [comment]
The `imageUrl` attribute does not appear in `https://collections.ala.org.au/ws/dataResource/dr341`. This needs work by a biocache store developer.

**Comment by nickdos** [comment]
I can ask Dave if he has some slack to look into it... is there a issue number in biocache-store for this?

**Comment by ansell** [comment]
No I have been tracking it all here so far.
