### ISSUE TITLE
Unlinked PERTH images in AVH

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#326]
If you do a search in the new AVH on records with multimedia, the first several hundreds of records in the result are images that are not linked to existing AVH records, so they have no metadata other than the link to the image: http://avh.ala.org.au/occurrences/search?q=*%3A*&fq=multimedia%3A%22Image%22&qc=data_hub_uid:dh9&fq=-collection_uid%3A*

Last Tuesday, June 26th, I re-delivered all those AVH records. They didn't come through. Could someone check after this weekend's re-index (I'll be away)? I have noticed before in the last three months that AVH updates haven't come through.

**Comment by nielsklazenga** [comment]
The PERTH records with the same catalogue numbers are now in there and have the images linked to them, for example:
http://avh.ala.org.au/occurrences/59536cdd-bdd7-4569-99af-d51197c453a0 and http://avh.ala.org.au/occurrences/83ae65f1-de3d-4b5e-94bb-08e9f5c0a3b4 (the first one is just the image; the second one is the AVH record, with the image).

So the empty records with only the images, but no metadata are duplicates (sort of) and should be removed.

**Comment by ansell** [comment]
@nielsklazenga There don't appear to be any unlinked images using the search in the original comment. After we receive a full dump for dr376 we can analyse which records were not loaded from it and delete those records.

**Comment by nielsklazenga** [comment]
@ansell I can't find them anymore either. Maybe close this issue?

**Comment by ansell** [comment]
I will close this and reopen if the issue reappears after the full dump is loaded.
