### ISSUE TITLE
Update marine/non-marine status and management

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#334]
IRMNG is still being maintained: http://www.irmng.org/ which the source of the ALA marine/terrestrial facet.  This data has not been updated for possibly years.

Update data and look at how this data is managed - there is no list or data set for IRMNG so there isn't proper attribution and the status isn't verifiable

**Comment by ansell** [comment]
The Darwin Core Archive for this seems to be:

http://www.irmng.org/export/IRMNG_genera_DwCA.zip

**Comment by charvolant** [comment]
The under test version of the name index has IRMG from 2018-03-20.

**Comment by ansell** [comment]
biocache-store is currently pulling in the Darwin Core Archive directly using the `update-habitat-data` command that we have to run periodically in jenkins (last run 2018-07-19):

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/bf609895f27e08e3d9e9f7539045d957c038edac/src/main/scala/au/org/ala/biocache/load/TaxonProfileLoader.scala#L48

http://localhost:9193/job/Update%20conservation%20and%20habitat%20data/

How does that relate to the name index also having IRMNG embedded in it? Can we remove `TaxonProfileLoader` once the new name index is installed?
