### ISSUE TITLE
Need to restart the AVH auto load script.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/data-management#341]
Looks like AVH records haven't been uploaded since April 2017... most likely because auto loads were temporarily halted while the new names index was loaded.

Need to reinstate the loads as the AVH has been continued to be delivered since then.  Not sure if we need to load all since then (ie: to catch all the delta changes) or just the last one???

**Comment by M-Nicholls** [comment]
caught up and automation re-enabled
