### ISSUE TITLE
Biocollect record with multiple images being duplicated

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#346]
Reported by a user - https://support.ehelp.edu.au/helpdesk/tickets/17969.

Original biocollect record with many images: https://biocollect.ala.org.au/sightings/bioActivity/index/af135759-8291-4023-8fb4-6f689234e54a

Biocache record with the first image duplicated: https://biocache.ala.org.au/occurrences/ceffbe27-2bf5-4496-8e1c-292643dd1388

Investigate why biocache record images are all duplicates.

**Comment by ansell** [comment]
The same issue also happens on biocache-clustered:

https://biocache-clustered.ala.org.au/occurrences/ceffbe27-2bf5-4496-8e1c-292643dd1388

I will ask Mahmoud how the biocollect harvesting works and go from there

**Comment by nickdos** [comment]
Thanks Peter, feel free to assign this to Mahmoud if he's better placed to look into it.

**Comment by ansell** [comment]
Mahmoud said that he is currently actively working on the biocollect script so I have reassigned it to him. There were issues in the past with duplicates when the only difference in the URL was in the parameters (as the images system stripped the parameters before checking for an existing image), but not sure if that is relevant here.

**Comment by peggynewman** [comment]
This appears to be resolved
