### ISSUE TITLE
University of Sydney Campus Flora

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#35]
At the University of Sydney we have been developing an App "Campus Flora" (iPhone only at this stage) that offers and interactive map of the plants on Campus and information that aligns with our Botany curriculum and, as anyone with an iDevice can have the App, it takes Botany to a broader audience.  https://campusflora.wordpress.com and https://itunes.apple.com/au/app/campus-flora/id918408102 

I think it would be good to have the plants on campus in the ALA and maybe USYD should be a partner of ALA esp. wrt to including the campus vege in the ALA map. 

Would this be possible? If so, how would we go about this?

*Initial response sent

**Comment by nicbarker** [comment]
Hi Guys,
I'm the dev on the project over at Sydney Uni. I built a web front end and ported our species database over into MySQL which you can find [here.](http://campusflora.sydneybiology.org) The species data including locations on campus are also available as a JSON dump [here.](http://campusflora.sydneybiology.org/species.json)  
The project has also been open sourced so if you're interesting in checking it out the repo is on bitbucket [here.](https://bitbucket.org/bio_eru/campusfloraweb)

**Comment by nielsklazenga** [comment]
Hi Nick, I have nothing to contribute to this issue, but I just checked out your web app. and think it is great.

Niels (AVH)

**Comment by sadeghim** [comment]
I am going to implement the data transformation procedure. And will report the progress and issues here.

**Comment by nicbarker** [comment]
Thanks Niels, appreciate it. We're looking to get this up and running at a couple of different unis over the next few months or so.

**Comment by nicbarker** [comment]
@sadeghim let me know if you want me to transform the data on our side, I can set up a specific api end point on our side if you like.

**Comment by sadeghim** [comment]
@nicbarker, I checked the JSON output and wanted to know are these the whole number of records you have? 255 records? Is the record id 250 missing?

**Comment by nicbarker** [comment]
Yes you're correct - record 250 in that table was deleted and replaced.
There are 255 recorded distinct species, and ~2000 individual plants (each species_location object)

**Comment by sadeghim** [comment]
@nicbarker May I get the actual occurrence records with associated media and locations? I see that for each species there are some images and it's not known which occurrence has which image. For example, the record number 3 has 16 locations but only 4 images. I assume that there are 16 occurrences but only 4 of them have images which are not known.

**Comment by nicbarker** [comment]
@sadeghim Ah I understand now. So the way our data is structured is that images are attached to the species level object (i.e one species has multiple images) not to each individual plant (i.e one species also has multiple "species_locations")

So to re-iterate, the species images are generic images of the species that we've taken, and they aren't related to individual plants on campus. The species_location objects specify the location and arborplan information, but that's it.

**Comment by sadeghim** [comment]
@nicbarker Thanks for the information, another question is that will the volume of the data grow? I mean the number of specie, or the locations and etc. If so, this API will always spit out the whole data or you think about paging or parameterising the API?

**Comment by nicbarker** [comment]
Yes, the data will most likely grow over time - although not by much. The maximum size we'd be looking at for this instance is 2-3 times the current data set. There's no pagination currently implemented but obviously if it gets too big I'll have to build something :)

**Comment by sadeghim** [comment]
@nicbarker Here is the preview upload of the records into the Atlas Sandbox : 

http://sandbox.ala.org.au/ala-hub/occurrences/search?q=data_resource_uid:drt3687

Happy to take your comments.

**Comment by nicbarker** [comment]
@sadeghim This looks fantastic! Do you guys need to do anything in particular with our images? I'm new to ALA as a concept so I'm not sure what the policy re: images is.

**Comment by sadeghim** [comment]
Regarding the images, there are some problems. These images are not associated to any occurrence. And there is not enough metadata about them: photographer's info and licence/rights.  So, uploading them as occurrence records information doesn't seem to be efficient.

If you are very kin to upload those images to the Atlas, since they are attached to the species records, you can use species list tool to upload the list and associated media. Here is the address : http://lists.ala.org.au/

**Comment by nicbarker** [comment]
Ok great, just wasn't sure what the go was. I think it's best if we leave them for the moment since as you said they're not associated with any specific occurrence - the way we gather images seems to not fit with the ALA model. I'll of course let you guys know if this changes.

In the long run, do you want me to let you know about changes to our dataset? Or is the transformation / import something you plan to do every so often?

**Comment by sadeghim** [comment]
Considering the number of records and the area that you cover, I guess the changes will not be very significant and frequent, so it can be a manual process of rerunning data transformation on this dataset which can be initiated either by you or ALA.

I created a data resource page (http://collections.ala.org.au/public/show/dr2269) for your project and wanted to know the licence that you want to put on your data (which is normally CC-BY) and the details of the contact point at Comapusflora. Please send the info to this email : data_management@ala.org.au

**Comment by nicbarker** [comment]
Wonderful. I'll get in touch with the project head Rosanne Quinnell and relay that information to her. Thanks for all your help @sadeghim !

**Comment by nicbarker** [comment]
Just to confirm @sadeghim the license we have decided to go with is [GPLv3.](https://www.gnu.org/licenses/gpl.html)
I'll email the details to the ala email address you provided.

**Comment by rquinnel** [comment]
Ok I'm here now. Soz for the delay.

Very happy with progress so far.  Re: images in CampusFlora - I have agreements from students to use image in the campus flora (iOS and WebApp) but currently this agreement does not extend to ALA. 
Wrt Usyd data, what I envisaged was that the GPS + species (so only subset of all the data in our Campus Flora) would be a collection in the ALA.  I think CC-BY would be fine for this subset of data but I quite cautious and wouldn't mind checking with the other stakeholders (Grounds staff and legals here at USYD). 
I recall from previous emails with Peter Doherty (ALA) that there were a couple of ways to go with offering a collection. I think at the minimum having users be able to search "The University of Sydney" or postcode 2006 would allow these data to be viewed as collection. This collection is slightly different to a herbarium (there is a list of these in the ALA and these are all backed at the institutional level) and a collection that folk are adding too a lot (as in the case of sightings of animals in wetlands areas for example). Our collection is a bit different. 
Let me think for a bit and I'll get back to you.

**Comment by rquinnel** [comment]
Oh and there will be some redundancy as I see ALA harvest from iNaturalist and CFlora used iNaturalist to survey plants that weren't in our ArborPlan database.

**Comment by M-Nicholls** [comment]
from an email from rquinnel:

I have checked with our Head of Grounds and can confirm that the ArborPlan data (the bulk of the data in CampusFlora) can be shared. It would make sense to me to offer the CampusFlora as a collection in the same way that the John Ray Herbarium is offered as a collection. The locations and species could be derived from the CampusFlora database and added to the ALA data set but not the photos or descriptive text as we are using these with permission (see notes below). 
Please note:
•	that the iNaturalist data is replicated in the CampusFlora database; it is possible to ID ArborPlan plants in the CF database for mapping to reduce replication. 
•	the copyright holders of all photos are the students who took the photos. 
•	photos are of the species on campus but not of every individual in that species. 
•	the pin for John Ray Herbarium is in a strange place and ought to be associated with the HeydonLawance building (-33.885276, 151.186090) on Camperdown campus and be close-ish to the Entomology and Fossil collections.


Much of the descriptive text for the CampusFlora collection can be found from the WebApp page: 
Acknowledging the traditional custodians upon whose ancestral lands the University of Sydney campuses stand. Campus Flora maps the locations of more than 2000 individual plants from 80 families on campus grounds and provides a botanical description of each plant and information on its distribution. Campus Flora not only extends the teaching of botany from the classroom into the University of Sydney campus grounds but it enables us to share our learning resources with the broader community. “Trails” highlight the important aspects of select plant groups and we have developed these to align with our science curriculum.
