### ISSUE TITLE
Data feeds to NSW OEH

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#350]
provide data set to NSW OEH of records in ALA that match their names list (NSW only, exclude bionet Atlas records)

https://biocache.ala.org.au/occurrences/search?q=species_list_uid%3A%22dr8308%22&fq=cl927%3A%22New+South+Wales+%28including+Coastal+Waters%29%22&fq=-data_resource_uid%3A%22dr368%22

include species list

also records in ALA not in their list with record count

**Comment by charvolant** [comment]
Complete set of records matching/not matching OEH names sent to OEH 3/9/18. OEH supplied records were not excluded, since it's possible to filter them out and it gives a more complete picture.

**Comment by M-Nicholls** [comment]
•	ALA to produce custom download with all fields (fields to have unique names) 
- Include the row_key - these are the unique key fields for each data set?
- Include data set ID
- Include ALA taxon identifier
- Add in the ACT and Jervis bay records if they are excluded based on the current set of filters

•	Produce a separate data set for stateProvince:NSW (rather than the spatial intersection used in the current query), this will include records without coordinates
•	ALA to produce file of ALA taxon ID matches to OEH taxon ID
•	Phil to advise if there are any synonym issues in ALA-OEH name matching

**Comment by charvolant** [comment]
Confirmed that elements in citations.csv (and README.html) have different uids, particularly data provider/data resource pairs.

**Comment by charvolant** [comment]
Sample dump file (just for Red Wattle birds in the ACT to keep things simple) at https://biocache.ala.org.au/biocache-download/6caf5be6-6ab9-349e-9edc-47db37d02ef2/1542249668434/records-2018-11-15-1542249644-NSW-OEH.zip

List of occurrences for NSW by taxon at https://biocache.ala.org.au/biocache-download/6caf5be6-6ab9-349e-9edc-47db37d02ef2/1542238118991/nsw-2018-11-15.zip

Taxon results matched against the OEH taxonomy at https://www.dropbox.com/s/14otroorbm4k68v/matches-2018-11-15.zip?dl=0

**Comment by charvolant** [comment]
Pending questions on relationships between fields from OEH. Once these are resolved, another data dump will be needed.
