### ISSUE TITLE
Generate static downloads from new infrastructure

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#363]
The static download files on https://downloads.ala.org.au/ are out of date and require updating. 

As a short term work-around to ala-downloads#27, we could copy and paste the DOI links from each file into the text description on downloads server (assuming they generated static downloads have a DOI).

**Comment by ansell** [comment]
Job is at:

http://aws-scjenkins.ala:9193/job/ok-Bulk data exports for downloads.ala.org.au

Had permission and disk space issues the last times it was run.

**Comment by ansell** [comment]
The method we previously used for this was removed and currently has no replacement. Will need to look into this again after the pipeline work is complete.

**Comment by ansell** [comment]
Working on a new replacement method for static download generation.
