### ISSUE TITLE
Make Distribute Row Keys jenkins job more resilient

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#372]
Adding some retries to the ``Distribute Row Keys`` jenkins job so it doesn't fail on a single IO failure may be useful based on the past 24 hours, although if there are underlying issues that aren't transient it may not have any effect.

Part of the issue may have been the business requirement to restart the bstore nodes each time they are required.

**Comment by ansell** [comment]
There were two more instances of the ``Distribute rowkeys`` job failing overnight causing data loads not to occur fully

**Comment by sadeghim** [comment]
It was a bug in determining the number of lines per file. 
Now if we have less than 4 lines in the file, we'll add more empty lines to generate one file per node.
Also the rounding up of the number of lines per file is fixed now.
```
lines=$((($total_lines+$BSTORE_NODE_COUNT-1)/$BSTORE_NODE_COUNT )) #Rounding up the number
```

**Comment by ansell** [comment]
There are still some minor issues with this on very small datasets. It failed again on ``dr5829`` that has 3 records.

**Comment by ansell** [comment]
There were no failures in the recent history (less than one day due to old build removals), so closing this as fixed again
