### ISSUE TITLE
Blue Trap Bees

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#38]
A detailed repeat survey data set including explicit absence records

Initial processing to flatten out into individual records has been done, follow up with owner for remaining site/event details

**Comment by charvolant** [comment]
Data provider would like to be able to select datasets based on the way the data was collected: survey data, individual events, museum records etc with an eye to being able to compare eg presence/absence profiles for different techniques.

**Comment by charvolant** [comment]
Sample uploaded. Waiting for response from Saul

**Comment by charvolant** [comment]
Uploaded to dr2014.

Saul has another tranche of data using a different sampling method. So onwards and upwards!

**Comment by charvolant** [comment]
Data for malaise traps loaded to dr2014.

Using the same catalog number scheme as the original with species abbreviations.
