### ISSUE TITLE
ACT weed data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#390]
Just wondering if you can use our ACT weed mapping data from ArcGIS On-line.  There are a few options for the format I can download.   It is very comprehensive – so will be useful for ALA.

To see the scale of what we have- this web app map shows the data for 2016-17: http://actgov.maps.arcgis.com/apps/webappviewer/index.html?id=8304b4b35bc942cbaea4a07933bdd18c 

Steve Taylor \| Senior   Invasive Weeds Officer \| m 0411 166 340   High Risk Invasive Plants   Team   http://www.environment.act.gov.au/parks-conservation/plants-and-animals/Biosecurity/weeds |  
-- | --

**Comment by ansell** [comment]
My last email to them about this was on 3 November 2017 and they have not replied
