### ISSUE TITLE
JCH data update

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#391]
I wish to submit a copy of the current Janet Cosh Herbarium database to you. 
I attach here both the Excel spreadsheet and the CSV version (not sure if you need the latter).
I hope you are still the contact people to receive this data for ALA & AVH. 
I have deleted all specimens without grid references (unfortunately there are 1000s of entries that fall in this category) but if you want the entries without GRs please advise. 
I have tidied up many typos but there are bound to be others I have missed, and if so, please return questionable entries for me to rectify. 
The last time our database was submitted was Nov 2015 I believe, if this is of importance to you to refer back to.

Please let me know if this is well received to this location, or suggest where better it should be sent.

Thankyou

**Comment by nielsklazenga** [comment]
Was done years ago.
