### ISSUE TITLE
reload SAMA data - fix for materialSample and scientificName issues

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#394]

**Comment by sadeghim** [comment]
There is a bug here:
https://github.com/sadeghim/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/processor/DefaultValuesProcessor.scala#L34

That set the raw value to default even though the raw field has already some value.

Removed the default value from DR and reprocessing should fix the issue.

**Comment by sadeghim** [comment]
It's solved now.

**Comment by sadeghim** [comment]
Open this again as there are some issues with the data file.

**Comment by sadeghim** [comment]
Done.
