### ISSUE TITLE
Australian Antarctic Data Centre

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#4]
Review current data sets and load new ones from the AADC.
Review capabilty for automated harvest and use of API

**Comment by sadeghim** [comment]
The migration to IPT is started and the data sets will be gradually transferred to the new server. I will update the data resources entries in the Collectory accordingly.

**Comment by sadeghim** [comment]
These data resources are updated so far:

| Name | DR |
| --- | --- |
| Antarctic Marine Protists species checklist | **dr91** |
| Elephant Seal Sightings, Heard Island | **dr87** |
| Seabirds of the Southern and South Indian Ocean | **dr165** |
| Weddell Seal census, Vestfold Hills, Antarctica | **dr85** |
| Weddell Seal Sightings, Vestfold Hills, Antarctica | **dr86** |

**Comment by sadeghim** [comment]
Added these :

| Name | DR |
| --- | --- |
| Australian Antarctic Division Herbarium | **dr90** |
| National Whale and Dolphin Sightings and Strandings Database | **dr93**|
| Orca observations from the shores of Macquarie Island | **dr94** |
| Southern Ocean Continuous Zooplankton Recorder (SO-CPR) Survey | **dr95** |
| Cetacean Sightings Survey and Southern Ocean cetacean program | **dr96** |

**Comment by sadeghim** [comment]
Added these :

| Name | DR |
| --- | --- |
| Antarctic Fur Seal Populations on Heard Island Summer 1987-1988 | **dr473** |
| APIS - Antarctic Pack Ice Seals 1994-1999, plus historical data from the 1980's | **dr97**|

**Comment by sadeghim** [comment]
Added these:

Added these :

| Name | DR |
| --- | --- |
| Inventory of Antarctic seabird breeding sites | **dr136** |
| Macquarie Island Fur Seal Database | **dr99**|

**Comment by sadeghim** [comment]
Added these :

| Name | DR |
| --- | --- |
| Kelp rafts in the Southern Ocean | **dr139** |
| Electron Micrograph Database - Marine Specimens | **dr137** |
| Electron Micrograph Database - Terrestrial and Limnetic Specimens | **dr138** |
