### ISSUE TITLE
New data export files for NSW OEH

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#400]
•	ALA to produce custom download with all fields (fields to have unique names) 
o	Include the row_key 
o	Include data set ID
o	Include ALA taxon identifier
o	Add in the ACT records if they are excluded based on the current set of filters

check metadata for duplicate entries - most likely just dr/co/dp duplication

•	Produce a separate data set for stateProvince:NSW (rather than the spatial intersection used in the current query), this will include records without coordinates

•	ALA to produce file of ALA taxon ID matches to OEH taxon ID (Phil, is there an updated names list for us to run the match against?)

**Comment by M-Nicholls** [comment]
covered by https://github.com/AtlasOfLivingAustralia/data-management/issues/350

**Comment by charvolant** [comment]
Query for:

* State label is NSW; or
* State label is ACT; or
* Region is NSW including coastal waters; or
* Region is ACT; or
* Region is Jervis Bay

And matches species in ALA also in OEH

https://biocache.ala.org.au/occurrences/search?q=(state%3A%22New%20South%20Wales%22%20OR%20state%3A%22Australian%20Capital%20Territory%22%20OR%20cl927%3A%22New%20South%20Wales%20(including%20Coastal%20Waters)%22%20OR%20cl927%3A%22Australian%20Captial%20Territory%22%20OR%20cl927%3A%22Jervis%20Bay%20Territory%22)&fq=species_list_uid:dr8308

**Comment by charvolant** [comment]
Actually, better than that, eliminate dr368 (OEH Atlas of NSW Wildlife) from the source, since that will knock out ~9m records.

https://biocache.ala.org.au/occurrences/search?q=(state%3A%22New%20South%20Wales%22%20OR%20cl927%3A%22New%20South%20Wales%20(including%20Coastal%20Waters)%22%20OR%20cl927%3A%22Australian%20Captial%20Territory%22%20OR%20cl927%3A%22Jervis%20Bay%20Territory%22)&fq=species_list_uid%3Adr8308&fq=-data_resource_uid:dr368

**Comment by charvolant** [comment]
Sample dump file (just for Red Wattle birds in the ACT to keep things simple) at https://biocache.ala.org.au/biocache-download/6caf5be6-6ab9-349e-9edc-47db37d02ef2/1542249668434/records-2018-11-15-1542249644-NSW-OEH.zip

List of occurrences for NSW by taxon at https://biocache.ala.org.au/biocache-download/6caf5be6-6ab9-349e-9edc-47db37d02ef2/1542238118991/nsw-2018-11-15.zip

Taxon results matched against the OEH taxonomy at https://www.dropbox.com/s/14otroorbm4k68v/matches-2018-11-15.zip?dl=0
