### ISSUE TITLE
Spatial Layers upload improvements

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#402]
issues to improve spatial layer loading

**Comment by ansell** [comment]
nectar-spatial-test has now been setup, leaving nectar-spatial-staging available for layer uploads: https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/28

The guide to the many steps required to load layers is on the ALA wiki https://github.com/AtlasOfLivingAustralia/data-management/issues/445

This can be closed at this point.
