### ISSUE TITLE
Add Start/Stop VM support to Delete Records By Query Jenkins job

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#416]
The ``Delete Records By Query`` jenkins job on ``aws-scjenkins`` does not currently have support for starting and stopping the bstore VMs by itself. 

It would be very useful to be able to directly run this job on its own. 

When the copy uuids.txt command runs, it may be silently fail at that point right now, as it gets to the proceed or abort stage without the bstore vm's being up, even though the log before that point seems to show the copy operations succeeding.

**Comment by sadeghim** [comment]
Done.
