### ISSUE TITLE
Load Dataset : Robert Read 20181116

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#422]
Load new dataset provided by Robert Read.

- [x] Download dataset from Dropbox as zip file
- [x] Fix zip file so it doesn't contain a 0-length dummy entry for `/`
- [x] Map non-standard field names to Darwin Core field names
- [x] Create Darwin Core Archive from the mapped file, without images
- [x] Create a new data resource to hold these observations `https://collections.ala.org.au/public/show/dr13290`
- [x] Upload the Darwin Core Archive to collectory
- [x] When images is ready for loading again, add images to the archive, reload, and wait for reindex to occur again to check
- [x] Ask and wait for details for the data resource name/license/citation/etc.
- [x] Load records into the new data resource
- [x] Wait for reindex to occur and check

Refs ticket 36888 on helpdesk

**Comment by javier-molina** [comment]
URL for FD ticket https://support.ehelp.edu.au/a/tickets/22774

**Comment by ansell** [comment]
Moving this to `Waiting for` as the dataset does not have licenses available for either occurrence records or images at this point.

**Comment by ansell** [comment]
This is blocked by https://github.com/AtlasOfLivingAustralia/biocache-store/issues/350
