### ISSUE TITLE
Automate deployment of releases

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#423]
We want to move from developers running ansible (or copying war files) manually to a "push button" solution that allows:
- ansible to be run the same way, every time
- know who ran the deployment
- log of all the deployment events
- have a roll-back option
- only allow release versions (no SNAPSHOTs to prod)
- update dev/test servers with different version numbers than prod (configurable)
Solution could be Jenkins or some other off the shelf OS option

**Comment by ansell** [comment]
Roll-back requires that the entire original system be untouched by the deployment, which is done on an entirely fresh system. There is no way to guarantee or make rollback simple if the existing system is being modified. You could think up any number of use-case specific rollback mechanisms, but each would require specific attention and devops time to design, implement, debug, and monitor.

**Comment by nickdos** [comment]
Rolled into new issue (#464) - slightly wider scope.

**Comment by nickdos** [comment]
> There is no way to guarantee or make rollback simple if the existing system is being modified. 

Yes, this is true. It will probably need to be an optimistic roll-back that assumes only config files and code artefacts have changed (war file or runnable jar). This will cover some risk but not 100% as you stated. 

We probably need to think about VM/container snapshots and combined with external log file storage will minimise data loss in the case of needing to do a full roll-back.
