### ISSUE TITLE
Lat and Lon are same number

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#427]
Trigger by email from GBIF - https://support.ehelp.edu.au/helpdesk/tickets/22148

For some records like: https://biocollect.ala.org.au/sightings/bioActivity/index/f828ee72-1cfa-4143-83dc-b42369ed1a17 Lat and Lon is exactly same.

- [ ] short term fix is to add a country code all "ALA Sightings" records, which would fix the problem from GBIF's end.

**Comment by nickdos** [comment]
Moved to data-management, as I can't see anyway BioCollect folks can fix data that was imported over 2 years ago. 

Changing description to see if we can add a country code to all ALA sightings records.

**Comment by djtfmartin** [comment]
There isn't any mechanism currently for not exporting certain records to GBIF.
I think we should just delete these records. I don't see any value in them being exposed in ALA or GBIF. We could create an archive of them just in case there later becomes a means to make them recoverable.

**Comment by peggynewman** [comment]
This record https://biocache.ala.org.au/occurrences/3d862fe7-d9b1-4844-ba27-d010625fe0c0
suspiciously passed the negative lat/long geospatial tests. We can't update the record to have AU country ourselves, I don't think that is necessarily clear from other elements of the record and the onus should be on the data provider. Also 2 users have flagged the problem - Biocollect users should be able to see the flags on their records in the ALA and fix them (ping @temi @pbrenton in case they can see some other way around this problem). The DQ filters should theoretically remove them from default view in the ALA. I'm closing this.
