### ISSUE TITLE
Ensure that NZVH data is not being sent to GBIF

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#429]
NZVH have asked us to ensure that their data is not being sent to GBIF and fix any past instances where it was sent. The setting in the collectory https://collections.ala.org.au/dataResource/show/dr2153 appears to show GBIF as not getting NZVH data, but a resource named NZVH at GBIF still exists and must be deleted:

https://www.gbif.org/dataset/847375df-8ac8-4189-a8d6-deaefb90355c

**Comment by djtfmartin** [comment]
Resource has been deleted.
