### ISSUE TITLE
Jaeger-Moran Plants

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#432]
data on share drive - Jaeger-Moran plants

\ALA Data\File Store\Occurrence\jaegar-moran plants

**Comment by CorinnaPaeper** [comment]
The csv file for data upload is in the specified folder (20190805 Moran data - Plants.csv). DwC fields have been added where possible. 

Origin: Jaeger-Moran Plants.mdb > CP_001qry_Plants sightings DwC fields
