### ISSUE TITLE
Records for SDS blocked species appearing in ALA

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#433]
Reported by Ken W in ticket https://support.ehelp.edu.au/a/tickets/25712

https://biocache.ala.org.au/occurrences/search?q=lsid%3AALA_Halyomorpha_halys#tab_recordsView
and
https://biocache.ala.org.au/occurrences/eb577dc9-47b6-4716-a4ff-0e07996b20cd

Both show a "rejection" message `PPC1-A1	Your record Bactrocera papayae,1995-11-06 and Cairns (general) has not been forwarded to the Atlas of Living Australia.` yet appear in the biocache with full resolution coordinates.

**Comment by M-Nicholls** [comment]
essentially this processing was implemented as a prototype for a pest SDS but was never approved for full production implementation (no one would give us the list of pests needed to use as the basis and take responsibility for it).

**Comment by Rita-C** [comment]
@timhicks-ala , can you please check if this is still happening?

**Comment by timhicks-ala** [comment]
@Rita-C I can see no occurrence records currently of Bactrocera dorsalis that aren't preserved specimens, and no Australian-based results for Halyomorpha halys (it actually looks like this is no longer recognised by BIE). None appear to have that rejection message that I can see.

**Comment by Rita-C** [comment]
@nickdos cc @timhicks-ala , can we close this ticket?
