### ISSUE TITLE
Coordinates in Northern hemisphere

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#437]
Some records have wrong coordinates in northern hemisphere:
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr836&qc=&wkt=MULTIPOLYGON(((139.833984375+18.06231230454674,139.833984375%2010.574222078332806,148.798828125%2010.574222078332806,148.798828125%2018.06231230454674,139.833984375%2018.06231230454674)))#tab_recordsView

**Comment by ansell** [comment]
Sent an email to the previous contact for dr836 about this issue and also to see if we can setup an email contact so the annotations can be sent through to them from Biocache.

**Comment by ansell** [comment]
The 0.0 coordinates can be found using the following (for reference) as they were identified as data quality issues

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr836&fq=(assertions%3A%22zeroCoordinates%22%20OR%20assertions%3A%22zeroLatitude%22%20OR%20assertions%3A%22zeroLongitude%22)#tab_recordsView

The data resource owner is tracking down the origin of these errors which appear in the source data, so will close this issue.
