### ISSUE TITLE
index all Darwin Core fields

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#444]
All darwin core fields should be included in the index - e.g. geodeticDatum, organismRemarks and verbatimElevation are all missing from the index

**Comment by djtfmartin** [comment]
geodeticDatum is there - its just called "datum" and for some reason is missing the DWC mapping.

There is a CSV download of the indexed fields here that makes it a bit easier to see what the current state of play is:

http://biocache.ala.org.au/ws/index/fields.csv
