### ISSUE TITLE
NSW Waterwatch BDRS

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#45]
http://root.ala.org.au/bdrs-core/nswww/home.htm

**Comment by charvolant** [comment]
Created DwCA transformation code - https://github.com/charvolant/dwca-ala-transform

**Comment by charvolant** [comment]
Waiting for comments. Also, would this be a good thing to put into the biocache store while we're about it?

**Comment by charvolant** [comment]
DWCA end-point for sample http://root.ala.org.au/bdrs-core/nswww/webservice/application/downloadDwca.htm

Developed mapping service

**Comment by charvolant** [comment]
Script for ACT and Southern Tablelands Weed Spotter built.

**Comment by charvolant** [comment]
Loaded ACT BioBlitz to http://collections.ala.org.au/public/show/dr4577

There are a large number (~15%) of 'Unlisted species' entries. These are loaded, since someone saw something there. There are catalogNumbers so correct identifications can be uploaded.

**Comment by charvolant** [comment]
Loaded ACT and Southern Tablelands Weed Spotter (just surveys 169 and 206).
Updated jenkins script on mccartney to load using the DwCA transformer on dury

**Comment by charvolant** [comment]
Loaded Atlas of Life in the Coastal Wilderness to http://collections.ala.org.au/public/show/dr702 and updated jenkins job

**Comment by charvolant** [comment]
Loaded Condamine Alliance to http://collections.ala.org.au/public/show/dr4608

**Comment by charvolant** [comment]
CCSA Feral Or Peril has absence records for survey 86 and access via http://feralperil.ala.org.au/bdrs-core/portal/25/webservice/application/downloadDwca.htm

**Comment by charvolant** [comment]
CSIRO Yellow Box access via http://yellowbox.ala.org.au/bdrs-core/portal/22/webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4611

**Comment by charvolant** [comment]
Flora and Fauna of Wamboin and Bywong available at http://root-uat.ala.org.au/bdrs-core/ihv/webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4612

**Comment by charvolant** [comment]
GER-K2C loaded to http://collections.ala.org.au/public/show/dr4614

**Comment by charvolant** [comment]
GER-S2S at http://s2s.ala.org.au/bdrs-core/portal/12/home.htm access via http://s2s.ala.org.au/bdrs-core/portal/12/webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4621 set up jenkins job for monthly harvesting

**Comment by charvolant** [comment]
GER-SH at http://sh-birds.ala.org.au/bdrs-core/portal/10/home.htm access via http://sh-birds.ala.org.au/bdrs-core/portal/10/webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4625 set up jenkins job for monthly harvesting

**Comment by charvolant** [comment]
Mangrove Watch at http://www.mangrovewatch.org.au No direct access to data; need contact.

**Comment by charvolant** [comment]
Bird Atlas NSW at http://root-uat.ala.org.au/bdrs-core/nsw-ba/home.htm access via http://root-uat.ala.org.au/bdrs-core/nsw-ba/webservice/application/downloadDwca.htm there's an existing upload of http://collections.ala.org.au/public/show/dr1089 with 3m-odd records. There's also another empty DR at http://collections.ala.org.au/public/showDataResource/dr3378 All records from BDRS look like they've arrived after the main upload, so adding to dr3378

**Comment by charvolant** [comment]
Bathing Birds at root.ala.org.au/bdrs-core/npansw/home.htm access via root.ala.org.au/bdrs-core/npansw/webservice/application/downloadDwca.htm

Only including records with `datasetID == "urn:lsid:bdrs.ala.org.au:Survey:289"` it would be nice to add ` and not deleteThisRecord == "true"` but the filter works on the original record, not the transformed record. So manually deleting from CSV file.

Loaded to http://collections.ala.org.au/public/show/dr4638

**Comment by charvolant** [comment]
NSW Waterwatch at http://root.ala.org.au/bdrs-core/nswww/home.htm loaded to http://collections.ala.org.au/public/show/dr4645 set up jenkins job to do monthly harvesting.

Note that the mapping file *must* be encoded in ISO-8859-1 for tomcat to interpret the file correctly. Otherwise, the micro symbol is encoded incorrectly.

**Comment by charvolant** [comment]
Redland City council at http://root.ala.org.au/bdrs-core/rcc/home.htm via root.ala.org.au/bdrs-core/rcc//webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4652 set up jenkins job for monthly harvesting

**Comment by charvolant** [comment]
Scenic Rim Regional Council at http://root.ala.org.au/bdrs-core/scenicrim/home.htm Has one record in it.

**Comment by charvolant** [comment]
Scotland Island at http://root.ala.org.au/bdrs-core/scotis/home.htm has one record.

**Comment by charvolant** [comment]
Tweed Council Koala count http://root.ala.org.au/bdrs-core/tweed/home.htm and Tidbinbilla http://root.ala.org.au/bdrs-core/tbbilla/home.htm also only have a few records between them.

**Comment by charvolant** [comment]
Upper Murrumbidgee Waterwatch at http://root.ala.org.au/bdrs-core/umww/home.htm via http://root.ala.org.au/bdrs-core/umww/webservice/application/downloadDwca.htm loaded to http://collections.ala.org.au/public/show/dr4659 Active site, set up jenkins harvesting job

**Comment by charvolant** [comment]
Weed biological control at http://root.ala.org.au/bdrs-core/wbiocont/home.htm via http://root.ala.org.au/bdrs-core/wbiocont/webservice/application/downloadDwca.htm

Requires generating a second record for the host

**Comment by charvolant** [comment]
SA Discovery Circle at http://www.discoverycircle.org.au/ via http://root-uat.ala.org.au/bdrs-core/unisa/webservice/application/downloadDwca.htm

**Comment by charvolant** [comment]
BDRS for some reason encodes `John O'Grady` as `'John O"'Grady'` This doesn't pass muster in the GBIF DWCA reader for some completely inexplicable reason totally unrelated, no doubt, to it not being a sensible encoding.

**Comment by charvolant** [comment]
Added `fixBdrs` option to dwc-archive-plugin to fix escape errors
