### ISSUE TITLE
Three different structures for the last three MEL_AVH "delta" files

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#451]
Two of the last three `MEL_AVH` (`dr376`) delta files will need to be manually patched before loading them, negating any benefit from the use of delta files compared to full dumps.

The first file looks like it is intact and correct, with the extension file name in the `meta.xml` matching the extension file name in the archive:

```
# unzip -l avh_delta_20190206_1413.zip 
Archive:  avh_delta_20190206_1413.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 28877748  2019-02-06 14:13   unit.csv
      158  2019-02-06 14:13   identification_history.csv
    18261  2019-02-06 14:04   meta.xml
     4895  2018-09-05 11:42   eml.xml
---------                     -------
 28901062                     4 files
```

In the next case, the `meta.xml` file (with an oddly out of date timestamp) contains a reference to an extension file `identificationhistory.csv` (note the difference to the first delta), but none was included, which likely caused the Darwin Core Archive loader to fail:

```
# unzip -l avh_delta_20190221_1650.zip 
Archive:  avh_delta_20190221_1650.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  5083162  2019-02-21 16:50   unit.csv
    18260  2018-09-05 11:42   meta.xml
     4895  2018-09-05 11:42   eml.xml
---------                     -------
  5106317                     3 files
```

In the case of the latest file, from dated `20190305_1830`, the extension file is against named `identification_history.csv` in the `meta.xml`, but in the archive it is named `determinationhistory.csv`:

```
# unzip -l avh_delta_20190305_1830.zip 
Archive:  avh_delta_20190305_1830.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
592195183  2019-03-05 18:34   unit.csv
      158  2019-03-05 18:30   determinationhistory.csv
    18261  2019-02-06 14:04   meta.xml
     4895  2018-09-05 11:42   eml.xml
---------                     -------
592218497                     4 files
```

**Comment by nielsklazenga** [comment]
Thanks @ansell and sorry, that was the same error we had before. I thought I had fixed that. Will try to get it right tomorrow.

**Comment by nielsklazenga** [comment]
Hi @ansell, as it happens I just got an IPT up last week, so I can fix this once and for all. Are you happy for me to start providing the entire data set every week from now? Our IPT is inside our network for now, so I would still upload the DwCA to the upload server.

**Comment by ansell** [comment]
Hi @nielsklazenga Yes, providing the entire dump each week will make it much easier to work with the dataset and find issues. Uploading it to the upload server is the best way to do that if the IPT instance isn't visible. We are pulling the NZVH full dump from their semi-private (we have a username/password to use) IPT instance each week, so we can replicate that easily in future for MEL_AVH if it goes that way.

**Comment by nielsklazenga** [comment]
Thanks @ansell. Then that's what we'll do. Won't get very far with it anymore today, but hopefully next week.

**Comment by nielsklazenga** [comment]
@ansell, just loaded a DwCA produced by our IPT onto the upload server. Was a bit of a struggle, as PostgreSQL and IPT are not a great combination with data sets of this size. It kept freezing after about 3,000,000 records. I now migrate it to MySQL first and that works fine.

**Comment by nielsklazenga** [comment]
@ansell, could you check on the AVH upload? It hadn't come through this morning. The DwCA I uploaded last week comes from an IPT, so the structure should be okay.

**Comment by ansell** [comment]
I am back to work today and will look into loading from the full MEL_AVH Darwin Core Archive today.

**Comment by nielsklazenga** [comment]
Thanks @ansel, that has come through now. There are some records that shouldn't be there, not sure where they come from. Could you remove them?

https://avh.ala.org.au/occurrences/search?q=*:*&fq=data_resource_uid:%22dr376%22&fq=last_load_date:[*%20TO%202019-05-01T00:00:00Z]

(So, all the records that were not updated with the last load).

**Comment by ansell** [comment]
I will remove those records.
