### ISSUE TITLE
15,018 records from 1770 including species described after 1770

### ISSUE THREAD

**Issue by ManonGros** [AtlasOfLivingAustralia/data-management#452]
The [Australian National Wildlife Collection provider for OZCAM](https://www.gbif.org/dataset/0debafd0-6c8a-11de-8225-b8a03c50a862) contains [561 records](https://www.gbif.org/occurrence/search?dataset_key=0debafd0-6c8a-11de-8225-b8a03c50a862&year=1770) from 29 April 1770.
And the [WildNet - Queensland Wildlife Data](https://www.gbif.org/dataset/e4473544-f4cd-4429-b791-39d6e1fdb0a4) contains [14,457 records](https://www.gbif.org/occurrence/search?dataset_key=e4473544-f4cd-4429-b791-39d6e1fdb0a4&year=1770) from January, April, May June and August 1770.

Many of these records include species described after 1770 (for example, [17 occurrences of platypuses](https://www.gbif.org/occurrence/search?taxon_key=2433376&year=1770), see related issue reported on the GBIF portal feedback system here: https://github.com/gbif/portal-feedback/issues/1915).

Would it be possible to check if these records are correctly dated? Thanks!

**Comment by M-Nicholls** [comment]
The ANWC records are dated as "Pre 1900" and the way to express that in DwC eventDate was to select a date range:

Theoretically, this means that the earliest date they could possibly have been collected would be the first day that Captain Cook touched down in Australia, and have given a date range =  29/04/1770 – 31/12/1900. Presently a record which has verbatimEventDate = ‘PRE 1900’, gets an eventDate = 1770-04-29/1900-12-31

We are discussing alternatives that may express this better.
