### ISSUE TITLE
Load latest records from iNaturalist API

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#454]
**Instructions**

- [x]  Use the iNaturalist API to load daily deltas (I believe using the updated_since parameter)

- [x]  Refer to Patrick’s email 10 May for using the recommended ‘id_above’ technique as per http://api.inaturalist.org/v1/docs/#!/Observations/get_observations

- [ ]  It is anticipated that this job will run daily and should not be used to load more than a day or two’s records. Can we build something in that stops that happening?

- [x] Refer to spreadsheet for Darwin Core field mappings to replicate those used in the extract (or refer to: https://github.com/inaturalist/inaturalist/blob/master/lib/darwin_core/occurrence.rb)

**Comment by sadeghim** [comment]
@peggynewman I didn't get the 3rd part. Could you please clarify that bit for me?

**Comment by peggynewman** [comment]
@sadeghim If a load fails for more than a week, would we be better off to use the full DwC extract to do a load rather than use the API?
