### ISSUE TITLE
update biocollect data load to include license

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#468]
Update the load from biocollect to include the license informatio  and attribution when setting up the data resource.  If no license has been selected then don't set up the dr or load the data

Attribution to default to "project name (url)"

**Comment by pbrenton** [comment]
I think that the BioCollect API will also need updating to include all of the activity metadata attributes. Should also pass through the DQ/QA attributes too.

**Comment by sadeghim** [comment]
Regarding the licensing, this should be done during Data Resource creation which is done on bioCollect side. Maybe @chrisala can change the code to accommodate this.

**Comment by sadeghim** [comment]
Regarding the additional attributes in the darwincore records, I need to change the code to have the those extra fields in the files to be ingested into the system.

If we want to avoid this step, and automatically have all the fields and changed appear on the biocache, I need to change the harvester to load all fields (or filter out some specified fields but load the rest). Also on ecodata side, we need to have full darwincore terms that don't need any processing in the harvester.

**Comment by sadeghim** [comment]
Closing this issue:
AtlasOfLivingAustralia/ecodata#556
AtlasOfLivingAustralia/ecodata#557
#507
