### ISSUE TITLE
Load images directly into the image server

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#472]
As part of iNat load, try to load images directly into the image server.
#175

**Comment by djtfmartin** [comment]
@sadeghim Can we hold off on this work for now ?

With changes to image-service (which i hope to deploy this week to production) and some modifications on this branch

https://github.com/AtlasOfLivingAustralia/biocache-store/tree/feature/fasterImageLoading

Loading iNaturalist shouldnt be a problem. The first load should take approx 6 hrs, and subsequent loads should be very quick with the changes in image-service and biocache-store

cc @nickdos @M-Nicholls
