### ISSUE TITLE
Infrastructure Performance Improvement

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#481]
pieces of work to improve ALA systems performance

- server upgrades
- data loading and processing speed
- query results performance
(e.g. doc values)
- speed of page display
- ...

**Comment by ansell** [comment]
This is effectively blocked for biocache infrastructure by https://github.com/AtlasOfLivingAustralia/data-management/issues/412

**Comment by ansell** [comment]
The CAB plan for Cassandra Cluster upgrade from m5.2xlarge to i3.xlarge was tracked in https://github.com/AtlasOfLivingAustralia/data-management/issues/485

**Comment by ansell** [comment]
The work necessary for the Cassandra Cluster upgrade is being tracked in https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/290
