### ISSUE TITLE
Cassandra server changes

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#485]
- [x] Document proposed cassandra server changes for CAB
- [x] Testing (performance and load) plan
- [x] Deployment plan
- [x] Rollback plan

**Comment by matthewandrews** [comment]
The first stage would be cassandra.  Production solr changes can wait until after the test solr cloud is built.

Steps involved in the cassandra change:
 - take a snapshot of production data
 - create 4 new cassandra nodes
 - install cassandra and configure
 - load new nodes with a copy of production data from snapshot
 - performance testing of new nodes
 - delete the copied data from new nodes
 - add the new nodes to the production cluster
   (cassandra automatically copies data to the new nodes)
 - once new nodes are ready, remove the old nodes from the production cluster

Rollback for most issues is simple: just add the old nodes to the production cluster and remove the new nodes. If there is actual loss or corruption of data (unlikely), we would restore from the original snapshot.

**Comment by ansell** [comment]
The equivalent tracking issue for Solr (which is independent as long as the node counts don't change) is at https://github.com/AtlasOfLivingAustralia/data-management/issues/487
