### ISSUE TITLE
Flickr Harvesting Improvement

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#49]
Review the flickr harvesting application and flickr API to see if there is any room for improvement.

**Comment by sadeghim** [comment]
Discovered that it gets the photos from now back to 2010 which was set in data resource page. The **start date** at connection properties is updated to 01-01-2015 and the whole ingestion process took 22 min compare to 21 hours.

I think this start date should be automatically set to the last time that harvesting is done.
@djtfmartin what do you think?

**Comment by djtfmartin** [comment]
i'd probably stick with havesting the last few months. As discussed the problem is there is no way to query by date added to group.

**Comment by sadeghim** [comment]
For now we can leave it as it is. For those images which were uploaded to flickr before this period and added recently to the groups being monitored, we can harvest them once in a (couple of) month.
