### ISSUE TITLE
Sensitive Data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#494]
SDS list maintenance

    All lists current
    All lists have an editor for the jurisdiction
    All lists are able to be automatically updated
    Pest SDS environment resolved

    Document a product roadmap for the SDS
        ALA to have formal responsibility for sensitive data processing
        agreement signed from jurisdictions with roles and responsibilities
        review and design security model
    SDS processing available in a data test – sandbox or stand alone
    full resolution records available for sensitive species
    full resolution records available for modelling

**Comment by ansell** [comment]
Bioplatforms Australia also have an SDS implementation, which reuses ALA BIE as the species lookup service:

https://github.com/BioplatformsAustralia/sslh/blob/master/sslh/handler.py#L45

Their species lists are CSV files in this directory:

https://github.com/BioplatformsAustralia/sslh/tree/master/sslh/data
