### ISSUE TITLE
fungimap data update

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#497]
To follow up:

from email 8/8/2019:

Thanks for getting in touch. I'm relatively new in the role of fungimap coordinator and my understanding is that yes, there is a significant of backlog of data that needs to be transferred to ALA. I'll speak to the relevant volunteers and our management committee to emphasise the importance of progressing this.

In the meantime, we are now encouraging contributors to make their observations through iNaturalist wherever possible - I've noticed research grade observations are being ported across already, presumably automatically/via an API?

Please let me know if there is anything else you need from us.

**Comment by nickdos** [comment]
Tom M (RBG) will send a list of records for us to delete - this should remove a batch of bad records that are in the ocean - see screenshot:

![Uploading image.png…]()

**Comment by nielsklazenga** [comment]
Completed
