### ISSUE TITLE
CSIRO Marine Data IPT

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#5]
Review http://ogc-act.csiro.au/ipt/ for data to load

**Comment by charvolant** [comment]
Updated for new collectory-plugin architecture and being tested

**Comment by charvolant** [comment]
Need to be able to mark IPT records as already present, so that we don't double-load from data resources that have already come from other systems.

**Comment by charvolant** [comment]
Enchancement in production. However, direct web services access needs an apikey that needs to be specifically checked in the controller code, as well as more general userInRole check. Adding apikey code to IptController.

**Comment by charvolant** [comment]
Pull request submitted for collectory-plugin

**Comment by charvolant** [comment]
Loaded data into http://collections.ala.org.au/public/show/dr2220 to http://collections.ala.org.au/public/show/dr2242

Checking on the period of regular schedule for updates.

**Comment by charvolant** [comment]
Scheduled to run every month using the "Monthly CSIRO Oceans and Atmosphere IPT Scan" Jenkins job.
