### ISSUE TITLE
No relationship between provided and processed establishmentMeans values

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#504]
Values for establishmentMeans are wildly different between the provided data in the MEL-AVH data set and what I get out of the Biocache.

This is what I get from a query on the table that is queried by my IPT:

```sql
SELECT establishment_means, count(*)
FROM avh_cache.occurrence
GROUP BY establishment_means;
```
establishment_means | count(*)
|---|---
|    | 4089243
| cultivated | 18033
| introduced | 74589
| managed | 47497
| native | 589495
| naturalised | 284
| uncertain | 58221

(`cultivated` is mapped to `managed` in the IPT)

And this is what I get from a query on the Biocache:

https://biocache.ala.org.au/occurrences/search?q=*%3A*&fq=data_resource_uid:%22dr376%22

Establishment means | Count
---|---
native | 586,007
cultivated | 17,713
not cultivated | 18
not cultivated; native | 12
Unknown | 2
not cultivated; not native | 1
Not supplied | 4,287,514

I expect the non-standard values in the facet results are hanging around because the provided value is now `null`, but what happened with the standard values that have been delivered, but can't be found back in the Biocache?

I also note that the indexed `establishment_means` field is still multi-valued, which I expect is why I can't get the field values through the web services:

```json
  {
    "name": "establishment_means",
    "dataType": "string",
    "indexed": true,
    "stored": true,
    "multivalue": true,
    "description": "Establishment means",
    "info": "http://rs.tdwg.org/dwc/terms/establishmentMeans",
    "dwcTerm": "establishmentMeans",
    "downloadName": "establishment_means",
    "classs": "Occurrence"
  }
```
Is there a reason for this? Darwin Core doesn't allow multiple values for `establishmentMeans`. It would be very helpful to me to be able to get establishmentMeans values through the web services (without having to send a separate request for each establishmentMeans term).

(Also note that `cultivated` and `natural_occurrence` fields are still indexed. These are old HISPID/ABCD fields that we haven't used for years.

**Comment by ansell** [comment]
As I mentioned on Slack, you needed to wait until this morning (Wednesday) before checking the latest dataset.

The values now in the ALA as of the reindex this morning are slightly different to the ones you quote above from yesterday, but are still not consistent with your original values. I will check the Darwin Core Archive that was loaded on Sunday/Monday to get more information about what was in the CSV file itself for the `establishmentMeans` field:

establishment_means | count
-- | --
native | 589785
cultivated | 18052
not cultivated | 18
not cultivated; native | 12
unknown | 2
not cultivated; not native | 1

I have opened a bug about the facet download button in the biocache interface being broken https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/315

Until that is fixed, you can use this URL to directly get the facet values as a downloaded CSV file:

`https://biocache-ws.ala.org.au/ws/occurrences/facets/download?q=*%3A*&fq=data_resource_uid%3A%22dr376%22%20AND%20data_resource_uid:%22dr376%22&facets=establishment_means&count=true&lookup=true`

The browser for the facet names is:

`https://biocache.ala.org.au/fields`

In this case, it appears that the ALA has, in the past, put both `cultivated` and `establishment_means` together with `establishmentMeans`:

`https://biocache.ala.org.au/fields?filter=establishmentMeans`

That will almost certainly create issues when trying to either think or construct queries using the term. There are unfortunately many cases where someone at the ALA has, in the past, pushed multiple ALA index fields into the same Darwin Core Term, possibly not understanding the consequences of doing so.

**Comment by ansell** [comment]
The values from the archive that was loaded a few days ago, `avh_cache-v1.8`, are:

establishment_means | count
-- | --
native | 589495
cultivated | 18033
introduced | 74589
managed | 47497
naturalised | 284
uncertain | 58221

788119 rows in the file contained a value for `establishmentMeans`, with the 6 unique values above as their contents. 4089243 records didn't have a value. 

That matches your numbers, so based on that, it is either a bug in biocache-store or biocache-service where there has been translation occurring for some reason.

**Comment by nielsklazenga** [comment]
Thanks for looking into this @ansell . Should I open an issue in  the other two repositories you mention?

**Comment by ansell** [comment]
I will track it down in biocache-store and open an issue there (and close this after referencing that issue)

**Comment by nielsklazenga** [comment]
Thanks @ansell. I read my emails in the wrong order, so at first missed the line where you said you had already done that.

**Comment by ansell** [comment]
The relevant code in biocache-store has a note from circa 2012 that references AVH. Can you look into this code and check whether it is relevant at this time:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/0398df452abd311a0463c6d4a4b4e8449bc93f6d/src/main/scala/au/org/ala/biocache/processor/MiscellaneousProcessor.scala#L93-L118

**Comment by nielsklazenga** [comment]
Yes, that made sense at the time, as we were delivering `establishmentMeans` as the old HISPID (also ABCD) terms `NaturalOccurrence` and `CultivatedOccurrence`. We don't do that anymore. Since the HISPID review in 2015 we only deliver Darwin Core terms (and some GGBN/ABCD terms for loans etc.), so mapping is no longer necessary.

**Comment by ansell** [comment]
Okay, tracking removing it at https://github.com/AtlasOfLivingAustralia/biocache-store/issues/339 , will reinvestigate this after that change is made and deployed to check if there is anything else that affects it.

**Comment by nielsklazenga** [comment]
I was bugged about this again today, so I looked into it again. While the weird, concatenated HISPID 3 values have disappeared from the facets, some of the standard values are not there. This is what was delivered last weekend:

value | count
-|-
(blank) | 4108630
cultivated | 17301
introduced | 74530
managed | 47135
native | 576749
uncertain | 57096

And this is what the facet field has:

value | count
-|-
native | 597,148
cultivated | 17,882
Not supplied | 4,286,263

I am not so much concerned about the slight difference in numbers, but about entire categories that are missing. The missing values are (sort of) standard terms (http://rs.gbif.org/vocabulary/gbif/establishment_means.xml), but they were not in HISPID 3, and the values that are there those that GBIF and HISPID 3 have in common. Seems that there is still some data mapping happening that we are not aware of.

**Comment by nielsklazenga** [comment]
Support ticket https://support.ehelp.edu.au/a/tickets/97308:

Good afternoon,

I was attempting to filter out introduced occurrences of Atriplex nummularia from a query yesterday, and noticed that 'Introduced' is not listed in the filter, despite it being recorded as the Establishment means, see https://avh.ala.org.au/occurrences/430c9f72-8c71-40f8-ae56-d401d945f57a.

I'm pretty sure there are other values for Establishment means that aren't listed in the filter too, but don't have examples to hand.

This is a really useful filter, so it would be great if it could be fixed up.

Thanks,
Alison

**Comment by nielsklazenga** [comment]
Appears to have been fixed in new infrastructure.
