### ISSUE TITLE
Naturemapr updates - new instances

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#509]
These new sites can be setup as new data sources if you are still doing it:
•	https://southern-highlands.naturemapr.org/
•	https://noosa.naturemapr.org/
•	https://albury-wodonga.naturemapr.org/
--------------------------------------------
Just checking to see if you've had any time to update your feed at the ALA end yet for sucking down NatureMapr data.

This is the new web method:
/api/Projects/{projectid}/SightingsUploadedSince/{day}/{month}/{year}

From here:

https://webapi.naturemapr.org

And authentication is now OAuth/JWT so you first call the authenticate method:
/api/Authors/Authenticate

That method returns you a token that you then inject as a bearer token in the HTTP header for when you call the SightingsUploadedSince method..

And you can substitute ProjectId for any of the projectids returned to you via the UpdatedSince method (which returns a list of projects):
/api/Projects/UpdatedSince/{day}/{month}/{year}

Let me know how you go and/or any issues!

**Comment by charvolant** [comment]
Updated Talend job to use new https://webapi.naturemapr.org API
Migrated load to AWS jenkins
Created or updated DRs for:

* https://collections.ala.org.au/public/show/dr14081
* https://collections.ala.org.au/public/show/dr702
* https://collections.ala.org.au/public/show/dr4690
* https://collections.ala.org.au/public/show/dr14080
* https://collections.ala.org.au/public/show/dr14082

Still to do Southern Highlands

**Comment by charvolant** [comment]
Waiting on metadata details for remaining instances

**Comment by charvolant** [comment]
Updated Budawang Coast Nature Map https://collections.ala.org.au/public/show/dr14021

**Comment by peggynewman** [comment]
Closing - we're about to take a different approach with NatureMapr using a single data resource so that we don't have to set up a new one for each area.
