### ISSUE TITLE
Delete MELU records from MEL-AVH data set

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#514]
The University of Melbourne is now delivering its own data, 
https://avh.ala.org.au/occurrences/search?q=*%3A*&qc=data_hub_uid%3Adh9&fq=data_resource_uid%3A%22dr13282%22,
so MELU records in the MEL-AVH data set are outdated duplicates. Could these records,
https://avh.ala.org.au/occurrences/search?q=*%3A*&qc=data_hub_uid%3Adh9&fq=data_resource_uid%3A%22dr376%22&fq=institution_code:MELU, please be deleted?

**Comment by ansell** [comment]
I was waiting on the MELU image loads, being tracked in #456 but I can remove the dr376 MELU records earlier if that is desired.

**Comment by nielsklazenga** [comment]
Thanks @ansell. Fine with me to wait for the images.

**Comment by ansell** [comment]
The load of MELU records and images are now complete. I will work on this as my next data task.

**Comment by ansell** [comment]
Deleted the following UUIDs from dr376:

[dr376-MELU-uuids.txt](https://github.com/AtlasOfLivingAustralia/data-management/files/4032819/dr376-MELU-uuids.txt)
