### ISSUE TITLE
Load data : OWAD Koala records

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#521]
Excel spreadsheet submitted to support@ala.org.au for OWAD Koala records.

- [x] Ask for data resource metadata
- [x] Map dataset to Darwin Core Terms
- [x] Create Data Resource in Collectory for `OWAD Environment detection dogs` https://collections.ala.org.au/dataResource/show/dr13823
- [x] Create Institution in Collectory for `OWAD Environment` `https://collections.ala.org.au/institution/show/in444`
- [x] Create Collection in Collectory for `OWAD Environment` `https://collections.ala.org.au/collection/show/co292`
- [x] Create Provider Map in Collectory for `OWAD` as the `institutionCode` and `collectionCode` to map to the relevant institution and collection `https://collections.ala.org.au/providerMap/show/153`
- [x] Create Darwin Core Archive
- [x] Wait for data resource metadata to be given
- [x] Upload Darwin Core Archive to Collectory
- [x] Load Darwin Core Archive to cassandra
```
aws-bstore-4b 2019-11-05 10:21:24,250 INFO : [DataLoader] - 1370, >> last key : dr13823|OWAD Environment-Phascolarctos cinereus-May-18-Queensland-Canungra, Scenic Rim LGA--28.002670-153.213764, UUID: , records per sec: 1000.0
aws-bstore-4b 2019-11-05 10:21:24,254 INFO : [DataLoader] - Finished DwCA loader. Records loaded into the system: 1374, records skipped: 0, new records: 1374
aws-bstore-4b 2019-11-05 10:21:24,468 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2019-11-05 10:21:24,562 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2019-11-05 10:21:24,562 INFO : [Loader] - Completed loading resource: dr13823. Completed in 2.477seconds (0.04128333 minutes)
```
- [x] Process occurrence records
- [x] Sample occurrence records
- [x] Wait for next reindex to occur
- [x] Verify that the records are as expected
```
1,374 results for Data resource: OWAD Environment detection dogs Koala records   
```
`https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr13823`
- [x] Reply and close the helpdesk ticket

See full details in ticket 34500 in helpdesk

**Comment by matilda2812** [comment]
I have spoken to Olivia- she would like this dataset directly uploaded to the ALA.

**Comment by ansell** [comment]
Responded to the helpdesk ticket and waiting for them to respond with any further queries.
