### ISSUE TITLE
iNaturalist records in ALA not restricted to research grade and needs ID

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/data-management#528]
"This data is provided via a Darwin Core archive exported from iNaturalist. All verifiable bservations (research grade and needs ID) are exported by iNaturalist." (https://collections.ala.org.au/public/show/dr1411)

https://biocache.ala.org.au/occurrences/fe4d0d75-16d1-44d7-8f3e-0f7f311230e1
is casual grade:
https://www.inaturalist.org/observations/1200228

I have not checked to see how many other ALA imports are neither research grade or needs ID.

**Comment by sadeghim** [comment]
I have investigated this issue and it's part of the non-existent record in the iNat export of verifiable records. 
It will be removed in the next run of the iNat sync job which is supposed to run weekly.
It has a bug that I'm fixing.
Will close the issue as soon as it gets fixed.

**Comment by Mesibov** [comment]
Thanks, @sadeghim. Of the 649186 records I looked at, 351591 are "iNaturalist research-grade observations" in the datasetName field, and the other 297595 are "iNaturalist observations". If all that ALA is accepting are "research grade" and "needs ID", why not record that info in datasetName as "iNaturalist needs-ID observations"?

**Comment by sadeghim** [comment]
No worries,
The synchronisation job is now in place and just completed for the first time and the record is gone. This will run every Sunday and cleanup all the removed records from Biocache.

Regarding the Data set names, this happened because of the old and new data set mixes. In the past, we only had research-grade records and now we have decided to include need_id ones as well.
I need to find a way to unify this field across the data resource.

**Comment by sadeghim** [comment]
Now that synchronisation job is running regularly, we shouldn't see any casual records which is older than a week. The job will delete records which are deleted or changed their attributes in a way that it doesn't meet our harvesting criteria before a week a go.

Closing this ticket now, @Mesibov please create an issue if you found an iNat record which shouldn't be on ALA.

**Comment by Mesibov** [comment]
@sadeghim "Closing this ticket now, @Mesibov please create an issue if you found an iNat record which shouldn't be on ALA."

That's a job for ALA. If you adopt my suggestion and assign incoming "research grade" records to datasetName "iNaturalist research-grade observations", and "needs ID" records to "iNaturalist needs-ID observations", then you can programmatically find incoming records which shouldn't be on ALA.
