### ISSUE TITLE
iNaturalist records in ALA do not give image URLs

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/data-management#531]
In a sample dataset of ca 50,000 iNaturalist Australia records, the only entries for associatedMedia are "original.XXX", where "XXX" is jpg, JPG, jpeg, png and so on.

The ALA version of these records does not give either the iNaturalist URL for the image or the ALA URL for the image.

Example:
https://www.inaturalist.org/observations/22197
image_url:
https://static.inaturalist.org/photos/39710/medium.jpg?1444335406

https://biocache.ala.org.au/occurrences/e62d0327-e59e-4565-8cb9-39fc09937faf
https://images.ala.org.au/image/details?imageId=23280710-a281-4909-81bd-186ad46d7601
associatedMedia:
original.jpg

Is there a reason for not including either of the image URLs in the download in associatedMedia?

**Comment by sadeghim** [comment]
iNaturalist images are uploaded in a dwca zip file and I think the way biocache-store loads them leaves the `associatedMedia` field empty.

@djtfmartin do you have any comment on this?

**Comment by djtfmartin** [comment]
Sounds like a data ingest bug. 

Alternatively we could be populating associatedMedia with URLs to image service. This would then work for data sources where the image (or sound file) isnt available via source URL.

**Comment by sadeghim** [comment]
@M-Nicholls can you discuss this with Bob.

**Comment by nickdos** [comment]
@peggynewman taking over this one.

**Comment by peggynewman** [comment]
Closing this - this is a broader problem for downloads and exports, not just iNaturalist. We'll track it in #58.
