### ISSUE TITLE
iNaturalist records in ALA with locations different from the originals in iNaturalist

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/data-management#533]
In a sample dataset of ca 50,000 iNaturalist Australia records, there are records in which verbatimLatitude and verbatimLongitude don't agree with the originals on iNaturalist. Many of these are for sensitive locations and have been generalised in ALA to the nearest 0.1 degree, which explains those differences.

Other cases are puzzling. For example,

https://www.inaturalist.org/observations/4797801

is an observation of the rock fern Cheilanthes sieberi from 2016. iNaturalist says the coordinates are "obscured" because the taxon is threatened, but only the subspecies pseudovellea is listed as threatened in NSW:

http://plantnet.rbgsyd.nsw.gov.au/cgi-bin/NSWfl.pl?page=nswfl&lvl=in&name=Cheilanthes~sieberi~subsp.+pseudovellea

The iNaturalist location is "-35.262374318 147.6182615149" with an accuracy of 6 m, and since this is an "obscured" location, the coordinates are for a random spot within a 0.2 x 0.2 degree rectangle around the true location (https://www.inaturalist.org/pages/geoprivacy).

The ALA location

https://biocache.ala.org.au/occurrences/0090e8fd-de6e-460a-bfd1-380cc03d3841

is "-35.2833075268 147.6056407741" with a coordinateUncertaintyInMeters of 6.

iNaturalist gives a verbal description of the location as "Wagga Wagga - Pt B, AU-NS, AU", while ALA gives "755 Keajura Road, , NSW, AU" [The missing placename is probably Tarcutta.]

Where did ALA get its verbal location and coordinates from?

**Comment by sadeghim** [comment]
The record is deleted from ALA during the synchronisation process. And I don't know how it had ended up in ALA at the first place.

I am doing another ingestion of all the records to get the eligible missing ones. After that there shouldn't be any discrepancies between ALA  and iNat other than those that are related to local processing rules (Australian taxa and sensitive records generlisations).

**Comment by ansell** [comment]
The example record above currently has the same coordinates in the ALA as iNaturalist. Can this issue be closed?

**Comment by Mesibov** [comment]
@ansell I haven't re-checked the other discordant records I found last October, nor have I done a thorough audit of ALA's current iNaturalist holdings vs the originals. Something peculiar happened in the sample record and my question "Where did ALA get its verbal location and coordinates from?" hasn't been answered. You're welcome to close this issue based on the change in the one sample record, but a bigger issue is lurking here which has not been addressed.

**Comment by sadeghim** [comment]
@Mesibov We only fetch the iNat data using their API and if it's changed we will reflect it on ALA. Most of the problematic records are `need_id` records. And they will get updated later and we'll update on ALAin a matter of a day or two.

The information that is shown on ALA is whatever comes from their API.

**Comment by nickdos** [comment]
INat is showing the same locality as ALA now:

![image](https://user-images.githubusercontent.com/532845/77984443-48473380-735d-11ea-89ee-e458c8172608.png)
