### ISSUE TITLE
Data load : Queensland Museum fix

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#543]
Investigate the QM job (**QM data update** on ala-dury) to get it running again as is. We will investigate migrating and rewriting the job only after further discussions on the tech options available to them.

**Comment by sadeghim** [comment]
QM data is loaded. Need to load QM sponge maps. Then verify the records.

**Comment by sadeghim** [comment]
QM is loaded and scheduled to be running on a monthly basis.
Spongemaps job is disabled as there is no new data updates from the data provider.
