### ISSUE TITLE
iNaturalist "rights" fields does not match original iNat record

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#547]
I was looking at the `licence ` field in images.ala.org.au and noticed a large number of iNat records with no "Licence" specified. See "License" facet for https://images.ala.org.au/?fq=recognisedLicence:unrecognised_licence&fq=dataResourceUid:dr1411.

- [ ] There are actually lots of records with both copyright and variants of CC in the iNat records, so the image-service needs to be be processed or updated in some way. I also note that iNat has separate license fields for the record data, image and sound files, so code should be checking the appropriate one.

Checking a random record shows 3 different versions of License or rights depending on which system you are looking at.

https://images.ala.org.au/image/1e532eb6-0bb1-4b78-94ea-7c7052cb48af
https://biocache.ala.org.au/occurrences/6e189c03-3c57-4d8d-a85b-2213849ffeaf
https://www.inaturalist.org/observations/36853433

The iNat record has `Observation © Em...oto · all rights reserved`, the biocache record has `CC-BY-NC-Int` (which is clearly wrong and appears to be a default value obtained from the Collectory) and image-service has empty `rights` and `license` fields. Edit: some records have https://images.ala.org.au/?q=&fq=recognisedLicence:ALL-RIGHTS-RESERVED in image-service, so maybe that is the way to indicate these © records.

I'm guessing the problem is that `copyright` is being interpreted as not being any of the known CC licences and therefore left empty. The Collectory default is then being inserted (incorrectly).

- [ ] I'm thinking that we might need to put "Copyright" into the `rights` field. The code that inserts the `license` field should check for this value and then NOT insert the default license from the Collectory.

**Comment by nickdos** [comment]
@peggynewman FYI...

**Comment by peggynewman** [comment]
Still 400K images with unrecognised licence: 
https://images.ala.org.au/?fq=recognisedLicence:unrecognised_licence&fq=dataResourceUid:dr1411
This still needs to be addressed.

**Comment by peggynewman** [comment]
Closing this.
