### ISSUE TITLE
Black/missing/text-only images on some records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#548]
Example: https://biocache.ala.org.au/occurrences/41b30193-7d66-4b78-83f6-3149d9bd8312

Clicking "View image details" on the black image shows details for a completely different occurrence.

Almost all images here are either entirely black, or text with a black bar at the bottom of the image: https://biocache.ala.org.au/occurrences/search?q=collector_text%3A%22annable%22&fq=data_resource_uid%3A%22dr364%22#tab_recordImages

Reported in helpdesk ticket 59625.

**Comment by ansell** [comment]
This may need to be handled by @djtfmartin as it appears to be caused by an issue in either biocache-store or image-service with HTTP redirects not being followed. Not sure where to open a follow-up issue, but the following is one place that the redirects may have failed to be followed, which could explain why the image appears as it does:

https://github.com/AtlasOfLivingAustralia/image-service/blob/d3bb08d0e038b6d07eb360cc6939d4ef72c305aa/grails-app/services/au/org/ala/images/ImageService.groovy#L124-L125

**Comment by ansell** [comment]
The NGINX version there, `1.17.4` indicates that it was done late last year which agrees with its timestamp:

```
# ls -lah /data/image-service/store/4/2/d/1/d70c7d06-daf4-44c9-830a-78627fca1d24/original 
-rw-r--r-- 1 image-service image-service 169 Oct 22 00:17 /data/image-service/store/4/2/d/1/d70c7d06-daf4-44c9-830a-78627fca1d24/original
```

**Comment by djtfmartin** [comment]
I've been looking at this and found a few issues going on with dr364 images.

The biocache record referenced in Tim's original post has been deleted (presume by a jenkins job), but it is here:

https://biocache.ala.org.au/occurrences/b83de47a-f6ec-413f-aeef-26d1adadb471


I believe redirects are followed by image-service as long as the protocol remains the same. HttpURLConnections by default have setFollowRedirects = true according to javadoc.

The problematic records seem to be coming from BioCollect which for some reason have `original_filename` values with http://images.ala.org.au as opposed to https.

Still looking at it....

**Comment by timhicks-ala** [comment]
Additionally raised in helpdesk ticket 95508 with further examples:

Gallery showing multiple black images: https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:8b443d18-845f-4459-bb2b-90ac507b3dde#gallery
Example affected record. Image metadata is there but no actual image data: https://biocache.ala.org.au/occurrences/c3bd4bbc-cd5d-4156-8c83-423df1efe476

Example record where the image appears black but is actually all text on a transparent background: https://biocache.ala.org.au/occurrences/4b7e3503-c7da-4968-aa49-773910b08fe2

@djtfmartin should I raise a separate issue for the black text images vs missing images that display as black?

**Comment by djtfmartin** [comment]
Apologies @timhicks-ala  - i missed this somehow. I think we can leave as one issue.
