### ISSUE TITLE
Wrong image associated to multiple sightings

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#550]
The occurrences below have an image from another occurrence which shouldn't be associated with them:
https://biocache.ala.org.au/occurrences/a8f4c843-22ea-4d1c-9a0b-3214cd2cd0f1
https://images.ala.org.au/image/details?imageId=d70c7d06-daf4-44c9-830a-78627fca1d24

And this is the correct occurrence:
https://biocache.ala.org.au/occurrences/6da57918-0ff1-4a01-a83f-dab7a5444750

**Comment by peggynewman** [comment]
This appears to be resolved.
