### ISSUE TITLE
Flickr images are not ingested properly

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#553]
Looking at https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr360&fq=alau_user_id%3A%22160417453%40n04%22#tab_recordImages 
you can see there are many blank images.
Seems there should be an issue with the harvester or biocache-store.

**Comment by peggynewman** [comment]
Closing this. Track this problem in #471.
