### ISSUE TITLE
Data load : CSIRO Marine Invertebrates Image Collection (MIIC)

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#557]
- [ ] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

IPT location:  http://ogc-act.csiro.au/ipt/resource.do?r=csiro_miic
Data Resource: https://collections.ala.org.au/public/showDataResource/dr9919 

From Dave:
Updated with new images of specimens
Be great to figure what needs to refreshed and how to trigger any updates.
You could use the updated date on my IPT  but that also refers to  any changes in the EML which does not seem to get posted very well into ALA. The whole set has been updated and needs a compete reload

- [ ] Update DR metadata, include custodian and link to original resource
- [ ] Delete original data
- [ ] Reload DwCA

Catalogue Numbers have been changed so new UUIDs will be generated.
_____________
Standard load processing:
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
Will be part of the OBIS load. Closing.

**Comment by sadeghim** [comment]
Related to https://github.com/AtlasOfLivingAustralia/data-management/issues/922
