### ISSUE TITLE
Load data : UNSW AVH

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#560]
For the moment check the data in the sandbox so we can get back to the provider with the changes they need to make. See email.

https://sandbox.ala.org.au/ala-hub/occurrences/search?q=data_resource_uid%3Adrt20943#tab_recordsView

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [x] Ask data provider for metadata, including:
* Data resource name
* Description
* License : prefer Creative Commons Attribution https://creativecommons.org/licenses/by/4.0/
* Citation : Statement to be used by those downloading and using these records
* Contact : Email and/or phone number
* Website : (Optional)
- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [x] Create new data resource using https://collections.ala.org.au/admin
- [x] Upload the dataset to collections.ala.org.au
- [x] [Optional] If the dataset is destined to be included in a data hub, identify the data hub and add the new data resource id to its list https://collections.ala.org.au/dataHub/list
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [x] Ask the data provider to review the new records using the same URL

**Comment by ansell** [comment]
Are these records currently bundled in one of the other AVH datasets, such as MEL_AVH?

**Comment by ansell** [comment]
The `data_hub_uid` for this dataset will be `dh9` (AVH)

**Comment by nielsklazenga** [comment]
@ansell, UNSW is a new provider; the data is not in any other data set.

**Comment by peggynewman** [comment]
They've uploaded to sandbox, Mahmoud is having a look at the data there; it has lots of problems.

**Comment by sadeghim** [comment]
`aws-bstore-4b 2020-02-24 10:43:34,042 INFO : [DataLoader] - There are 21041 records in the file. The number of NEW records: 0`

**Comment by sadeghim** [comment]
The DR is : https://collections.ala.org.au/public/show/dr14787

**Comment by sadeghim** [comment]
It shows properly on ala and avh: https://avh.ala.org.au/occurrences/search?q=data_resource_uid:dr14787

**Comment by ansell** [comment]
Reopening, needs collection and institution code mapping.

**Comment by ansell** [comment]
The collection and insititution code mapping issue is similar to #561 (which I forgot/wasn't-aware-of when uploading the MELU AVH records)

**Comment by peggynewman** [comment]
Collection is https://collections.ala.org.au/public/show/co66

**Comment by ansell** [comment]
That would make the institution: https://collections.ala.org.au/public/show/in63

**Comment by peggynewman** [comment]
Trying to map the [DR](https://collections.ala.org.au/dataResource/show/dr14787) back to the right collection

I've changed the DR Record Consumers from
https://collections.ala.org.au/collection/show/co298 (empty, no metadata)
to 
https://collections.ala.org.au/collection/show/co66 (good metadata & contact details)

In the data, the collectionCode='UNSW' and institutionCode='UNSW'.
There's no providerMap entry for this yet.

Looks similar to the problem with the Uni of Melbourne Herbarium. For that 
collectionCode='MELU' and institutionCode='MELU'
but it does have a providerMap

I worked out how to see all the providerMaps
https://collections.ala.org.au/providerMap/list?max=200&order=asc

To get the records to appear against co66, the providerMap should be created. This is likely the same issue as the Uni Melb Herbarium, and NZAVH. Need to look at the issue to make sure that database integrity remains intact for these; see linked issues
https://github.com/AtlasOfLivingAustralia/data-management/issues/561
https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/550

**Comment by nielsklazenga** [comment]
I created the provider map and re-uploaded the data. All good now. I think this can be closed after the re-index has taken place.
