### ISSUE TITLE
Fix collection association for MELU AVH records

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#561]
The recently moved MELU AVH records have not associated with their collection for some reason:

https://avh.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr13282%22

**Comment by peggynewman** [comment]
I have questions about this. Should be linked to CO64? 
And if so, does that happen at a record level or data resource level? 

Looking at this example record: https://biocache.ala.org.au/occurrences/ce53afca-c098-4555-af9e-bc6e85014d90

Collection code field = "The University of Melbourne"
what should this be set to?

Institution code field = Supplied institution code "MELU"
There is a Collectory institution:  University of Melbourne
But this code actually refers to the Index Herbariorum code for the Uni Melb Herbarium:
http://sweetgum.nybg.org/science/ih/herbarium-list/?NamOrganisationAcronym=MELU

Do we use a particular field for Index Herbariorum codes?

**Comment by ansell** [comment]
We need to go into the collectory and setup mappings for these particular codes in the `institutionCode` and `collectionCode` fields.

There is no documentation for it and I have to hope I am doing it the right way. There is no search functionality for it. I also can't figure out if there is anyway to restrict the mappings to a single data resource or whether they are always global mappings (ugh) and we need to hope they aren't matching anything unintended on other data resources.

The codes need to be setup in:

https://collections.ala.org.au/providerCode/list

Then they need to be mapped in:

https://collections.ala.org.au/providerMap/list

Have been on emergency fixes since this came up, but the same issue came up yesterday for UNSW AVH dataset in #560 so I mentioned it there.

We also need to fix the NZVH records that have the same issue.

**Comment by peggynewman** [comment]
Oh. Nuts. Ok. Sounds like something that needs to be documented somewhere and will be a big deal with any potential Collectory migration exercises. I'll try to rope in @nielsklazenga for some help with this.

**Comment by nielsklazenga** [comment]
You already did that.

**Comment by peggynewman** [comment]
Can't get you on Slack or email. Can you get in touch?

**Comment by ansell** [comment]
Closing this as "Won't Fix" as it broke the collections.ala.org.au application when I tried to work on it. The tasks for a developer to work through documenting it so that it can be safely done without breaking the database, or even just allowing search on the provider maps so that we could possibly verify what is present in the database have been marked as "Won't Fix" in the collectory issue tracker for the planning stage for the future switch to using GBIF registry instead of the collectory. See the list of issues I have previously opened on the collectory-plugin issue tracker for some references if we are still able to maintain the collectory https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/created_by/ansell
