### ISSUE TITLE
iNaturalist license is incorrectly being set to data resource default

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#564]
All iNaturalist records in ALA (791,907) are deemed to have license  CC-BY-NC-Int which can't possibly be correct.

iNaturalist provides the license information in both the API and the extract. This value provided for each record should be applied, not the default value in the data resource.

Possibly should be worked in with this other iNaturalist license issue:
https://github.com/AtlasOfLivingAustralia/data-management/issues/556

**Comment by ansell** [comment]
The matching biocache-store issue for this is https://github.com/AtlasOfLivingAustralia/biocache-store/issues/361

**Comment by charvolant** [comment]
A question on how we wish to handle non-standard licences. The the moment, the modified code is, lookup the licence string against a list of possible licence regexes in licences.txt. If we can't find it, then use the datastore default licence.

If there is a licence but it's "Licenced under the terms of the Floobyblah Trust licence" then we won't match it but I don't think we should default it. We can either:

- Pass it through as-is, which will be a pain for people attempting to use the data
- Pass it through as-is but include a quality flag of some sort
- Map it onto something like 'Custom' so that people can then look at the original, but it can be easily filtered away.

**Comment by peggynewman** [comment]
(3) is the best option in my mind, to map it to Custom licence as a catch all bucket.
(1) is messy, and will be difficult to filter as you say
(2) there is upcoming work on the QA and I don't think we should add anything to that right now.

**Comment by peggynewman** [comment]
There's some feedback from an iNaturalist user that there's an All Rights Reserved record coming across:
this observation that appears to have all rights reserved has made it over to ALA:
iNat record: https://www.inaturalist.org/observations/47090486 1
ALA record: https://biocache.ala.org.au/occurrences/56a8fdc2-d9a7-4434-9c7a-153bbe822799
It seems to still have the old default licence on it, so maybe not all records have been updated with the latest release to biocache-store. If it was updated later to all rights reserved, then

**Comment by charvolant** [comment]
This doesn't correspond to any of the 'allowed' licences in biocache-store, because it doesn't have a version. It should become `CC-BY-NC (Int) 4.0` if processed from an inline licence. It looks like it's being filled out from the collectory defaults, since there's no supplied licence.

**Comment by peggynewman** [comment]
I'd like to remove the Collectory default value, given that there shouldn't be one for iNaturalist and the field is populated for every record. The original query to load records shouldn't even pull the record though, so maybe it did change.

The sync job checks for licence ... actually in Jenkins it checks for "icense" so maybe that's where the problem is.... 

`https://api.inaturalist.org/v1/observations?per_page=200&place_id=6744&order=asc&order_by=id&updated_since=2000-01-01T00%3A00%3A00%2B10%3A00&verifiable=true&icense=cc-by%2Ccc-by-nc%2Ccc-by-nd%2Ccc-by-sa%2Ccc-by-nc-nd%2Ccc-by-nc-sa%2Ccc0&only_id=true&id_above=46922682`

@patkyn could you have a look at the iNat sync job for this?

**Comment by patkyn** [comment]
The inaturalist weekly and daily sync job is now updated with the above typo fix. After running inaturalist weekly sync job, it ran Delete Records which removed 160,800 records from biocache that doesn't have the licenses cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa, cc0 in inaturalist

**Comment by peggynewman** [comment]
Final QA - now a variety of licenses on iNat records
![image](https://user-images.githubusercontent.com/1271932/92436087-2c3a9e80-f1e7-11ea-818d-04d495c8e45a.png)
