### ISSUE TITLE
Remove obsolete Collectory entries

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#573]
The list contains a bunch of data providers and data resources created by BioCollect & MERIT. It excludes:

-	All druids connected to BioCollect/MERIT projects where harvest is set to true
-	Any projects with record count != 0 
-	Any projects that have a folder in /mnt/data/biocollect/upload/biocollect (only 1 after other filters applied)

**Comment by ansell** [comment]
Need the list before working on this, so putting into Waiting until then.

**Comment by ansell** [comment]
[issue-573-lists.zip](https://github.com/AtlasOfLivingAustralia/data-management/files/4612417/issue-573-lists.zip)

**Comment by ansell** [comment]
Analysing those lists shows 2067 data providers and 5227 data resources. No way of doing that many using the "delete" button in the collectory web interface, as was originally recommended to me, so it will require a script.

**Comment by ansell** [comment]
HTTP DELETE verb on these paths should work unless that functionality is broken currently:

https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/master/grails-app/conf/CollectoryUrlMappings.groovy#L66-L71

**Comment by ansell** [comment]
Experimented for too long trying to figure out whether apikeys are enabled (looks like they are) and how to possibly specify the apikey to use for the delete method:

https://github.com/AtlasOfLivingAustralia/collectory-plugin/blob/d8177b1a85833e60f2f9141dcf945be319be113e/grails-app/controllers/au/org/ala/collectory/DataController.groovy#L479-L502

Putting this into waiting until someone familiar with how to do it gets back to me about it.

**Comment by ansell** [comment]
Testing on `nectar-collections-test`. The pattern used for deleting `dataResource`'s didn't work for `dataProvider`'s. All of the attempts to delete using that pattern for `dataProvider` returned HTTP 500, indicating that the server didn't like it for some reason, but there was nothing in the log files to indicate any specific errors.

```
==> /var/log/nginx/access.log <==
[REDACTED] - - [12/May/2020:16:49:44 +1000] "GET /dataResource/list HTTP/1.1" 200 126733 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0" "-" request_time=0.096 upstream_response_time=0.096 upstream_connect_time=0.000 upstream_header_time=0.088 upstream_cache_status=-
[REDACTED] - - [12/May/2020:16:49:49 +1000] "POST /dataProvider/index HTTP/1.1" 500 65870 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0" "-" request_time=0.183 upstream_response_time=0.112 upstream_connect_time=0.004 upstream_header_time=0.112 upstream_cache_status=-
```

**Comment by ansell** [comment]
AFAICT the data provider id's need to be manually dumped from the database to make the `POST /dataProvider/index` method work. It isn't clear from the code why the `dr` numbers work for it (in addition to the `id` values), but for data providers, it seems the `id` values, which are not easily accessible using the REST services, are required.

Query to dump the IDs that I will use is:

```
SELECT id, uid, name FROM data_provider INTO OUTFILE '/var/lib/mysql-files/data_providers.csv' FIELDS ENCLOSED BY '"' TERMINATED BY ',' ESCAPED BY '"' LINES TERMINATED BY '\n';
```

Then will map that list against the `dp` numbers provided in the spreadsheet and use the resulting id list as the deletions.

**Comment by ansell** [comment]
Will also switch to deleting data resources by id to ensure if they are recreated in the meantime, they won't be deleted again by my script (if they are recreated unnecessarily, there is another issue to fix before deleting them again)

```
SELECT id, uid, name FROM data_resource INTO OUTFILE '/var/lib/mysql-files/data_resources.csv' FIELDS ENCLOSED BY '"' TERMINATED BY ',' ESCAPED BY '"' LINES TERMINATED BY '\n';
```
