### ISSUE TITLE
Remove data : Fossil data resources

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#589]
Helpdesk ticket 82387 - request to remove data from multiple data resources:
https://collections.ala.org.au/public/show/dr2290
https://collections.ala.org.au/public/show/dr2289
https://collections.ala.org.au/public/show/dr2342

**Comment by peggynewman** [comment]
This task should delete 1508 records in the collection only. Those data resources contain other data and shouldn't be removed. For example the Fossil Birds (DR2290) data resource contains data that goes into 6 other collections.

**Comment by peggynewman** [comment]
Removed 1507 records in co241 by query instituionCode:SAMA and collectionCode:Palaeontology
