### ISSUE TITLE
Data issue: previous determination field not populated

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-management#590]
Feedback from a user - https://support.ehelp.edu.au/a/tickets/37012

> I do have one suggestion, I maintain some vegetation databases and in correcting species naming in them often consult AVH/ALA.  The data for a collection does not include previous determinations and if that could be added it would be very helpful.  By co-incidence I was talking to another consultant earlier this evening and she agreed that she would also find it helpful.

Looking at the DwC spec, I think he means the field `previousIdentifications`: http://rs.tdwg.org/dwc/terms/previousIdentifications. 

Is there a mapping problem or is data simply not being provided by the collections?

**Comment by nielsklazenga** [comment]
Previous identifications do show up in Biocache/AVH when they are provided, see for example https://avh.ala.org.au/occurrences/80930a23-91ee-41aa-ba39-c8e27ecf72c8. To my knowledge, the National Herbarium of Victoria (MEL) is the only herbarium that delivers this term. The data is also provided in the Identification History extension, which is our preferred way of delivering it, but this is not supported by ALA yet.

It will be harder to deliver dwc:previousIdentifications when we start publishing data directly from our collections management system, but, now that I have seen a use case, I will go the extra mile.

**Comment by nickdos** [comment]
Field is searchable too https://avh.ala.org.au/occurrences/search?q=previous_identifications%3A*
