### ISSUE TITLE
Notification from wordpress submissions

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#60]
See if we can get workpress to provide a notification when a new dataset comes in.

**Comment by djtfmartin** [comment]
Have you seen alerts.ala.org.au ?

its already doing this

**Comment by charvolant** [comment]
Replaced with direct contact to data management email. Stuff in the old wordpress entries page will still be processed but the data upload page on the ALA now just provides templates and refers to the email address. This is all for the best, since there's usually a bit of to and fro before loading the data. 

The major advantage the submission page was that it kick-started the metadata process with information about titles, contacts, licensing etc.
