### ISSUE TITLE
Investigate missing naturemapr records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#608]
Reported in helpdesk ticket 91347

This record from 2016, an example given by the user: https://atlasoflife.naturemapr.org/Sightings/4185937
Does not appear in the ALA: https://biocache.ala.org.au/occurrences/search?q=qid:1598233412461 (the one result for this catalog number is from a different dataset)

This record from 2020: https://atlasoflife.naturemapr.org/Sightings/4265830
Does appear in the ALA: https://biocache.ala.org.au/occurrences/c2e23e8a-80fc-401b-8e3f-167eb7e805c2

Initial suspicion is that there's a hard-coded date somewhere in the naturemapr import process that may be causing some records to be missed.

**Comment by peggynewman** [comment]
NatureMapr feed is broken and new feed is on the way. Closing.
