### ISSUE TITLE
Load data : Butterflies Australia API

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#611]
- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

[Butterflies - API  Guide.pdf](https://github.com/AtlasOfLivingAustralia/data-management/files/5186096/Butterflies.-.API.Guide.pdf)

- [x] Ask data provider for metadata, including:
* Data resource name
* Description
* License : prefer Creative Commons Attribution https://creativecommons.org/licenses/by/4.0/
* Citation : Statement to be used by those downloading and using these records
* Contact : Email and/or phone number
* Website : (Optional)
- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [x] Create new data resource using https://collections.ala.org.au/admin
- [x] Upload the dataset to collections.ala.org.au
- [ ] [Optional] If the dataset is destined to be included in a data hub, identify the data hub and add the new data resource id to its list https://collections.ala.org.au/dataHub/list
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
I've emailed the tech lead on this but haven't heard back.

**Comment by patkyn** [comment]
After loading, there are 7607 records from this https://www.butterflies.org.au/external/rest/v1/sighting/list

Few issues:
1) Video file is not playable. https://images.ala.org.au/?fq=dataResourceUid%3Adr16457&fq=fileType:video
For this occurrence: https://biocache.ala.org.au/occurrences/19ffb0cb-f345-4d80-b1d8-85197b5ba3bb
Although, the video link seems ok. https://www.butterflies.org.au/external/home/attachment/14003/get

2) There are duplicate survey data with same eventId and scientificName
![image](https://user-images.githubusercontent.com/1606595/97832044-ea7d2e80-1d25-11eb-8ba1-1140bfe2f2e5.png)

![image](https://user-images.githubusercontent.com/1606595/97832070-01bc1c00-1d26-11eb-9e83-f1bfbf0e2e5d.png)

3) There are also same survey with different event ids
![image](https://user-images.githubusercontent.com/1606595/97832096-18627300-1d26-11eb-87cc-a1e864356409.png)

![Uploading image.png…]()

**Comment by peggynewman** [comment]
Left to do: set up a schedule in Jenkins weekly

**Comment by patkyn** [comment]
Setup jenkins job to run every month

Currently, 7606 records for dr16457

Latest run:
aws-bstore-1b 2021-04-28 15:48:42,490 INFO : [DataLoader] - Finished DwCA loader. Records loaded into the system: 13044, records skipped: 0, new records: 5307
aws-bstore-1b 2021-04-28 15:48:42,686 INFO : [DataLoader] - Registry response code: 200
aws-bstore-1b 2021-04-28 15:48:43,230 INFO : [DataLoader] - Registry response code: 200
aws-bstore-1b 2021-04-28 15:48:43,230 INFO : [Loader] - Completed loading resource: dr16457. Completed in 3162.149seconds (52.702484 minutes)
Finished: SUCCESS

**Comment by patkyn** [comment]
There are 12,910 records after indexing.
