### ISSUE TITLE
Update NSW Conservation & Sensitive Lists

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#612]
List: https://lists.ala.org.au/speciesListItem/list/dr650
Link to data: https://www.environment.nsw.gov.au/threatenedspeciesapp/

**Comment by peggynewman** [comment]
Related support ticket: https://support.ehelp.edu.au/a/tickets/93666
Pterostylis chaetophora is missing from the list

**Comment by charvolant** [comment]
Downloaded data via web page. There are a number of odd entries that include a locality. Looking for a method of downloading that contains richer classification data and separates species and locality.

**Comment by charvolant** [comment]
Threatened speices data is available from the OEH Threatended Biodiversity Web Service https://www.environment.nsw.gov.au/-/media/OEH/Corporate-Site/Documents/BioNet/bionet-threatened-biodiversity-web-service-data-standard-200170.pdf This is accessible via odata v4 or https://data.bionet.nsw.gov.au/biosvcapp/odata/ThreatenedBiodiversity_Species

**Comment by peggynewman** [comment]
Update: https://data.bionet.nsw.gov.au/biosvcapp/odata/SpeciesNames

**Comment by peggynewman** [comment]
Downloaded from Bionet, and loaded temp lists into the lists tool for comparison. Sent to BIonet for review.

**Comment by peggynewman** [comment]
Completed quite a while ago
