### ISSUE TITLE
Data load : BDBSA refresh + observer data correction

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#615]
Data has been uploaded to FTP site as usual.

Once the dataset has been loaded, corrections will need to be made to the Observer field. See helpdesk ticket 92554.

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [x] Upload the dataset to collections.ala.org.au
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
SAfauna - There are 1606318 records in the file. The number of NEW records: 103138
Saflora - There are 1881812 records in the file. The number of NEW records: 39976
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [x] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
The SA Fauna data load contains some sensitive information. Straight after it's loaded, but before the index runs, the file SAFauna_sensitive_fix.csv (see uploads server) should be loaded to overwrite the sensitive information.

**Comment by charvolant** [comment]
Latest load has Kangaroo Aerial Survey recordedBy update and Australian Sealion Population Survey entries removed.

Index shows: SAfauna dr365 at 1,610,209 records, SAflora dr 366 at 1,883,328 records. These are both larger than what is reported by the load.

**Comment by charvolant** [comment]
Number of processed records for dr365 is 1606317
