### ISSUE TITLE
Images: sound files not playable in biocache

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#618]
Re ANWC support ticket https://support.ehelp.edu.au/a/tickets/93878

Some sound files are not playable. 

not working - 404 returned
https://biocache.ala.org.au/occurrences/46380eca-e06f-46a7-a2c8-3fc41a6163e0
https://images.ala.org.au/image/proxyImage?imageId=fdeed073-4522-4c7b-85ab-392a2a987f0e

working example
https://biocache.ala.org.au/occurrences/ea0dd68d-85f7-41fa-aeb6-830e44cb9ef1
https://images.ala.org.au/image/proxyImage?imageId=7d65a1cd-a23b-4924-9293-2745c56b21d3

**Comment by nickdos** [comment]
https://images.ala.org.au/image/7d65a1cd-a23b-4924-9293-2745c56b21d3 works from image-service

**Comment by ansell** [comment]
`https://images.ala.org.au/image/fdeed073-4522-4c7b-85ab-392a2a987f0e` is failing for me

**Comment by nickdos** [comment]
Yes, media file itself is 404: https://images.ala.org.au/store/e/0/f/7/fdeed073-4522-4c7b-85ab-392a2a987f0e/original
