### ISSUE TITLE
Data load : QVMAG

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#620]
- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

New file is on the upload server: ala-upload-20201006.csv
DR is https://collections.ala.org.au/public/showDataResource/dr345

* New person compiling data - check unique keys match and generally DwC terms are ok
* DR currently has 90,738 records
* Note record counts per file . 
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/20238/
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
aws-bstore-4b 2020-10-21 10:04:24,094 INFO : [DataLoader] - There are 5857 records in the file. The number of NEW records: 5856
aws-bstore-4b 2020-10-21 10:04:24,094 INFO : [DataLoader] - Load finished for ala-upload-20201020.csv
aws-bstore-4b 2020-10-21 10:04:24,223 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2020-10-21 10:04:24,223 INFO : [Loader] - Completed loading resource: dr345. Completed in 15.584seconds (0.25973332 minutes)
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr345
- [ ] Ask the data provider to review the new records using the same URL

**Comment by ansell** [comment]
New data file uploaded overnight that fixed a single duplicate catalog number in the previous file. It now contains 5856 unique keys. Will upload it today.

**Comment by ansell** [comment]
Biocache strangely reported 5857 records, but it did report the expected number of new records, 5856. Moving this to Waiting and will check it again after the overnight reindex completes.

**Comment by peggynewman** [comment]
Now 96,591 records. Done.
