### ISSUE TITLE
Remove georeference data from MV record

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#621]
https://support.ehelp.edu.au/a/tickets/94691

"We’ve updated the locality information for NMV K 2278:
 
https://biocache.ala.org.au/occurrences/a44127e1-ba7d-4f04-8e2e-3972e0b2a323
 
Please could you remove the georeference data (latitude, longitude, geodetic datum) from the record in the Atlas – the fields will be blank in our next export but will therefore not overwrite the existing data."

**Comment by sadeghim** [comment]
@timhicks-ala 
The new pipeline system, doesn't accumulate the information for records like biocache was doing in the past.
Every load is a fresh load and it will not keep information from the past for records if there is an updated version of them in the new delivery.
So, as you can see in the record detail page: [here](https://biocache.ala.org.au/occurrences/a44127e1-ba7d-4f04-8e2e-3972e0b2a323) the mentioned fields are not present anymore.
