### ISSUE TITLE
Data load : SAMA data update

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#633]
From helpdesk ticket: https://support.ehelp.edu.au/a/tickets/96981

Update of South Australian Museum datasets:

Current/SAMA-DWC-CSV-Arachnology-2020-11-30.csv
Current/SAMA-DWC-CSV-Entomology-2020-12-1.csv
Current/SAMA-DWC-CSV-Herpetology-2020-12-2.csv
Current/SAMA-DWC-CSV-Ichthyology-2020-11-29.csv
Current/SAMA-DWC-CSV-Mammalogy-2020-11-30.csv
Current/SAMA-DWC-CSV-MarineInvertebrates-2020-12-2.csv
Current/SAMA-DWC-CSV-Ornithology-2020-12-2.csv

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [x] Upload the dataset to collections.ala.org.au
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [x] Ask the data provider to review the new records using the same URL

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 17:17:19,570 INFO : [DataLoader] - There are 60930 records in the file. The number of NEW records: 297
aws-bstore-4b 2021-01-27 17:17:19,570 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Ornithology-2020-12-2.csv
aws-bstore-4b 2021-01-27 17:17:19,736 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 17:17:19,736 INFO : [Loader] - Completed loading resource: dr346. Completed in 138.606seconds (2.3101 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
60,678 results for Collection: South Australian Museum Ornithology Collection

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 17:44:39,251 INFO : [DataLoader] - There are 76518 records in the file. The number of NEW records: 63
aws-bstore-4b 2021-01-27 17:44:39,251 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Herpetology-2020-12-2.csv
aws-bstore-4b 2021-01-27 17:44:39,396 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 17:44:39,396 INFO : [Loader] - Completed loading resource: dr346. Completed in 163.145seconds (2.7190833 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 17:56:54,202 INFO : [DataLoader] - There are 56637 records in the file. The number of NEW records: 1947
aws-bstore-4b 2021-01-27 17:56:54,202 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-MarineInvertebrates-2020-12-2.csv
aws-bstore-4b 2021-01-27 17:56:54,340 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 17:56:54,340 INFO : [Loader] - Completed loading resource: dr346. Completed in 132.961seconds (2.2160168 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 18:04:27,632 INFO : [DataLoader] - There are 31045 records in the file. The number of NEW records: 56
aws-bstore-4b 2021-01-27 18:04:27,632 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Mammalogy-2020-11-30.csv
aws-bstore-4b 2021-01-27 18:04:27,793 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 18:04:27,793 INFO : [Loader] - Completed loading resource: dr346. Completed in 76.44seconds (1.274 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 18:09:53,037 INFO : [DataLoader] - There are 16494 records in the file. The number of NEW records: 3
aws-bstore-4b 2021-01-27 18:09:53,037 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Ichthyology-2020-11-29.csv
aws-bstore-4b 2021-01-27 18:09:53,182 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 18:09:53,182 INFO : [Loader] - Completed loading resource: dr346. Completed in 46.589seconds (0.77648336 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 18:16:14,510 INFO : [DataLoader] - There are 100490 records in the file. The number of NEW records: 143
aws-bstore-4b 2021-01-27 18:16:14,510 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Entomology-2020-12-1.csv
aws-bstore-4b 2021-01-27 18:16:14,657 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 18:16:14,658 INFO : [Loader] - Completed loading resource: dr346. Completed in 188.186seconds (3.1364334 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-01-27 18:23:33,449 INFO : [DataLoader] - There are 55767 records in the file. The number of NEW records: 27
aws-bstore-4b 2021-01-27 18:23:33,449 INFO : [DataLoader] - Load finished for SAMA-DWC-CSV-Arachnology-2020-11-30.csv
aws-bstore-4b 2021-01-27 18:23:33,635 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-27 18:23:33,635 INFO : [Loader] - Completed loading resource: dr346. Completed in 121.935seconds (2.03225 minutes)
Finished: SUCCESS
