### ISSUE TITLE
Delete images from MV record

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#634]
Spider record has lots of bird photos attached to it by error

https://biocache.ala.org.au/occurrences/160f6d90-cedf-45a1-8fd8-550d37efd274

I've "deleted" the images using the Admin/Delete function in the images service, but they need to be removed from the associatedMedia field in Cassandra.

The only valid image is: https://images.ala.org.au/image/details?imageId=1b92f3e8-903e-40a1-853d-9ac0155eefd3

**Comment by peggynewman** [comment]
Deleted in image service (but not yet purged) and to be removed from Cassandra:
https://images.ala.org.au/image/details?imageId=021d7b3e-31a4-4c2f-9c29-0998de2f17e7
https://images.ala.org.au/image/details?imageId=0a08103f-d282-497f-b3fe-3007d94e95b3
https://images.ala.org.au/image/details?imageId=0a3f9bab-bed1-460d-8faf-36484b23947e
https://images.ala.org.au/image/details?imageId=1b3787dc-e801-4ad5-9f95-09089b3c12b9
https://images.ala.org.au/image/details?imageId=5176ec12-4a1d-4e81-abb9-e1d6775f9269
https://images.ala.org.au/image/details?imageId=65443291-2e0c-43b9-b101-d8c20426e77a
https://images.ala.org.au/image/details?imageId=768c1520-b9b5-4d08-abfa-ef03c291cd06
https://images.ala.org.au/image/details?imageId=c33f780a-9b6d-4ec3-9563-1fd568400255
https://images.ala.org.au/image/details?imageId=c91948a8-4fba-47f7-ac23-fde99a16a9af
https://images.ala.org.au/image/details?imageId=ee369348-cb87-45ff-8e21-18a9d745d261

Retain the spider image:
https://images.ala.org.au/image/details?imageId=1b92f3e8-903e-40a1-853d-9ac0155eefd3

**Comment by sadeghim** [comment]
The corresponding dwca file is corrected and those wrong images are deleted from the record's associated image list.
The ingestion is undergoing and we check the results after indexing finished.

**Comment by sadeghim** [comment]
Fixed now.
