### ISSUE TITLE
Data load : BDBSA (SA Flora & Fauna)

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#637]
SA Fauna https://collections.ala.org.au/public/show/dr365
SA Flora https://collections.ala.org.au/public/show/dr366
Please report back here on whether this job is ready for automation/scheduling in Jenkins.

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [ ] Upload the dataset to collections.ala.org.au
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by patkyn** [comment]
Before load, there are 1,605,815 results for Data resource: SA Fauna (BDBSA)  

Triggered the Talend job GetData for 01122020 datetime to pull the 2 files from the uploads server into my local. Then called Fauna job to perform transform safauna_all_01122020.csv to conform to darwin core headers and generate SAfauna.DwC.csv csv file. There were 1608230 lines generated. The generated SAfauna.DwC.csv is copied to uploads server. Call Load/Process/Sample in Jenkins to load SAfauna.DwC.csv (https://collections.ala.org.au/dataResource/show/dr365)

```
aws-bstore-4b 2021-01-28 11:27:34,415 INFO : [DataLoader] - 1606000, >> last key : dr365|SUR796307-56, records per sec: 788.64355
aws-bstore-4b 2021-01-28 11:27:35,736 INFO : [DataLoader] - 1607000, >> last key : dr365|SUR910-56, records per sec: 757.00226
aws-bstore-4b 2021-01-28 11:27:36,997 INFO : [DataLoader] - 1608000, >> last key : dr365|SUR983113-27, records per sec: 793.02136
aws-bstore-4b 2021-01-28 11:27:37,298 INFO : [DataLoader] - There are 1608230 records in the file. The number of NEW records: 3326
aws-bstore-4b 2021-01-28 11:27:37,299 INFO : [DataLoader] - Load finished for dr365.csv
aws-bstore-4b 2021-01-28 11:27:37,500 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-01-28 11:27:37,500 INFO : [Loader] - Completed loading resource: dr365. Completed in 2213.849seconds (36.897484 minutes)
Finished: SUCCESS
```

**Comment by patkyn** [comment]
Reloaded SAflora.Dwc.csv

```
aws-bstore-4b 2021-02-12 15:18:43,415 INFO : [DataLoader] - 1890000, >> last key : dr366|SUP9930-5, records per sec: 805.153
aws-bstore-4b 2021-02-12 15:18:44,682 INFO : [DataLoader] - 1891000, >> last key : dr366|SUP9968-17, records per sec: 789.266
aws-bstore-4b 2021-02-12 15:18:45,924 INFO : [DataLoader] - There are 1891978 records in the file. The number of NEW records: 9380
aws-bstore-4b 2021-02-12 15:18:45,924 INFO : [DataLoader] - Load finished for dr366.csv
aws-bstore-4b 2021-02-12 15:18:46,104 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-02-12 15:18:46,104 INFO : [Loader] - Completed loading resource: dr366. Completed in 2621.806seconds (43.696766 minutes)
Finished: SUCCESS
```
