### ISSUE TITLE
Load data : Passive eDNA collection enhances aquatic biodiversity analysis

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#650]
Data resource has already been set up: https://collections.ala.org.au/public/show/dr16844

- [x] Check that the unique key in the file is not empty or duplicated (occurrence ID)
- [x] Upload the dataset to collections.ala.org.au
- [x] Specify the unique key in the connection parameters
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [x] Wait for next complete reindex
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [x] Ask the data provider to review the new records using the same URL

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-02-26 10:06:59,244 INFO : [DataLoader] - There are 3984 records in the file. The number of NEW records: 3983
aws-bstore-4b 2021-02-26 10:06:59,244 INFO : [DataLoader] - Load finished for dr16844.csv
aws-bstore-4b 2021-02-26 10:06:59,382 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-02-26 10:06:59,382 INFO : [Loader] - Completed loading resource: dr16844. Completed in 8.919seconds (0.14865 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
Data updating request from Michael has been successfully completed by uploading updated file to collection website and re-executed Jenkins job. 

Confirmation from Michael that updated dataset is all good.
