### ISSUE TITLE
Data load : Platypus conservancy files

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#651]
Data resource: https://collections.ala.org.au/public/showDataResource/dr8128

5 files
- [x] APC ALA records 2018.2 (Mar-May).xls
- [x] APC ALA records 2018.4 (Sep-Nov).xls
- [x] APC ALA Plat NSW+ACT.xls
- [x] APC ALA Plat Qld + Tas.xls
- [x] APC ALA records QLD platypus corrections (2021 Feb).xls

For each
- [x] Upload the dataset to collections.ala.org.au
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [x] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
After next complete reindex:
- [x] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [x] Ask the data provider to review the new records using the same URL

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-03-04 10:58:31,476 INFO : [DataLoader] - There are 586 records in the file. The number of NEW records: 555
aws-bstore-4b 2021-03-04 10:58:31,477 INFO : [DataLoader] - Load finished for dr8128.csv
aws-bstore-4b 2021-03-04 10:58:31,609 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-03-04 10:58:31,609 INFO : [Loader] - Completed loading resource: dr8128. Completed in 3.094seconds (0.051566668 minutes)
Finished: SUCCESS
