### ISSUE TITLE
Load DwCA with multiple images

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#66]
Get a Darwin core archive, pull it apart and find the images, load the images into images.ala.org.au, along with image metadata, and the occurrence records with correct image references.

**Comment by AlexisTindall** [comment]
Hi Doug, 

Is this an issue related to our 'images with diverse metadata' discussion last week? As I discussed with Miles, the set of Museum Victoria images would be the best group with which to test this - they have a number of instances of multiple images of the same occurrence taken by different photographers or with other differing metadata. They're also very keen to see this issue resolved. 

Thanks for following this up. 
Alexis

**Comment by djtfmartin** [comment]
I had a chat with @M-Nicholls about this.

The way to tackle the issue would be to extend the biocache code to support a image extension in DwC-A. The biocache could then support an extensible list of key/value pairs for each image (stored in image-service).

We shouldnt go down the route of loading the images first and then join things up in the biocache.

**Comment by djtfmartin** [comment]
@M-Nicholls @charvolant do we have a dataset already supplying images with a DWC-A extension ? 

NZVH is planning to send up data in this format using Audobon core properties in the images extension.

**Comment by M-Nicholls** [comment]
@djtfmartin @charvolant yup, MV sent an example data set it's on the filestore

**Comment by charvolant** [comment]
Looking through example data and biocache-store.

First attempt at getting an handle on what's there:

* Images have rowType http://rs.gbif.org/terms/1.0/Image (deprecated) or http://rs.gbif.org/extension/gbif/1.0/multimedia.xml so it should be fairly easy to locate their extension file. 
* The image metadata comes from DCTerms
* The process of loading a DwCA in the biocache unzips the file into a temporary location (DwCALoader).
* During loading, the loader iterates over the archive using an ArchiveIterator. This iterator pulls in the extension data associated with each record as it traverses the archive. So a next() returns the complete record. These then get translated into a FullRecord, the Occurrence part of which contains an array of image URLs
* The OccurrenceDAO transfers these records into the store. 
* The RecordProcessor has images are accessed and added to the image store via the OccurrenceDAO. The associatedMedia entry is then rebuilt with the image store images.
* The MediaStore (abstract, with two concrete instances for local files and a service) stores the images and assigns them ids.

Things I need to find:

* The images come with a nice crop of metadata. When these are put into an occurrence record, they're reduced to URLs. From the look of things, the simplest solution is to pre-upload the images to the image service and set metadata before storing the occurrence data. The occurrence data can then be linked directly to the image already in the image store. 
* TODO It's not immediately obvious how metadata gets added to images the MediaStore doesn't seem to have methods for that.
* TODO Transactional, schmactional. Doing things this way can potentially create images which are never linked to occurrences, since they have been stored before the occurrence data is added and if adding the occurrence data fails, there are a bunch of images dangling in the breeze.
* We need to be consistent about whether identifiers are listed in the fields of the core/extension metadata. The sample data doesn't have a field entry for the identifier field in both the core and the extension.

**Comment by M-Nicholls** [comment]
needs a facility to add images to existing records already loaded into the biocache without re-supplying the whole record

"The vast majority (if not all) of the images that are ready to be delivered by the herbaria – and there are potentially tens of thousands of them – are of specimens that already have records in AVH, so sending a DwC extension with the specimen data won't work so well for us. As pointed out, the ability to add images to an existing specimen record would greatly ease the delivery of specimen-related images."

**Comment by M-Nicholls** [comment]
also consider options for extracting image specific metadata from the exif data

**Comment by charvolant** [comment]
The image upload already automatically extracts EXIF data and puts it into the embedded tab.

**Comment by charvolant** [comment]
Pull request at https://github.com/AtlasOfLivingAustralia/biocache-store/pull/50

**Comment by djtfmartin** [comment]
ive merged this - thanks !

**Comment by charvolant** [comment]
A warning to young players. The meta.xml has to correctly specify the `fieldsEnclosedBy="&quot;"` attribute to stop things from getting pretty yukky.

**Comment by charvolant** [comment]
Metadata loading correctly. The description field in System and the description field in Image Properties seem to refer to two different attributes, so populating one does not populate the other.

**Comment by charvolant** [comment]
It would be good to have a stable source of data for images. Unzipping the DwCA on the biocache means that the source images will eventually be cleaned up and got rid of. Instead, the collectory could act as a single point of reference for image data that has come from a dataset. There's a few steps here ...

* Have the collectory keep a trail of uploaded data, placed in permanent locations
* Have the collectory place additional media contained in a DwCA in a stable location
  * And by extension, correct URLs in associatedMedia or media extensions to point to the new location
  * Or provide a base URL so that relative media references can be resolved
* Have the collectory allow URL access to uploaded additional media
* Only transfer the core+extension data to the biocache when loading; the media can then be loaded from the collectory
