### ISSUE TITLE
Remove homo sapien images and records

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/data-management#660]
Reported by GBIF

https://www.gbif.org/occurrence/1632949261

and

https://bie.ala.org.au/species/NZOR-6-89915#overview

We should remove these old images and block images for homo sapiens from species pages. 
AFAIK we did used to do this in BIE, so there's a regression.

**Comment by djtfmartin** [comment]
Related:

https://github.com/gbif/pipelines/issues/489

**Comment by peggynewman** [comment]
All homo sapien records are museum records currently. Closing.
