### ISSUE TITLE
Delete lat and long from four MV records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#661]
From https://support.ehelp.edu.au/a/tickets/102143: Customer has asked us to remove location data from four MV records, and to confirm that spatial information will be removed after this is done. Have advised that removing the lat/long and reprocessing the record should remove location/spatial information, but we should be able to remove it manually if necessary.

Original email below:

We’re removing erroneous geo-location data from four records that recently received annotations. The fields will be blank when in our next export but that won’t overwrite the data that is already there so please could those fields be cleared out?
 
The four records are:

F250602 | https://biocache.ala.org.au/occurrences/e7d2bc51-3e02-4775-8e87-940a098da1c4
F250603 | https://biocache.ala.org.au/occurrences/bb6b0d87-da69-41b1-b2a1-63d8de6bdc80
F8987 | https://biocache.ala.org.au/occurrences/3e7b3a8d-3160-403e-8aa4-1dfa5b3529c7
F245659 | https://biocache.ala.org.au/occurrences/5caea147-0168-4776-b021-ed870ac2a172

The fields that need to be cleared are:
 
Latitude: decimalLatitude
Longitude: decimalLongitude
Geodetic datum: geodeticDatum
Coordinate Precision: coordinateUncertaintyInMeters
 
I don’t think any of the records currently have anything in verbatimLocality but we’ll be providing text in that field in our next export which will overwrite whatever is there. The value that appears in the field Locality on the ALA pages isn’t something we supply – will it and the Biome and other information based on the georeferenced data automatically update when the lat and long are removed or will they need to be manually cleared out too?

**Comment by timhicks-ala** [comment]
FYI @peggynewman - maybe one for @zalicedc ?

**Comment by timhicks-ala** [comment]
Additionally raised in https://support.ehelp.edu.au/a/tickets/110867

**Comment by sadeghim** [comment]
The data set is updated and waiting for the indexing.
Will check it tomorrow.

**Comment by sadeghim** [comment]
@timhicks-ala This is resolved now.
