### ISSUE TITLE
2021 Name Index

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#665]
- [x] Acquire up to date data sources
  - [x] AFD
  - [x] APNI/APC
  - [x] AusMoss
  - [x] Check with Tom May to see whether we can use the new NSL AusFungi
  - [x] AusFungi
  - [x] NZOR
  - [x] CAAB
  - [x] CoL
- [x] Port pre-processing code library to python
  - [x] Port AFD
  - [x] Port NSL
  - [x] Port NZOR
  - [x] Port CAAB
  - [x] Port ALA Species Lists
  - [x] Auto-generate EML
- [x] Merge taxonomic sources
- [x] Build name index
- [x] Run identification across previous/new name index and compare results
- [ ] Confirm any data issues from last name index fixed
- [x] Deploy new name index onto test
- [x] Rebuild test BIE
- [ ] Re-process and re-index test biocache
- [ ] Confirm correct behaviour
- [ ] Prepare comms announcement
- [ ] Deploy new name index onto production
  - [ ] Reprocess BIE
  - [ ] Reprocess SDS
  - [ ] Reprocess Species Lists
  - [ ] Reprocess biocache
  - [ ] Reprocess profiles
- [ ] Send notifications

**Comment by charvolant** [comment]
Current issues:

* Need to check with NSL since their taxon IDs seem to be on the /tree branch rather than the /node branch

**Comment by charvolant** [comment]
Planning to add lichens from  https://lichen.biodiversity.org.au

**Comment by charvolant** [comment]
APNI, APC, AusMoss, AusFungi (NSL) downloads are showing problems with identifiers. Being fixed by NSL.

**Comment by peggynewman** [comment]
Watching!

**Comment by charvolant** [comment]
Additional problems with NSL download giving incorrect URLs.

**Comment by charvolant** [comment]
New name index deployed 2022-07
