### ISSUE TITLE
Load data : Geelong Field Naturalists Club

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#667]
https://support.ehelp.edu.au/a/tickets/105655

CSV files uploaded to https://collections.ala.org.au/dataResource/show/dr10631

Hi ALA Data Management

I have been given the task of uploading four sets of data for the Geelong Field Naturalists Club.

I have prepared the following csv files and tested them in the Sandbox.  The files are attached:

gfnc_observations__reptile Ver 4_ALA_698.csv
gfnc_observations__mammal Ver2 _ALA_895.csv
gfnc_observations__butterfly Ver 4_ALA_1608.csv
gfnc_observations__butterfly saltbush blue-export_ALA_1189.csv

The club has agreed to use the Creative Commons Attribution license.

Can you please complete the data upload process using "Geelong Field Naturalist Club" as the data set name?

- [ ] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [ ] Ask data provider for metadata, including:
* Data resource name
* Description
* License : prefer Creative Commons Attribution https://creativecommons.org/licenses/by/4.0/
* Citation : Statement to be used by those downloading and using these records
* Contact : Email and/or phone number
* Website : (Optional)
- [ ] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [ ] Create new data resource using https://collections.ala.org.au/admin
- [ ] Upload the dataset to collections.ala.org.au
- [ ] [Optional] If the dataset is destined to be included in a data hub, identify the data hub and add the new data resource id to its list https://collections.ala.org.au/dataHub/list
- [ ] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
Done a long time ago
