### ISSUE TITLE
License data not coming through on occurrence records loaded via IPT 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#668]
https://biocache.ala.org.au/occurrences/search?q=-license:*

These all look like files delivered via IPTScan, so there might be a bug fix needed there.

Data resources:
[data (20).csv](https://github.com/AtlasOfLivingAustralia/data-management/files/6449232/data.20.csv)

Top 10: 
```
"data_resource_uid","name","count"
"dr15860","CANB AVH data","1014719"
"dr15863","PERTH AVH data","810979"
"dr15861","NSW AVH data","750221"
"dr15865","Australasian Virtual Herbarium (AVH) data from the State Herbarium of South Australia (AD)","737095"
"dr2287","BRI AVH data","550069"
"dr95","Southern Ocean Continuous Zooplankton Recorder (SO-CPR) Survey","546549"
"dr15866","DNA AVH data","325237"
"dr15867","CNS AVH data","187764"
"dr165","Seabirds of the Southern and South Indian Ocean","153771"
```

**Comment by nielsklazenga** [comment]
Thanks @peggynewman , I would not have thought that this would be in the IPT Scan, as both @patkyn and I have looked at that pretty closely, but I have noticed (and been annoyed) that every time I look up the data resources in the Collectory the license information has been lost and these are indeed all IPT data sets.

**Comment by peggynewman** [comment]
I assume that a record level license would just come through the data if it were there. But the the license must set as a default value in the collectory otherwise.
eg. This clearly has a dataset level CCBY 4 license https://data.aad.gov.au/ipt/resource?r=socpr
But in the collectory nothing is set in the default values - only in the "Rights" field https://collections.ala.org.au/dataResource/show/dr95
Doesn't IPTScan write to the collectory?

**Comment by nielsklazenga** [comment]
Correction: The Collectory does not actually let you set a default for the 'license' field. Something to keep in mind for the next stage of the infrastructure project.

I can do it in my IPT for the AVH data resources that I am still delivering (and can contact the others), but @patkyn cannot do the same for the OBIS and AAD data resources.

**Comment by peggynewman** [comment]
Note pipelines handling of license:
https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/271

**Comment by peggynewman** [comment]
Closing, most things now have a license
