### ISSUE TITLE
Jenkins DwCA - Import BioCollect Records (Daily)

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#680]
Name | Schedule | Schedule comments | Date last run | DR uid | DR name | DR record count? | DwCA? | Broad description of job
-- | -- | -- | -- | -- | -- | -- | -- | --
Import   BioCollect Records (Daily) | Daily | H 0 * * * | 01-February-2021 | NA | NA | NA | NA | A job that harvests in the   individual sightings recorded through the http://sightings.ala.org.au tool.

**Comment by patkyn** [comment]
Fields omitted from harvest:
licence - contains invalid data. Instead license is picked
identificationConfidence
eventFinishDate
comments
occurrenceDate
surveyDate
surveyEffort
observationRemarks

**Comment by nielsklazenga** [comment]
Should we map them to Darwin Core terms?

**Comment by patkyn** [comment]
Thank you for the feedback @nielsklazenga. Just wondering, which fields you are thinking of?

**Comment by nielsklazenga** [comment]
I think:
- identificationConfidence => `identificationRemarks`
- surveyEffort => `samplingEffort`
- observationRemarks => `occurrenceRemarks`
- occurrenceDate => `eventDate`
- eventFinishDate => `eventDate` (if there is an 'eventDate', but no 'occurrenceDate')
- surveyDate => `eventDate` (if none of the other dates are given)

We can put all the literal properties in `dynamicProperties` as well, if we can put them in a 'BioCollect' namespace.

**Comment by patkyn** [comment]
Ran biocollect harvest and ingestion in production.

dr3368 has had key changed to occurrenceID from catalogNumber. dr3368 seemed to have loaded by file upload in collectory at some point. Biocollect api doesn't output catalogNumber hence but catalogNumber. And the existing records cannot be re-linked by occurrenceID or catalogNumber. These had caused the uuids for the records to change. 
![image](https://user-images.githubusercontent.com/1606595/144947636-21011359-3b7c-4a2d-a032-befc42c7b2e5.png)


Backup of the previous dr3368 is stored in /data/dmgt/dr/dr3368/input/2021-12-03/dr3368-dwca-orig.zip.

**Comment by sadeghim** [comment]
Closing this as it has been completed a while ago.
