### ISSUE TITLE
Jenkins job to replace Parameterised Load Sample Process job

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/data-management#689]
All (or almost all) scheduled upload jobs in the old infrastructure use the Parameterised Load Sample Project job, for which there is no full replacement in Jenkins in Pipelines. 

The Jenkins job to be created should:
- Get the Data URL for the DR from the Collectory
- If this URL points to a directory on the upload server:
  - Find the latest file in this directory
  - Check if this file is more recent than the last time the DR was updated
- Trigger 'Data resource load' using the code that is now repeated in all Data-resource-load jobs.

**Comment by peggynewman** [comment]
Closing as this is covered off by preingestion
