### ISSUE TITLE
Default settings for annotation alerts for individual users

### ISSUE THREAD

**Issue by AlexisTindall** [AtlasOfLivingAustralia/data-management#69]
As discussed with Alison, Miles and Michael (02/03/15). 

Can we look into making the default setting for individual users to get alerts if there are annotations on the occurrences they upload? This would help prompt them to re-identify their sightings if their identifications are corrected by an expert. 

Can alerts be sent when annotations are responded to?

**Comment by djtfmartin** [comment]
Thanks Alexis. We are working on a new annotation tool (working name "taxon-overflow") which should address this.

**Comment by AlexisTindall** [comment]
Thanks Dave. I heard about Taxon Overflow last week. That'll work well for people who know that they can't identify the thing they have found, and is a good move, but it won't help the situation where people have 'confidently' mis-identified a sighting. 

Here is an example of this: 
http://biocache.ala.org.au/occurrences/d6ef84a2-de09-4b72-a4df-f8570402680b

Laura (the original contributor) won't get a notification of Mark's annotation unless she's signed up for alerts, and individual users might not immediately see the benefit in doing that. She is the only person who can change the identification on her reported sighting. 

Our suggestion was that individual users get automatically signed up for alerts on their sightings, which will help improve the quality of their data, and their engagement with the Atlas.

**Comment by djtfmartin** [comment]
Thanks Alexis. We plan to support both use cases in taxon overflow.

It'll be a centralised system for supporting identifications and flagging misidentifications from different bits of the Atlas/Ozcam/AVH etc. 

It'll replace the "Flag an issue" button and be integrated as a widget on the record pages.

**Comment by acvaughan** [comment]
This is a related issue: https://github.com/AtlasOfLivingAustralia/data-management/issues/76

**Comment by M-Nicholls** [comment]
developed and deployed
