### ISSUE TITLE
Issue in convert csv to dwca

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/data-management#690]
Currently, new or updated records show individualCount and coordinatePrecision as float. For eg: https://biocache.ala.org.au/occurrences/0e76fc74-269c-4681-9c93-20ba6859849b

Existing records that has not been updated still remains unchanged. For eg: https://biocache.ala.org.au/occurrences/f45c2bbb-9bda-400b-923b-6dd59ac326f2

The reason why this happens is:
The csv to dwca converter should read in values as string rather than converting it to float. For eg, Bionet job extract the sightings as string but during the reading in dwca-dr, this has been converted to number in the generated dwca

![image](https://user-images.githubusercontent.com/1606595/124246619-6ef9a880-db64-11eb-9fe5-e81355f663d3.png)

Another issue with the csv to dwca converted is if there's a multiline string. This happens for dr344. A record has been split into 2 records because of multiline in a field. 

![image](https://user-images.githubusercontent.com/1606595/124247986-c0566780-db65-11eb-9218-0deaafe8de88.png)

**Comment by sadeghim** [comment]
I see that for QM, the multiline string is processed properly in Solr:
`        "preparations":["Pin\nSlide"],`

But I cannot see this field in https://biocache.ala.org.au/occurrences/ca374cf5-b1c9-4ce2-9d84-ea434bf49950 which maybe is a bug for biocache hub as I see it in the ws: https://biocache.ala.org.au/ws/occurrences/ca374cf5-b1c9-4ce2-9d84-ea434bf49950

@nickdos any thought on this?

**Comment by nickdos** [comment]
> I see that for QM, the multiline string is processed properly in Solr:
> ` "preparations":["Pin\nSlide"],`
> 
> But I cannot see this field in https://biocache.ala.org.au/occurrences/ca374cf5-b1c9-4ce2-9d84-ea434bf49950 which maybe is a bug for biocache hub as I see it in the ws: https://biocache.ala.org.au/ws/occurrences/ca374cf5-b1c9-4ce2-9d84-ea434bf49950
> 
> @nickdos any thought on this?

Added https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/478

**Comment by sadeghim** [comment]
Closing this as the main issue here is fixed.

Remaining problem has been addressed in another issue: AtlasOfLivingAustralia/la-pipelines#478
