### ISSUE TITLE
New data load - Cantebury Museum NZ Mayfly collection

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#691]
I've already set up a collection and provider map for this, but not yet a data resource.

Institution: https://collections.ala.org.au/institution/show/in686 
Collection: https://collections.ala.org.au/public/show/co305
ProviderMap: https://collections.ala.org.au/providerMap/show/160

The data in the sandbox needs a collectionCode='mayfly' column associated with it to be able to map correctly to the collection. institutionCode should also be checked.

Data in Sandbox: https://sandbox.ala.org.au/tempDataResource/viewMetadata?uid=drt23115

Tasks:

- [x] create data resource
- [ ] add 'mayfly'  column to dataset in sandbox (no longer required, see below)
- [x] create drxxx in /data/dmgt/drxxx with raw/ current/ history directories as per Confluence instructions https://confluence.csiro.au/display/ALASD/Pre-Ingestion+framework
- [x] run Ingest-dataset

**Comment by peggynewman** [comment]
Support ticket history: https://support.ehelp.edu.au/a/tickets/101862

After this is done, they are keen for data to be loaded to GBIF and to load another dataset, for which we'll likely have to create a new collection and advise on the collectionCode to be provided with the data.

**Comment by charvolant** [comment]
Loaded into pipelines at https://collections.ala.org.au/public/show/dr17655. Awaiting index to check on collection/institution mapping. Supplied data has a collection code of `Spirit Collection` so using that as a mapping.
