### ISSUE TITLE
Ingestion of the data resource dr17505 and dr17504 has failed to pass the validation.

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/data-management#694]
Ingestion of the data resource dr17505 and dr17504 has failed to pass the validation.
http://aws-spark-quoll-master.ala:9194/job/UUID-dataset/760/console
http://aws-spark-quoll-master.ala:9194/job/UUID-dataset/761/console

dr17505
![image](https://user-images.githubusercontent.com/1606595/125556515-a22e84a4-f8c5-4e3b-aaaa-4ef629fa6f17.png)

The darwin core file is sourced from the IPT https://www.marine.csiro.au/ipt/resource.do?r=gbr_northern_prawn_survey_catch
Validation for the darwin core file has passed: https://www.gbif.org/tools/data-validator/1622015286837

Further investigation shows occurrenceID is all unique in the occurrence.txt (column 8). There is also no empty keys.
So what is causing it to fail the duplicate and empty key checks? 
Could this be because the core id field in occurrence.txt is not unique? The id in event.txt is unique in this case. 
![image](https://user-images.githubusercontent.com/1606595/125557731-dd8a0ee7-2d39-4f86-8a7b-7e48baa51abe.png)

**Comment by djtfmartin** [comment]
This datasets should be available in next index

**Comment by djtfmartin** [comment]
These archives are now loaded.
https://biocache.ala.org.au/occurrences/search?q=dataResourceUid:dr17504
https://biocache.ala.org.au/occurrences/search?q=dataResourceUid:dr17505
