### ISSUE TITLE
Data load : Melbourne Water Frog Census Data 20210722

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#698]
Raised in https://support.ehelp.edu.au/a/tickets/112137
CSV file MW_Frog_Census_Data_Upload_22072021.csv is uploaded to https://collections.ala.org.au/public/show/dr737

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

**Metadata**
- [x] Locate the existing data resource in the collectory and check metadata and parameters: https://collections.ala.org.au/dataResource/show/dr737
- [ ] Check the unique identifier matches that in the new dataset

**Data Prep**
- [x] Download existing DwCA from hdfs with the intent to merge the two DwCAs 
- [ ] Map new dataset to the corresponding Darwin Core Terms in a CSV if necessary http://rs.tdwg.org/dwc/terms/. Package the CSV into a Darwin Core Archive
- [ ] Ensure the new dataset has correctly specified unique identifier without duplicates, and matches the unique identifier in the collectory connection parameters
- [ ] Ensure images are specified in an images file in the DwCA with the identifier field populated
- [ ] Check that species, location, times are adequately specific. Check back with the data provider if necessary
- [ ] Merge the two datasets

**Data Load**
- [ ] Upload the new DwCA to the dmgt server
- [ ] Run the Ingest_dataset job on Jenkins, setting the data resource UID (DRNNNN) parameter http://aws-spark-quoll-master.ala:9194/job/Ingest-dataset/
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
**QA**
- [ ] Wait overnight for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr737
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
Fixed a long time ago
