### ISSUE TITLE
Fix Tas seed centre processing

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#71]
transform from degrees minutes  seconds to decimal degrees isn't correct - For consistency it's better to let the biocache load do the transform from the verbatim coordinates rather than manually processing before the load

**Comment by sadeghim** [comment]
Waiting to be loaded.

**Comment by sadeghim** [comment]
Loaded but needs to delete the decimal coordinates column.

**Comment by sadeghim** [comment]
Deleted the columns but the coordinates are not shown on the map.

**Comment by sadeghim** [comment]
The right format of the verbatim strings are generated and ingested by biocache.
