### ISSUE TITLE
Yugul Mangi occurrence data load

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#718]
Ask Peggy for emails containing data and metadata.

**Comment by sadeghim** [comment]
DR is created: https://collections.ala.org.au/public/show/dr17780

**Comment by sadeghim** [comment]
Lat and Lon were swapped. Fixed and re-ingested. Waiting for the indexing tomorrow.

**Comment by peggynewman** [comment]
There are still 2 records with spatial issues. 
![image](https://user-images.githubusercontent.com/1271932/131466252-f8bf90cf-3541-4b6b-af54-d9efe10dadc5.png)

**Comment by sadeghim** [comment]
The issue is fixed now. There was an issue with the coordinates in the original data:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/1578598/131757352-902fac6d-0827-407e-859b-20f1ae0238ca.png">
