### ISSUE TITLE
Missing plant classification

### ISSUE THREAD

**Issue by acvaughan** [AtlasOfLivingAustralia/data-management#75]
The classification in APC is incomplete; several groups of vascular plants are missing and families that are recognised by APC, but are missing the classification in APC (such as Chenopodiaceae), are not in the APGIII classification, so users can't query for them. 

I'm not clear exactly where the responsiblity lies for this (ALA, ANBG, ABRS ...).

HIGH PRIORITY

**Comment by M-Nicholls** [comment]
if the APC itself is incomplete it's an ABRS matter but if the APC is complete but the ALA is not showing the information properly then it's an ALA responsibility

Chenopodiaceae is in the ALA and appears to have a full classification.  If there are further problem please provide a few examples.
