### ISSUE TITLE
DR341 - Schedule ANWC weekly job

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#759]
Previous jenkins job ran Friday 1am, but the files tend to land in uploads (see anwc) on saturdays at 11pm.
Schedule the ingest-dataset for Monday.

Adhoc job: http://aws-spark-quoll-master.ala:9194/job/Data-resource-loads/job/dr341-canb-anwc-weekly/

Notes:
Source files on uploads: /mnt/data/anwc/upload/anwc/
Collectory points to: sftp://upload.ala.org.au:ala/dr341/Mapped-Archive.zip
Scripts are all on /data/dmgt

**Comment by sadeghim** [comment]
Closing this as it has been completed a while ago.
