### ISSUE TITLE
Improve annotation verification options

### ISSUE THREAD

**Issue by acvaughan** [AtlasOfLivingAustralia/data-management#76]
Currently, you can't tell the difference between an annotation made by a user and one provided by a collections manager. Ideally, once a collection manager has either verified or corrected the data, the original user annotation flag should be removed (though the annotation history should remain), so it is no longer flagged as a potentially erroneous record. It would also be good to have better options for responding to annotations, so it's clear whether the user annotation is being accepted (and the data corrected), or refuted (and the data left as is).

HIGH PRIORITY for both botanical and zoological communities.

**Comment by acvaughan** [comment]
This is a related issue: https://github.com/AtlasOfLivingAustralia/data-management/issues/69

**Comment by djtfmartin** [comment]
Thanks Alison. We plan to address this in the taxon-overflow work.
So annotations will show the users' institutional affiliation where possible.

**Comment by AlexisTindall** [comment]
Hi Dave. Will this also allow people to make 'verified' responses? Some users use annotations as data quality tools at present, filtering out results with annotations as a means of identifying that something is wrong with those records. We were hoping that with a verified response a record that has been corrected or refuted by an authorised user could be considered either un-annotated, or verified to indicate that the question over quality has been resolved.

**Comment by djtfmartin** [comment]
Yes on verified responses.

Marking records an un-annotated once a record has been verified needs more discussion i think. Being able to retrieve a list of records that have had an annotation in the past seems like a useful thing. Perhaps we need some way of just filtering in/out records that have "open" questions raised against them.

**Comment by AlexisTindall** [comment]
Definitely - un-annotated wouldn't be the best approach - it wasn't the best way of describing that. My intention was more that they wouldn't be considered in the same way as annotations with open questions - you've put it much better. Thanks.

**Comment by M-Nicholls** [comment]
Annotation verification categories:

"Corrected" (issue has been corrected in the source data and updated in the ALA)
"Verified" (record is correct, no changes needed)

other wise an annotated record has an "Open issue" (issue has been flagged, it either hasn't been fixed or can't be fixed) status

**Comment by M-Nicholls** [comment]
Functionality has been implemented and looks good - some follow up needed on the change in index values causing problem with alerts but I'll log a separate issue for that
