### ISSUE TITLE
Load data : Woodlark Island SHP Files

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#774]
Source shapefiles emailed on 9/11/21

**Comment by peggynewman** [comment]
Data is in and going to GBIF:
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr18302#tab_mapView

@charvolant do you have any python code you've used for mappings? I was going to share them with the data provider. Also am yet to get metadata from them.

**Comment by peggynewman** [comment]
This is done but there are no scripts. Emailing data provider to ask if they want to continue working on something else. Closing this.
