### ISSUE TITLE
SA DEWNR Flora and Fauna

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#78]
Turn the long-running SA DEWNR flora and fauna uploads into an issue, since it's worth recording some progress and information about them.

The two datasets are

* http://collections.ala.org.au/public/showDataResource/dr365
* http://collections.ala.org.au/public/showDataResource/dr366

**Comment by charvolant** [comment]
##Stripping garbage from the supplied data

The datasets provided can have embedded SQL commands, extraneous double quotes at the start (but not the end) of fields and lots of trailing whitespace. This appears to be an issue with the DEWNR SQL server being stupid about things. To clean this up, use the following sed script

    sed -r -e '1,30d
    32,76d
    s/"//g
    s/ +,/,/g
    s/ +$//' fauna.csv > fauna_adjusted.csv

This will need to be fiddled with.

Explanation: `-r` means use extended regular expressions. `1,30d 32,76d` means delete lines 1-30 and 32-76, the echoed SQL (line 31 is the header). `s/"//g` means replace every double quote on the line with nothing. `s/ +,/,/g` means replace any sequence of spaces followed by a comma with the comma. `s/ +$//` means replace every set of trailing spaces up to the end of the line with nothing.

**Comment by charvolant** [comment]
Data loaded.

Waiting for a re-index before we work out what records need to be culled.

**Comment by charvolant** [comment]
Provided list of "extra" records for possible deletion.

**Comment by charvolant** [comment]
There's a problem with some fields being mis-aligned, leading to weird locations and other horrors. See http://biocache.ala.org.au/occurrences/040dfffb-48b4-4634-b5c9-2a9191a8bfbe for an example

**Comment by charvolant** [comment]
The misalignment problem is caused by commas appearing in the observer field. There's a general problem with the way the original dump was generated, since it needed to play around with various bit of awkwardly formatted data. There's a new data load coming and fixing the CSV formatting in the original dump should do the trick.

**Comment by charvolant** [comment]
SA-DEWNR now has a key access to the sftp server and have added new dumps.

**Comment by charvolant** [comment]
Fauna loaded. Flora loaded into sandbox for checking by SA-DEWNR

**Comment by charvolant** [comment]
Loaded flora. Fauna needs to be re-checked.

**Comment by charvolant** [comment]
Loaded flora and fauna.

**Comment by charvolant** [comment]
There are a few "extra" records that have crept back into the dataset. Checking to see whether they can be cleanly deleted.

**Comment by M-Nicholls** [comment]
the new extraction of data is ready to download to ALA:
The files saflora_all_21072016 and safauna_all_21072016 are in the ftp area.

**Comment by charvolant** [comment]
Latest update from DEWNR imported om 23/08/16
