### ISSUE TITLE
Data load : Bdbsa SA Flora and Fauna (12/2021)

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#780]
Helpdesk ticket is https://support.ehelp.edu.au/a/tickets/123051

The SA Department for Environment and Water has created an updated version of the SA Flora (BDBSA) and SA Fauna (BDBSA) records on the ALA FTP site. `/mnt/data/dewnr-sa/upload/dewnr-sa`
Please update the datasets metadata with the month and year of this extraction - 12/2021

- [ ] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

Data Resources:
SA Fauna : https://collections.ala.org.au/public/show/dr365 1,670,076 records
SA Flora: https://collections.ala.org.au/public/show/dr366  1,929,054 records

- [ ] Check that the Darwin Core Terms in the new data are consistent with the existing data
- [ ] Check that the unique identifiers in the new data are consistent with the existing data, and with the connection parameters in the collectory 
- [ ] Ingest dataset 
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr365
https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr366
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
Raj, I assume you have ssh access to the uploads.ala.org.au server. Let Matt know if not.

**Comment by peggynewman** [comment]
My mistake. This was run on 7 Feb.
