### ISSUE TITLE
Data load : Mittagong Creek, Bowral & Whites Creek, Moss Vale Macroinvertebrate data Spring 2021

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#781]
Ticket: https://support.ehelp.edu.au/a/tickets/123071
DR: https://collections.ala.org.au/public/show/dr7949

File ALA-occurrence-data-Spring 2021.xlsx has been uploaded to data resource

Previous example: https://github.com/AtlasOfLivingAustralia/data-management/issues/671

- [x] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [x] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [x] Upload the dataset to collections.ala.org.au
- [x] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
Data is in.

**Comment by cha801p** [comment]
Data loaded on prod. New 62 records added. 
https://collections.ala.org.au/public/show/dr7949
