### ISSUE TITLE
Record deletion request - "unregistered" records in SAM data

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#792]
From ticket: https://support.ehelp.edu.au/a/tickets/127312

This covers 150 records in SAM data where the text "unregistered" appears in the catalogue number: https://biocache.ala.org.au/occurrences/search?q=text%3Aunregistered&qualityProfile=ALA&fq=data_resource_uid%3A%22dr346%22

Note that there may be affected records in the most recent SAM dataset.

"I've just discovered that some records have been added to some of our collections which were not intended to be sent to yourselves but did not have that indicated.
 
Could any records which have the string "unregistered" in their recordNumber (for example "MA-1241.unregistered") please be deleted from our (SAMA) data. These records have now been appropriately flagged and will not be sent through again in future
 
In the most recent data I sent through I believe there were three records like this."

**Comment by patkyn** [comment]
The unregistered catalog number records have now been removed
