### ISSUE TITLE
New Data Load : dr19843 TERN Ecosystems Surveillance

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#796]
- [ ] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

**Metadata**
I suggest we approach the collectory entries this way, setting them up in collections-test first then in production once we've verified with TERN.
In the collectory:
- [ ] **Terrestrial Ecosystem Research Network (TERN)** data provider 
- [ ] **TERN Ecosystems Surveillance** data resource 
- [ ] **TERN Ecosystem Surveillance Facility** collection (under the [University of Adelaide institution](https://collections-test.ala.org.au/public/show/in31))
- [ ] A provider map for the collection code (TERN) and institution code (UA) above to add to the data
- [ ] Dataset is intended to be included in AVH. collectionID and dataresourceID get added in data hub 9 https://collections.ala.org.au/dataHub/list. Check with AVH.

We still need:
- [ ] Description
- [ ] Citation : Statement to be used by those downloading and using these records
- [ ] Contact : Email and/or phone number

**Data Load**
- [ ] Load data into biocache-databox and finalise with TERN
- [ ] Rerun from source API into databox to ensure that UUIDs are consistent between loads
- [ ] Set up load script in production and run a full load and ingest. Check data after the overnight index process
- [ ] Note the statistics for new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
**QA**
- [ ] Wait overnight for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNNN

**Comment by rosemaryjoconnor** [comment]
TERN- still waiting for update of HTTP for site links etc...

**Comment by rosemaryjoconnor** [comment]
HTTP redirects to new server implemented. Waiting for metadata from TERN to finalise dataset

**Comment by rosemaryjoconnor** [comment]
TERN has come back indicating data updates for scientific name to reduce excluded records based on scientific name. They have also indicated a number of other exclusion parameters  - see below. I have responded that the exclusion logic needs to be via the API not our data upload. 
Full email thread will be attached on issue completion. 

From Donna Lewis
The following categories should be excluded. This won’t change, and going forward we will eventually have better tools for herbarium determinations i.e. constrained to NSL for vascular plants at the source.

 

Dead Tree/Shrub
NO ID
Indeterminate
Standing Litter
 

The following non-vascular records should also be excluded.

Bryophyte sp.
Fungi sp.
Liverwort sp.
Moss sp.
 
Thanks for the update on Scientific Name matching. Once we have omitted ‘sp.’ from family and genus level determinations, these records should resolve in the ALA.

**Comment by rosemaryjoconnor** [comment]
Databox - dr18508
Prod - dr19843

**Comment by peggynewman** [comment]
Waiting for TERN to update http links in linked data API in the new year.

**Comment by rosemaryjoconnor** [comment]
No update from TERN to date. Will email

**Comment by rosemaryjoconnor** [comment]
Donna Lewis responded. She will update week of 13/02/2023 after speaking with Devs in Adelaide

**Comment by rosemaryjoconnor** [comment]
Response from Donna Lewis 23/03/2023:

Our team are currently in the process of making edits and bulk updates at the source. I will certainly be in touch when it is completed. BUT, first I will test it has all flowed through to EcoPlots to ensure when the ALA hits the EcoPlots API, the data is updated.
