### ISSUE TITLE
ALA data set uploader

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#8]
Data sets submitted via the Data set uploader

**Comment by charvolant** [comment]
Loaded Yugul Mangi rangers Wanmarri data (#66)

**Comment by charvolant** [comment]
Attempted to contact Tasmanian Flora address but bounced

**Comment by charvolant** [comment]
Sent query to Mulbring birds

**Comment by charvolant** [comment]
Sent query to ANPS

**Comment by charvolant** [comment]
Sent query to Sydney Flatwings

**Comment by charvolant** [comment]
Sent query to Welford NP and Cunnamulla

**Comment by charvolant** [comment]
Sent query to BP records

**Comment by charvolant** [comment]
Sent query to MyRiveR Coffs Creek Bird sightings

**Comment by charvolant** [comment]
Sent query to Lipson Cove

**Comment by charvolant** [comment]
Loaded Mulbring birds (#58)

**Comment by charvolant** [comment]
Loaded Syney Flatwings (56). Suggested change to CC-BY.

**Comment by charvolant** [comment]
Loaded ANPS data (55, 57)

**Comment by charvolant** [comment]
Sent query to Spny Rush (44). Email bounces, trying alternate name listed on the survey.

**Comment by charvolant** [comment]
BP records (52) now uploaded via Eremaea/eBird. Not processing.

**Comment by charvolant** [comment]
Spiny Rush (44) dataset uploaded to http://collections.ala.org.au/public/showDataResource/dr2147

There is an additional weed dataset available that will be mailed directly.

See also #64 which came up in conversation.

**Comment by charvolant** [comment]
Sent query to Birds observed at Bellbird Nature Refuge (46)

**Comment by charvolant** [comment]
Bellbird Nature Refuge (46) has been uploaded manually.

**Comment by charvolant** [comment]
Loaded Tallaganda Orchids (54) to http://collections.ala.org.au/public/showDataResource/dr2150

**Comment by charvolant** [comment]
Sent query to Frogs list (45)

**Comment by charvolant** [comment]
Sent query to Opuntia* and Drosophila* (38-44) with an eye to combining the datasets

**Comment by charvolant** [comment]
Most of Frogs list (45) has been entered as individual sightings. Requested that the last three remaining records be entered in directly.

**Comment by charvolant** [comment]
Loaded Opuntia and friends to sandbox for checking

**Comment by charvolant** [comment]
Sent query for JD1 (37)

**Comment by charvolant** [comment]
Sent query re Odonata observations

**Comment by charvolant** [comment]
Sent query re Karinga Flora and  Jervois flora survey

**Comment by charvolant** [comment]
Sent query re Holmesglen student assignment

**Comment by charvolant** [comment]
Karinga Flora and Jervois flora survey already uploaded to http://collections.ala.org.au/public/show/dr928

**Comment by charvolant** [comment]
Odonata observations has replied with a new dataset with catalogue numbers. Data is already loaded in http://collections.ala.org.au/public/show/dr692 Querying whether it's acceptable to simply delete and reload the data.

**Comment by charvolant** [comment]
Working on Country Program already loaded into http://collections.ala.org.au/public/show/dr739

**Comment by charvolant** [comment]
Sent query to Emuvale Species list

**Comment by charvolant** [comment]
Re-loaded Odonata observations. Will re-load to re-map images later.

**Comment by charvolant** [comment]
Re-loaded Odonata with images. Sensitive species are having dates fuzzed as well as location.

**Comment by charvolant** [comment]
That's about it for this one. There haven't been any responses to queries for a while and the more detailed sources have been moved to other issues.
