### ISSUE TITLE
Delete duplicate data request - 12 MV records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#800]
Reported in https://support.ehelp.edu.au/a/tickets/149135

Please could the following 12 MV records be deleted? They have been identified as duplicates:
 
F305012 https://biocache.ala.org.au/occurrences/698b1090-384f-4b3a-bd0e-b6eb51771e70
F305013 https://biocache.ala.org.au/occurrences/ecb0c86e-f262-4a66-8980-18da4866c111
F305014 https://biocache.ala.org.au/occurrences/691bef01-ae03-47ce-b73d-06d6697cf2fd
F305015 https://biocache.ala.org.au/occurrences/ef49473a-c4c7-4397-b855-0496ce909c77
F305016 https://biocache.ala.org.au/occurrences/7d91f2a9-1ebc-4705-a192-0cf71fe7eb15
F305017 https://biocache.ala.org.au/occurrences/7359bcad-ef8c-48ba-b6b2-d645055c4d6a
F305018 https://biocache.ala.org.au/occurrences/355a40e0-aa25-4261-98e8-d6943209a7fe
F305019 https://biocache.ala.org.au/occurrences/3220b3c8-fb2a-4f88-ac6c-d7be50f1c9ff
F305020 https://biocache.ala.org.au/occurrences/952fd97a-0979-4613-9501-74bf87b87850
F305021 https://biocache.ala.org.au/occurrences/518a5099-bf21-49ab-8a40-e54e521adbc5
F305022 https://biocache.ala.org.au/occurrences/7bb28490-4389-4d98-809f-7a0d5fda6489
F305023 https://biocache.ala.org.au/occurrences/c469d64d-be53-4f87-8d9e-97ccbb4020ab

**Comment by sadeghim** [comment]
They are deleted now!
