### ISSUE TITLE
Track daily data resource counts

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#804]
We need to keep track of DR counts every time we load a new index, so we can see daily movements but also use for metrics reporting.

**Comment by djtfmartin** [comment]
A simple solution for this that could be a jenkins script or airflow script that:

1) Downloads record count using the biocache-service facet download
2) Pushes the CSV into a git repo

You can then use the github UI to see the difference day-to-day.

As an added bonus, it would be nice if it only pushed to the github repo if something had changed.
