### ISSUE TITLE
Remove location data from 3 CANB records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#805]
From https://support.ehelp.edu.au/a/tickets/152052:

"There are three herbarium specimens I sent to the National Herbarium either late last year or earlier this year which were collected as part of site assessment work undertaken by the Biodiversity Conservation Trust on private properties and which have since been included in the Atlas of Living Australia with locality data fully visible. As these plants occur on private lands for which we did not negotiate making public the locality data, I need to request that the latitude and longitude data and the locality data (in particular the station name) is removed from the following ALA records:
CANB:CANB 952604.1 Rhaphidospora bonneyana
CANB:CANB 952605.1 Acacia petraea
CANB:CANB 952602.1 Maireana cheelii"

I've advised the user to request CANB remove these details in their source data, but that we will make the changes locally for now as this is a sensitive data issue. The 3 records are linked in biocache below:

CANB 952604.1: https://biocache.ala.org.au/occurrences/e3d71374-a07f-4b02-acb3-2cd016b3c036
CANB 952605.1: https://biocache.ala.org.au/occurrences/8e23cdec-0751-4cdf-957c-ac32e20c60da
CANB 952602.1: https://biocache.ala.org.au/occurrences/f5fc00ff-716c-4ff7-a24b-80d7c987e73a

**Comment by charvolant** [comment]
Built new DwCA with location generalised to 1 degree lat/long (100km) since the stations around there are pretty big.
Ingested new DwCA in pipelines.

This resource is updated weekly, so the changes will not remain seven days from now.

**Comment by peggynewman** [comment]
none of these catalogNumbers exist nor those biocache UUIDs. closing.
