### ISSUE TITLE
Remove MV Palaeontology records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#807]
From https://support.ehelp.edu.au/a/tickets/150129:

Please could the Palaeontology records assigned to MV be removed?:
 
https://collections.ala.org.au/public/show/co237
 
Since the project that put them in is no longer running and MV didn’t provide them and can’t update them we’d like to remove them please.

**Comment by charvolant** [comment]
Requires removal from

https://collections.ala.org.au/public/show/dr2342
https://collections.ala.org.au/public/show/dr2289
https://collections.ala.org.au/public/show/dr2290

**Comment by peggynewman** [comment]
The 3 data resources have been removed. Closing.
