### ISSUE TITLE
Date fix on dr689 - NSW South Coast & ACT plants  

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#809]
Approx 1500 dates in this DR are no longer being parsed, I think because the date parser can't make sense of dd/mm/yyyy if dd <=12. 

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr689
 
Get the input DwCA from HDFS, update the date field to yyyy-mm-dd format and reload the dataset.

Are there any other DRs this issue has major impacts for?

**Comment by timhicks-ala** [comment]
Reported in https://support.ehelp.edu.au/a/tickets/153914

**Comment by rosemaryjoconnor** [comment]
Date fix complete. Dataset not yet reloaded due to UUID update issue

**Comment by rosemaryjoconnor** [comment]
Data upload complete. No response from Betty Wood so dataset has been uploaded to production.
