### ISSUE TITLE
DR1010 ClimateWatch - Data mapping, analysis and load

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#812]
ClimateWatch has changed how they get sightings from users.

https://collections.ala.org.au/public/showDataResource/dr1010

Their old data is here, which needs some cleaning: https://collections.ala.org.au/public/showDataResource/dr1010

New data is coming from the new system (I'll email a spreadsheet). This needs to be mapped. This spreadsheet will not be loaded, but the new data will probably be in the same format.

- clean up the HDFS DwCA such that it's readable
- map the new data to DwC, in alignment with the old data

Then we'll work out next steps with ClimateWatch.

**Comment by peggynewman** [comment]
create a new data resource by choosing edit on the ClimateWatch data provider : https://collections.ala.org.au/public/show/dp2048

Upload the new records from Anna into the new data resource, in databox, for demo. With validation level of 3 and above.

**Comment by cha801p** [comment]
Records are available here: https://biocache-databox.ala.org.au/occurrences/search?q=data_resource_uid%3Adr18597&qualityProfile=ALA&disableQualityFilter=scientific-name#tab_recordsView 
However, these records are getting excluded based on the scientific name quality. 

This has been conveyed to the data provider and waiting for a reply.
