### ISSUE TITLE
Fix DR689 NSW South Coast & ACT plants 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#815]
Betty is saying that there are some problems filtering by dates. Looking in the data there are many dates in the raw data with formats that aren't parsing. 

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr689

* fix dates - there are a lot of different date formats
* fix some of the identifications using the user assertions that betty has created:  https://biocache.ala.org.au/occurrence/search?q=data_resource_uid%3Adr689&disableAllQualityFilters=true&qualityProfile=ALA&fq=user_assertions%3A%2250005%22
* fix the identifiers in the datasets. current identifiers in the collectory are nonsense:

`Darwin core terms that uniquely identify a record: | eventDate, scientificName, verbatimLatitude, verbatimLongitude, verbatimCoordinates, decimalLatitude, decimalLongitude`

create new consistent identifiers. once the user assertions are dealt with, we will just create new UUIDs for the dataset. ensure this has limited impact on images before proceeding to production.

**Comment by rosemaryjoconnor** [comment]
- New dataset has been created. 
- Dates fixed.
- Created new identifier occurrenceId
- Fixed species names for assertions.
To do: mapping images to records with new identifiers.

**Comment by rosemaryjoconnor** [comment]
Data has been loaded with new UUIDs, occurrencID is the identifier. 
Betty Wood has been contacted via the freshdesk job, but no response as yet.

**Comment by rosemaryjoconnor** [comment]
Data upload complete. No response from Betty Wood so dataset has been uploaded to production.
