### ISSUE TITLE
Lake Macquarie Ecosystem Monitoring

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#816]
Check the following datasets for suitability for ingestion as occurrence and/or events. 

FEDERAL site (DATA.GOV.AU):
 
CEMP
‘Community Ecosystem Monitoring Program – Terrestrial – Lake Macquarie City Council’ ... https://data.gov.au/search?q=Community%20ecosystem  (provides both data and relevant PDFs)
 
FRESHWATER CATCHMENT
‘Freshwater Catchment Ecosystem Health Scorecards –https://data.gov.au/search?q=Freshwater%20catchment
 
NSW site (DATA.NSW.GOV.AU) – ALL PERFECT 😊 ü  yay ... portal provides:
 
Lake Macquarie Community Ecosystem Monitoring Program – Terrestrial               (data, procedure & methodology)
Lake Macquarie – Freshwater Catchment Ecosystem Health Data                               (data & scoring guidelines)

**Comment by peggynewman** [comment]
Emailed another spreadsheet 22/12/22

**Comment by rosemaryjoconnor** [comment]
Just need to complete events.csv with correct structure for template to send

**Comment by rosemaryjoconnor** [comment]
Completed events/occurrence/measurementOfFacts CSV files.
