### ISSUE TITLE
Move Birdlife Seabird Atlas to BIrdlife Data Provider

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#817]
move:
dr7452 from dp54 to dp28
Sea Bird Atlas: https://collections.ala.org.au/public/show/dr7452
CSIRO data partner: https://collections.ala.org.au/public/show/dp54
BirdLife data partner: https://collections.ala.org.au/public/show/dp28
 
Also, I think it would be great if we could empty out dp54, and move all of the DRs to Dave’s OBIS DP.
The only problem I can see there is if any of them have gone to GBIF. If they have, we may need to check that GBIF metadata will still be ok.

**Comment by patkyn** [comment]
dp54 drs now moved to dp5183.

[dp54-drs.txt](https://github.com/AtlasOfLivingAustralia/data-management/files/9612673/dp54-drs.txt)
