### ISSUE TITLE
Daily DR counts

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#818]
Keep a log of daily dr counts somehow - download this file weekly and put a datestamp in the filename

https://biocache-ws.ala.org.au/ws/occurrences/facets/download?q=*%3A*&facets=data_resource_uid&count=true&lookup=true

**Comment by cha801p** [comment]
Set up a Jenkins job for weekly dr counts: /job/Data-scripts/job/weekly_dr_count/
