### ISSUE TITLE
Image load problem for dr345

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/data-management#832]
Images are loaded on the image server but not linked to records. 
Reason: Change in URL (identifiers) 
From- https://cloudstor.aarnet.edu.au/plus/s/k2jAWzT6g6l7oyL/download?path=%2F&files=ZOO_QVM-2017-12-0379.jpg 
To- https://fmpweb.qvmag.tas.gov.au/images/ZOO_QVM-2017-12-0379.jpg

**Comment by patkyn** [comment]
Updated the image records with the new url.
