### ISSUE TITLE
Set up iNaturalist extracts 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#836]
Set up iNaturalist exports in S3 using the December export (see directory in S3) as previously done for Tasmania.
We need these for Tas, Qld and National.

Let me know when they're ready and I will provide contact names for each.

Share the notebook that does this work on a private repo in GH, but at the same time we need to ensure no sensitive data is stored on GH. We can discuss this. Perhaps we should just maintain the notebook in S3.

**Comment by peggynewman** [comment]
Closing this, superceded by https://github.com/AtlasOfLivingAustralia/preingestion/issues/105

**Comment by peggynewman** [comment]
Reopening this issue, as it belongs in the data-management repo, and closing the issue in preingestion instead.

@cha801p I've created a notebook to do this, which generates a report on the counts that need to be sent to people who request access to this data

https://github.com/AtlasOfLivingAustralia/databox/tree/master/inaturalist-sensitive-exports
See https://confluence.csiro.au/display/ALASD/iNaturalist+Sensitive+Observation+Data

Still some work for you to do to empty private_ fields and create individual archives for all states and territories, and load them into S3.

**Comment by cha801p** [comment]
Sent data to **Simon Gorta** _s.gorta@unsw.edu.au_ on May 3rd 2023 (10AM) for ACT and NSW.

**Comment by cha801p** [comment]
Sent data to Simon Gorta [s.gorta@unsw.edu.au](mailto:s.gorta@unsw.edu.au) on May 4th 2023 (1PM) for ACT and NSW **with updated taxo information.**

**Comment by peggynewman** [comment]
Notebook still to be pushed to GH

**Comment by peggynewman** [comment]
File loading into S3 now - these exports are to be set up for 202306

**Comment by cha801p** [comment]
**Ticket Update:** 4 September, 2023 (4:30 PM)

**Issue Identified:** Set up iNat Extracts

**Resolution:** State-wise csv and zip files created and uploaded on s3 bucket

**S3 location:** /202306/output/

**Next step:**Waiting for the next update from Peggy after communicating with Cam

**Comment by cha801p** [comment]
**Ticket Update:** 4 October, 2023 (5:30 PM)

**Issue Identified:** Set up iNat Extracts

**Current Status:** State-wise CSV and zip files were created and uploaded to the S3 bucket

**S3 location:** /202306/output/

**Steps Taken:** 

1. Received an email from the Tasmania data requester on 3rd October, 2023
2. Draft email sent to Cam, Peggy, and Mahmoud with Data download link

**Next step:** 

- [ ] Waiting for the next update from Peggy and Cam

**Comment by cha801p** [comment]
**Ticket Update:** 14 December, 2023 (3:00 PM)

**Issue Identified:** Set up iNat Extracts

**Current Status:** State-wise CSV and zip files were created and uploaded to the S3 bucket

S3 location: /202306/output/

**Steps Taken:**
Peggy has emailed the data requester


**Next step:**
Waiting for an update from Cam/Appropriate Expertise

**Comment by peggynewman** [comment]
Waiting on me to discuss this with Cam

**Comment by peggynewman** [comment]
Superceded by https://github.com/AtlasOfLivingAustralia/data-management/issues/1008
