### ISSUE TITLE
VBA data load

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#838]
Update the VBA dataset with new data from:
https://discover.data.vic.gov.au/dataset/?sort=score+desc%2C+metadata_modified+desc&q=biodiversity+taxa&organization=&groups=&res_format=

**Comment by rosemaryjoconnor** [comment]
VBA data loaded into Databox. Data checks looking good. 
Upload to uploads server is failing due to space issues. Matt is looking into it

**Comment by rosemaryjoconnor** [comment]
VBA finally succeeded in Jenkins preingest load dataset.  It took a few hours, will check first thing tomorrow re the index etc.... Patricia helped out, first of all got rid of the job trying to run the VBAFetcher and then sorted out the Jenkins permissions etc... that had been revoked.
