### ISSUE TITLE
Insect Investigators Data Load

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#839]
Create an ongoing data load for this project from BOLD. At the same time, look into other Australian datasets on BOLD. Check with Nick/ARGA how they are loading/processing.

webpage: https://insectinvestigators.com.au/

The BOLD project ID is ASMII – data is already public so can be accessed from the Workbench section of BOLD by searching for the project code, or without logging in you can find the records in the more public-facing site: https://www.boldsystems.org/index.php/Public_SearchTerms?searchMenu=records&query=ASMII&taxon=

There’s 14,060 specimens, and 13097 COI barcode sequences (but about 500 of those sequences are flagged as problematic records/contamination, so shouldn’t be used further).

**Comment by peggynewman** [comment]
Sent email.

**Comment by cha801p** [comment]
Loaded the data on Databox. Testing in progress.

**Comment by javier-molina** [comment]
@cha801p let's talk about the format of this dataset and what we already have from Bold: https://biocache.ala.org.au/occurrence/search?q=*%3A*&qualityProfile=ALA&fq=data_resource_uid%3A%22dr375%22

**Comment by peggynewman** [comment]
We could use the BOLD API: https://www.boldsystems.org/index.php/resources/api?type=webservices

**Comment by peggynewman** [comment]
Notebook for ARGA https://github.com/ARGA-Genomes/arga-data/blob/develop/jupyter/notebooks/iBold-file-import.ipynb
Could be useful to update dr375

**Comment by cha801p** [comment]
Emailed data provider re data load:
https://collections.ala.org.au/public/show/dr22303
