### ISSUE TITLE
Authoritative Lists Management

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#841]
Develop strategy for ongoing list maintenance including:
- quarterly list updates
- monitoring of list updates
- recording of date of most recent list updates
- clarification of list sources

- update of Github documentation - Authoritative List repository
- checking if notification of list changes by stakeholders is possible

**Comment by peggynewman** [comment]
List updates went in this week. We should probably have a look at doing updates again in November.
Closing this now.
