### ISSUE TITLE
dr341-dr349 Aust Nat Wildlife & Fish Collections

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#843]
Meeting with Corinna went well. There are issues on their side impacting capability to rework their data processes. 
On hold until Peggy gets back.

**Comment by rosemaryjoconnor** [comment]
As per emails 27/10/2022 ANWC Rob van Heuzen was sent DWCA for dr341 and dr349. There has been no response to date regarding new dataset.
Emailed for information/update 06/02/2023. No response to date. 
Contacting Corrina Paeper today

**Comment by peggynewman** [comment]
Edited the description

**Comment by rosemaryjoconnor** [comment]
Following meeting with Corinna, Peggy to follow up.

**Comment by peggynewman** [comment]
Met with Rob  on 4 April, they are still prepping the extract. Closing this until we hear from them again.
