### ISSUE TITLE
dr343 - MAGNT  Dataset upload

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#844]
MAGNT wants to upload a new dataset but was unsure of process. 
Notified to upload to upload server and we will check the data that comes through. 
Sue Horner is the contact

**Comment by rosemaryjoconnor** [comment]
Sue Horner is still having access issues.
I tested her credentials via WinSCP and there is no problem there.
Have advised that she take a look at her ftp client etc... and sent her settings I used to assist.

**Comment by rosemaryjoconnor** [comment]
Sue Horner has had her IP address whitelisted and can now upload. 
The new dataset is available

**Comment by rosemaryjoconnor** [comment]
First look at the dataset. One character encoded incorrectly, even though it gives the offset, nothing seems to be showing so have set encoding_error='ignore' and all seems ok.
There are 2 duplicate catalogNumbers, have emailed Sue for correction

**Comment by rosemaryjoconnor** [comment]
MAGNT replied, duplicates now updated and new occurrences file created. Waiting for databox and Production to be stable before loading

**Comment by peggynewman** [comment]
Done https://collections.ala.org.au/public/show/dr343

**Comment by rosemaryjoconnor** [comment]
Sue Horner has advised that there will be future updates. Full datasets will be uploaded.
