### ISSUE TITLE
Load Redmap into databox from AODN

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#846]
Redmap data is in AODN. Eventually we will also harvest ReefLife Survey from AODN as well. Work out how to pull and convert the data to DwC. If we need to consult with the data provider, call on Andrew/Erin for a contact. Let's see the data in Databox but we should check in with the data provider before going live as a matter of courtesy.

**Comment by peggynewman** [comment]
Redmap data is in AODN. Eventually we will also harvest ReefLife Survey from AODN as well. Work out how to pull and convert the data to DwC. If we need to consult with the data provider, call on Andrew/Erin for a contact. Let's see the data in Databox but we should check in with the data provider before going live as a matter of courtesy.

**Comment by cha801p** [comment]
-Loaded the data on databox
-DynamicProperties not showing up and needs an investigation

**Comment by cha801p** [comment]
-This has been raised further: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/787

**Comment by peggynewman** [comment]
In test here: https://collections-test.ala.org.au/public/show/dr18714
Needs
- license
- basis of record

I emailed Peter W (Redmap Data Manager) about this 04/04

**Comment by cha801p** [comment]
https://collections-test.ala.org.au/dataResource/show/dr18714

**Comment by peggynewman** [comment]
Still waiting to hear back from Peter W

**Comment by peggynewman** [comment]
Can script this using the WFS call to AODN

collection_url = "https://geoserver.imas.utas.edu.au/geoserver/redmap/wfs?typeName=redmap:RM_SIGHTING_VIEW_DATA&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(GEOM%2CPOLYGON((91.494140625%20-49.3955078125%2C91.494140625%20-3.7802734375000036%2C175.25390625%20-3.7802734375%2C175.25390625%20-49.3955078125%2C91.494140625%20-49.3955078125)))&userId=Guest"

**Comment by peggynewman** [comment]
We can't use FID as the unique identifier for this dataset - whenever AODN reload their datasets into the geoserver, the FID changes. We need to use the ID field as the occurrenceID.
