### ISSUE TITLE
ABARES dataset engagement

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/data-management#852]
At the ALA we have ingested a very old dataset about which a user has suggested there are some misidentified occurrence records evidenced by an incorrect distribution.
 
It was a Bureau of Rural Sciences (BRS) dataset, National Commercial Fisheries Presence 2000-2002.
We ingest it from here: [https://www.marine.csiro.au/ipt/resource?r=brs_2000_2002#anchor-description](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.marine.csiro.au%2Fipt%2Fresource%3Fr%3Dbrs_2000_2002%23anchor-description&data=05%7C01%7CKatherina.Ng%40aff.gov.au%7C4fddc0992a2d4148c59408db0e2be620%7C2be67eb7400c4b3fa5a11258c0da0696%7C0%7C0%7C638119353924723073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vGYyROyKAvM6jakNXr6mPxTWEERlKEAaa7u4Fgv0Zjo%3D&reserved=0).
 
I understand this is somehow related to ABARES. Do you know who we might be able to contact to source an updated dataset?

**Comment by peggynewman** [comment]
I chased this and there was no updated dataset.
