### ISSUE TITLE
FrogID Data  Refresh

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/data-management#855]
We need to source a FrogID data refresh

**Background**

Message from Kylie

> Hi data team, do we know when we might expect the data from FrogID week last year (Nov) to arrive in ALA? They've just posted about their stats from the week and it would be great to shout it out :slightly_smiling_face:

Response from Javier

Looks like we have a manual ingest for it and last time it was updated was in Nov 2020

[15:17](https://atlaslivingaustralia.slack.com/archives/CCURT5KAA/p1677557867581299)
We might need to add this to the list of datasets to refresh

**Comment by peggynewman** [comment]
Done
