### ISSUE TITLE
image loading issue for dr345

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/data-management#861]
-dr345 has 3,162 images on biocache, it has 3,248 images on [images.ala](https://images.ala.org.au/?fq=dataResourceUid:dr345), and the multimedia.csv from DwcA has 3,544 images.
Even after reingesting the dataset, there is still no change on biocache.
-It was found that there was a change in URL for 296 images
-Adam Collins deleted the unlinked images and no change has seen after ingesting the dataset again.

**Comment by cha801p** [comment]
Reloaded the data after checking if every identifier is linked to an occurrence
[images.ala](https://images.ala.org.au/?fq=dataResourceUid:dr345) now has the uploaded images
Count has changed from 3,248 to 3,539 images
This shall reflect tomorrow after full-index
Emailed the data provider the same
