### ISSUE TITLE
Mark problem lists as private

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#865]
Using a MYSQL query on the lists  to bulk update the following lists as private:

* 29 Lists with zero records 
* 3788 lists with 1 record (many duplicates) 
* 227 lists marked with list type – “Test list” (48 of these are public) 
* 191 lists NOT marked with list type “Test list” with the word test in the list name (59 of these are public) 

write the query, create a temp table to keep a copy of the data, apply the update then remove the temp table after testing.

@TaniaGLaity are there other bulk operations you'd recommend?

**Comment by TaniaGLaity** [comment]
- there are 70 lists for which owners are no longer have a registered account with the ALA - these could be ones that could be deleted too (if they don't have the authoritative flag)?
- there are 78 lists owner by users with locked accounts - these could either be deleted or made private too

all others would need more consideration I think

**Comment by rosemaryjoconnor** [comment]
Hi Peggy
I got slightly different numbers for these in Prod:

  *   29 Lists with zero records - 31 records
  *   3788 lists with 1 record (many duplicates) - 4107 of these
  *   227 lists marked with list type – “Test list” (48 of these are public)   - none with 'Test list' but 249 with  'TEST'
  *   191 lists NOT marked with list type “Test list” with the word test in the list name (59 of these are public) - got 94 in total all looked like they were public

I'll start on lists-test now and creation of temp table etc...
good to do something a little different!
chat soon
Rose
________________________________
From: Peggy Newman ***@***.***>
Sent: 23 March 2023 15:39
To: AtlasOfLivingAustralia/data-management ***@***.***>
Cc: OConnor, Rosemary (NCMI, Dutton Park) ***@***.***>; Assign ***@***.***>
Subject: [AtlasOfLivingAustralia/data-management] Mark problem lists as private (Issue #865)


Using a MYSQL query on the lists to bulk update the following lists as private:

  *   29 Lists with zero records
  *   3788 lists with 1 record (many duplicates)
  *   227 lists marked with list type – “Test list” (48 of these are public)
  *   191 lists NOT marked with list type “Test list” with the word test in the list name (59 of these are public)

write the query, create a temp table to keep a copy of the data, apply the update then remove the temp table after testing.

@TaniaGLaity<https://github.com/TaniaGLaity> are there other bulk operations you'd recommend?

**Comment by peggynewman** [comment]
Those numbers look reasonable. Ensure that you don't change anything that is flagged authoritative. (authoritative records are indexed with the list ID in pipelines).

We should be able to intermittently run it as a clean up script.

Also those account related issues, might have to look in the user admin system for a list of user ids for those. Not sure exactly.

**Comment by rosemaryjoconnor** [comment]
Records updated in lists-test. Mysql raw scripts in github - authoritative-lists/source-code/scripts. 

- ala-lists-create-temp.mysql
- ala-lists-update.mysql
- ala-lists-check-updates.mysql

**Comment by peggynewman** [comment]
I can't see the scripts in GH ... but wonder why there are 3? Can you do multiple queries in one script?

**Comment by rosemaryjoconnor** [comment]
Odd they should be there. Ii'll check first up tomorrow. Only 3 now as I was testing bits separately. I intended to putt it all into one and comment it once sure it was fine.

The update is simple it was getting the other queries correct that I was being careful with

I was being super- cautious!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rosemaryjoconnor** [comment]
Ok so I couldn't leave it! I had done the commit forgot to push... done now.
________________________________

**Comment by TaniaGLaity** [comment]
lists in test look heaps better -got rid of a LOT of junk!  

still need to make ones that have *test* in the List Name private too

Also had another idea for marking some private - can you de-duplicate lists? e.g. where they have the same name, type, owner, date submitted and date updated and item count - make all but one private?

**Comment by rosemaryjoconnor** [comment]
Hi Tania
Thanks for looking at those so quickly.
Re:

  1.  still need to make ones that have test in the List Name private too - ah I can see the bug in the sql I will get that fixed.
  2.  de-duplicating: I will have a look at how to do that asap. Should be do-able!

thanks
Rose


________________________________

**Comment by rosemaryjoconnor** [comment]
Hi Tania
Just taking a look at the de-dup logic. It is do-able of course however, using the date updated may not be particularly useful as this gets updated even if a typo in a name in metadata or anything changes. So it could be changed on one duplicate but not on another. Doug is in the process of adding another field, a date loaded which will indicate when the data was last loaded, I think this would be more useful to include when it is available.

In the meantime I see what I can pull out and get things in place.

thanks
Rose
________________________________

**Comment by peggynewman** [comment]
Hey Rose, I think that just retaining the one with the last date updated, even in the metadata, is probably fine to go ahead with. My suspicion is that most of these are not high quality lists any way. 
Got a few examples:
[fire names 2v](https://lists.ala.org.au/speciesListItem/list/dr7854)
[fire names 2v](https://lists.ala.org.au/speciesListItem/list/dr7855)
[Flora of the Sydney Basin Region](https://lists.ala.org.au/speciesListItem/list/dr8039)
[Flora of the Sydney Basin Region](https://lists.ala.org.au/speciesListItem/list/dr8038)

**Comment by peggynewman** [comment]
This is with Dave, will wait till finished

**Comment by djtfmartin** [comment]
I've ran these scripts. In addition i ran the following: https://gist.github.com/djtfmartin/551e632d75679b574bdc037abaa79208

Im closing this issue. we can createnew issue(s) with problem lists once they are identified

**Comment by TaniaGLaity** [comment]
@checksfields this is the ticket and link to script for Dave's cleaning up of lists . Amanda doesn't appear to be able to access this git hub repository
