### ISSUE TITLE
Eurobodalla Regional BotanicGardens

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#87]
Data set to review and load
Possibly to be added to AVH but not yet

**Comment by M-Nicholls** [comment]
loaded to sandbox, waiting on feedback from the herbaria and text for the collection page

**Comment by M-Nicholls** [comment]
loaded into public ALA, waiting on feedback and data set description

**Comment by nielsklazenga** [comment]
At their meeting last week, CHAH has agreed that, with Eurobodalla Regional Botanic Gardens having registered with Index Herbariorum, all conditions for inclusion in AVH have been met.

Could you organise hooking up the ERBG data source to be hooked up to the AVH hub? I think they still need a Collectory page as well.

@elywallis found some issues with the data back in March, in particular the lack of basisOfRecord, so it would be good if a new data load could be organised as well.
