### ISSUE TITLE
2x record deletion request - entomology records with incorrect name

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#872]
From https://support.ehelp.edu.au/a/tickets/174389

Could we please have the following records deleted:
 
https://biocache.ala.org.au/occurrences/30403b42-84d9-47b4-b46e-7272ba03ec90
 
https://biocache.ala.org.au/occurrences/4deb6bc3-f8da-4468-a2f4-bcabb3ef2bbc
 
They have the wrong name attached to them.

**Comment by peggynewman** [comment]
FYI @sadeghim AM are asking to remove 2 records from their DwCA. Their harvest is currently broken and they don't want to wait to fix these.

**Comment by cha801p** [comment]
Above records have been deleted. Record count: **1,560,993 records**

https://biocache.ala.org.au/occurrences/30403b42-84d9-47b4-b46e-7272ba03ec90 
https://biocache.ala.org.au/occurrences/4deb6bc3-f8da-4468-a2f4-bcabb3ef2bbc
