### ISSUE TITLE
#174738 dr689 - NSW South Coast & ACT Plants

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#875]
Freshdesk: [#174738]  https://support.ehelp.edu.au/a/tickets/174738

Betty Wood would like: I need to alter the identification of a record which I had identified as
Pterostylis parvifolia. It is actually Pterosylis rubescens

Have found this in dr689 but there are 9 occurrence records so will need to respond and have them indicate which record.

**Comment by rosemaryjoconnor** [comment]
FYI : Betty and Don Wood have another DR also:  dr691 - Plants of Scotia Sanctuary

**Comment by rosemaryjoconnor** [comment]
Betty Wood emailed

**Comment by rosemaryjoconnor** [comment]
Betty has replied and identified the single record to update. I've updated and will load the dataset asap.
She was also looking for another dataset from the Bush Heritage group for Carnarvan Station Reserve. Found at:  https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1030

**Comment by sadeghim** [comment]
Done!
