### ISSUE TITLE
Remove co115 (MV Arachnology)

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#879]
The Mueseum Victoria Arachnology Collection has been folded into the Entomology collection, and so our collectory page for this collection is redundant: https://collections.ala.org.au/public/show/co115

We've been asked to remove it: https://support.ehelp.edu.au/a/tickets/160983 (email dated 3/5/23)

**Comment by peggynewman** [comment]
Just emailed MV to ask about this and the Vertebrate Paleantology collections

**Comment by peggynewman** [comment]
sorted.
