### ISSUE TITLE
Improved download interface

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#9]
interface to allow field selection from full set of fields - index, QA and additional fields
saving of default set of fields
allow addition of un-sensitised values where appropriate permissions exist
placing export file in an accessible location
functionality to facilitate automation

**Comment by M-Nicholls** [comment]
allow selection of header as DarwinCore where available

**Comment by Tasilee** [comment]
Recent playing with Sandbox suggest to me that it is VITAL that exported data records (biocache or Sandbox) use the exact Darwin Core terms (camelCase etc) as column headers where appropriate. 

It is not a good look if exported records cannot be 100% determined on any re-import to Sandbox. That is, it is bad if the exported column headers are not recognised on re-import to Sandbox and these headers are not formatted to the Darwin Core term.

**Comment by M-Nicholls** [comment]
format options:
csv, tsv, JSON

probably worth reviewing what's in the license file as well
images?

**Comment by Tasilee** [comment]
I'd be thrilled with even CSV, as I suspect would most others, but JSON seems logical as well as priority 2.

Licence file is well worth a review. Images? None in download as such.

**Comment by M-Nicholls** [comment]
A download from cassandra looks to cover all required fields from the index as well as those not indexed.

use a single download interface to select fields, up to 100k instantaneous export from the index (restricted field list), over 100k or full field list from the cassandra database

Options for field groups
o	Raw values (of DwC classes)
o	Processed values (of DwC classes)
o	DwC classes - record-level (always), occurrence, organism, materialSample (specimens), event, location, geologicalContext, identification, taxon, measurementOrFact, resourceRelationship, other DwC extensions as added (multimedia, tissues,...)
o	Miscellaneous properties (miscProperties)
o	QA checks (includes duplicate detection)
o	Contextual layers
o	Environmental layers
o	AssociatedMedia
for future development:
o	Full resolution values – request permission, agree to terms of use


performance considerations:

implement after hours download?
queue to restrict number of active downloads?
download from a replicated cassandra?

fix up the index download as per previous comments around header and licensing file:
use
darwinCoreFieldName_raw
darwinCoreFieldName
as the naming convention if both the raw and processed fields are present in the download

Complete messages.properties info: 
(https://github.com/AtlasOfLivingAustralia/biocache-service/blob/f697e43f03cd82ec5326cd474a74ad4669d76878/src/main/webapp/WEB-INF/messages.properties )

field descriptions and links to darwinCore definition
should #download field names be used at all? If so review and update for consistency
darwincore field list (for  the index) 
Add QA check descriptions from https://docs.google.com/spreadsheets/d/1ayiiBxAFhy5bpeMUHOF1nyOP6yaYv1F_f8DvtLoeRx8/edit#gid=0

**Comment by Tasilee** [comment]
Thanks Miles

Looks good except that I wouldn't by default bother with the *contextual
and environmental sample values*. There is obviously some overlap between
Darwin Core and some layers such as State/Territory (contextual) and
elevation (environmental) but most would not be relevant. An option to
append all layer values would be useful.

*Associated media*: Yes, and a good example of the need to flag that
related information is available. Other examples - sequences, systematic
survey link etc.

*Download field names*: These really must be (spelled as) darwinCore when
available. When not, we must be consistent, everywhere! This raises the
issue of the *non DwC field descriptions* - which require serious
attention. I am happy to help, but in many cases, either code or a relevant
developer may need consulting. In short, we need at least a decent
(two-level as like Darwin Core) vocabulary.

QA checks? I like the term *assertions*. My research suggests the ALA has
the most comprehensive set, but some descriptions are iffy. There needs to
be an obvious option for including *all* (download could be the first place
users will hit assertions) or only ones that have a TRUE state. The better
the assertions, the more likely users will be able to determine fitness for
use.

*Performance*? The research community would be thrilled to  just get it,
regardless of any delays. That said, restrict active downloads to 1. Full
stop.

*Download fields*: I have added all the relevant Darwin Core fields to the
assertions in the spreadsheet I sent to TG2. I will be sending out an
update probably tomorrow.

Lee


Lee Belbin
Blatant Fabrications Pty Ltd
Tasmania
