### ISSUE TITLE
Temporary secondary backups

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#905]

**Comment by patkyn** [comment]
Weekly Secondary backups is currently backed up in ala-backup-biocache-src-data-production (s3 glacier storage).
for eg: 
![image](https://github.com/AtlasOfLivingAustralia/data-management/assets/1606595/b42d14bf-4814-493f-901b-dc47f9afa5bb)


Pending: documentation on restoring backup
