### ISSUE TITLE
Helpdesk # 152192 - dr22365 BRUVS Fish species

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#912]
https://support.ehelp.edu.au/a/tickets/152192

Our team here at the SA Museum took part in a bush blitz survey last year that produced some fish species records for the Great Australian Bight from video footage recorded via BRUVS. I can see that some of the fish species we’ve identified (via SARDI/PIRSA here in Adelaide) are rare or new records in the area to the ALA databases. I would like to be able to upload the sightings data to ALA, if possible to make the data publicly available. We don’t have collected items, just sightings from footage and so we are not able to upload them via the SAM Emu database uploads. Can you please let me know whether we can contribute the sightings data records and what format you might need them in. I currently have them in excel with all locality information.

**Comment by rosemaryjoconnor** [comment]
Revisiting today. No images to date. Will contact user.

**Comment by peggynewman** [comment]
There are some other BRUVs datasets around, have a look for DwCA examples

**Comment by rosemaryjoconnor** [comment]
Updated and loaded in databox - dr21695
Emailed user 12/07/2023

**Comment by rosemaryjoconnor** [comment]
Had to generate a unique catalogNumber. 

Used a combination of fields:

cdf['catalogNumber'] = cdf.index.astype(str) + '-' +  cdf['siteid'] + '-' + 'BRUVS-Bush-Blitz:' + '-' + cdf['year'] + cdf['month']  +cdf['day']

**Comment by rosemaryjoconnor** [comment]
dr22365 - preingest to Prod successful waiting on Index.

**Comment by rosemaryjoconnor** [comment]
Reopened as user has indicated they will still be hunting down some images to go with the data.

**Comment by rosemaryjoconnor** [comment]
Closing as no further response to date re images
