### ISSUE TITLE
BDBSA SA Flora and Fauna Files to ALA (06/23)

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#914]
The SA Department for Environment and Water has created an updated version of the SA Flora (BDBSA) and SA Fauna (BDBSA) records on the ALA FTP site.
Please update the datasets metadata with the month and year of this extraction - 06/2023

https://support.ehelp.edu.au/a/tickets/177457

**Comment by peggynewman** [comment]
@rosemaryjoconnor please note the request to make sure that the dates on collectory are up to date. This may need to be done manually.

**Comment by rosemaryjoconnor** [comment]
Finalising BDBSAFetcher.py. Will check collectory.

**Comment by rosemaryjoconnor** [comment]
New fetcher successfully run in databoxdev and databox.
Databox github updated with readme.md for BDBSA

**Comment by rosemaryjoconnor** [comment]
Have rechecked records in Prod vs databox
All seems ok except in Prod there is additional information.

- Additional political boundaries information
- Environmental sampling for this location

Is this just a prod vs test thing?

Example: 

https://biocache.ala.org.au/occurrences/079ef858-8ca7-4b92-8016-c5ec5fc77f13

https://biocache-test.ala.org.au/occurrences/079ef858-8ca7-4b92-8016-c5ec5fc77f13
