### ISSUE TITLE
Generate a DwCA name list directly from AFD data

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#92]
Use the raw AFD data to generate a suitable input to the names generator

Names generator https://github.com/AtlasOfLivingAustralia/ala-names-generator
Notes on name classification https://code.google.com/p/ala-portal/wiki/ALANameClassification

**Comment by djtfmartin** [comment]
Thanks @charvolant. Im hoping to make the ala-names-generator defunct.

The idea is that we can take archives of taxonomic information and pull them straight into the (new) BIE with no mangling beforehand. These archives would also be used to generate the name matching indexes using [ala-name-matching](http://github.com/AtlasOfLivingAustralia/ala-name-matching) library.

This is DwC-A format I've been working with for the new BIE:

https://gist.github.com/djtfmartin/fe6d3de741363011cc7e

We may need an additional extension for literature references, but Im hoping this information can retrieved via webservices, so no need for ALA to store and index. But we may need this extension for AFD for a while.

cc @nickdos

**Comment by charvolant** [comment]
@djtfmartin  Thanks for the format example. A few comments that are also implicit questions:

* The AFD has a separate name identifier for a name/author/year combination, which looks top me as if it corresponds to the scientificNameID term, rather than the acceptedNameUsageID. (John de la Salle has already shown me an example of somewhere where that doesn't work, as some nutter managed to describe a genus twice with different type species in the same year. However, in principle this could be extended so that they disambiguate.)
* As a side-note to that, the URL form of the AFD name identifier resolves properly. For example Mitra rosea (Reeve 1845) as a URL of http://biodiversity.org.au/afd.name/516443
* With the examples I've seen, there is also a synonym table of available names.
* There are a number of "interesting" cases, such as excluded names, miscellaneous literature names (mostly misidentifications), generic combinations, ... My instinct is that these will need special handling, since they represent edge cases in terms of how they're used for identification. To begin with, they can be incrementally added as separate files.
* There are tables for references and publications. I'll leave those for later, since it's got a fairly recursive structure.

In the short term, I'm interested in getting stuff from the AFD into a suitable format so that people can start discussing the more hairy bits with a concrete example in front of them. I'll use your format as a base.

**Comment by djtfmartin** [comment]
thanks @charvolant. This is really really good :)

parentNameUsageID should go in the taxa.csv with the template.
parentNameUsageID should be referring to the parent taxon (and I agree the name is a bit weird/off putting).

Excluded names, and misidentifications is something the ala-name-matching API has support for:

http://bit.ly/1c2joWU

I think the [DwC-A template in the gist](https://gist.github.com/djtfmartin/fe6d3de741363011cc7e) will need to be extended to include this information (and im not sure there is a DwC term for this so we'll have to come up with a name).

**Comment by nielsklazenga** [comment]
Sorry to butt in. The correct Darwin Core term for excluded names is [`occurrenceStatus`](http://rs.tdwg.org/dwc/terms/occurrenceStatus), see the [GBIF vocabulary](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml). Excluded names cannot be treated as a strictly taxonomic issue, as you need a spatial dimension as well. Excluded names in the ALA name list are excluded only from Australia, not the rest of the world.

On the second page of the cited query result I found two New Zealand records of moss taxa that are endemic to New Zealand:

![image](https://cloud.githubusercontent.com/assets/4694550/7717579/3b133320-fee7-11e4-9992-5bea9402d569.png)

I happen to know these taxa, but I don't think all ALA users will. This will be even more confusing when NZVH officially becomes part of the Atlas.

In the [GNA "star schema"](https://code.google.com/p/gbif-ecat/wiki/DwCArchive), `occurrenceStatus` is in a separate [Distribution extension](http://rs.gbif.org/extension/gbif/1.0/distribution.xml), along with [`locality`](http://rs.tdwg.org/dwc/terms/locality), which could be 'Australia', 'New Zealand', 'Papua New Guinea', etc. In AusMoss ([meta.xml](https://gist.github.com/nielsklazenga/c497ae9c4c21638c0e9a)), I have this information at both the state and country level. It doesn't really make sense at the taxon level to have `occurrenceStatus` but not `locality`.

**Comment by pmcneil** [comment]
looking at https://gist.github.com/djtfmartin/fe6d3de741363011cc7e the extension 'dataset' probably shouldn't have a rowType rowType="http://rs.tdwg.org/dwc/terms/Taxon"

**Comment by charvolant** [comment]
Notes from Anna about vocabulary

Peter also suggested I take a look at the glossary at https://github.com/AtlasOfLivingAustralia/ala-name-matching#understanding-the-name-matching-algorithm. Some comments follow.

•Cross Rank Homonym - A name that appears more than once at different ranks.

- I have never come across this concept. In the botanical code by definition homonyms have the same rank and a name does not have priority outside the rank at which it was published. CRHs seem to be a zoological thing, which might be worth stipulating.

 

•Excluded - An excluded concept is one that the NSL believes does not occur in Australia. This is only an issue if you are sure that the name you are matching on is in Australia.

- I think this should be “An excluded taxon...” but as I mentioned above, our “excluded” category covers doubtful, excluded and unplaced names. We don’t have three separate flag, one for each subcategory. We did discuss it at some point but I think we felt it was going to require more work and not add any greater certainty. Some are definitely excluded; some are in a limbo status. The comments in APC are what tells you which is which.

 

•Homonym - A name that has been publish more than once describing different species/genera.

- This should be “published”, I think? And I think homonymy applies to ranks other than just species and genera.

 

•Misapplied Name - A misapplied name is where a scientific name as been incorrect used in a publication to identify a species.

- This presumably should be ...“has been incorrectly...”? This isn’t a great definition, as misapplications can occur at ranks other than species. What about something like “A misapplied name is effectively a published misidentification, where a scientific name is incorrectly applied to material of a taxon that is subsequently shown to represent another taxon”?

 

•Phrase - The phrase component of a Phrase Name, generally indicating a location. See Phrase Name for more information.

- I am not sure I’d say “generally indicating a location”. Perhaps “often” and “collection locality”. However, it’s also acceptable to call something Grevillea sp. Big Leaves (A.B.Smith 3456) or even Grevillea sp. Magnifolia (D.C.Jones 3412) etc. etc.

 

•Phrase Name - An official scientific name that uses a phrase and optional voucher in place of a specific or infraspecific epithet. This type of name is generally assigned before an official name can be published. We need to consider them because we receive occurrence records using them AND more importantly they are included in official conservation lists.

Example of a phrase name:

Stylidium sp. Boulder Rock (A.H. Burbidge 2536)<br>

Genus = Stylidium<br>

Phrase = Boulder Rock<br>

Voucher = A.H. Burbidge 2536<br>

 

Here is a link to all the biocache records that have been matched to a phrase name:

http://biocache.ala.org.au/occurrences/search?q=*:*&fq=name_match_metric:phraseMatch

 

-There’s nothing particularly “official” about phrase names-- we only really categorise them as scientific in order to include the scientific portion (in the case of a species, the genus and so on). And saying they are “generally assigned” before publication kinda makes it sound like a necessary step. What about “A name that combines a scientific portion with a non-scientific suffix in place of a specific or infraspecific epithet. Phrase names are often used as ‘place-holders’ for entities believed to be new taxa that have not yet been formally described. We need to consider...”?

 

Point of interest-- where does the “sp.” part fit in? In APNI we enter it as part of the name element/epithet.

 

•Split Species - A species that has been split into a few subspecies. This results in the original species name becoming a synonym to the subspecies.

- This is incorrect, at least according to my understanding. Let’s say that if a species is split into say four subspecies. You can talk about the species as a whole (which encompasses all four) or you can talk about the individual subspecies, but the species itself does not become a synonym! Perhaps you are thinking of autonyms, where the publication of one or more valid and legitimate infraspecific taxa establishes an autonym that repeats the species epithet e.g. Grevillea dealbata Link subsp. dealbata?

•Voucher - The voucher component of a Phrase Name. This is generally composed of a collector name and identification. See Phrase Name for more information.

- Suggest “...generally composed of a collector’s name and collecting number or collection date.”?

**Comment by charvolant** [comment]
Intital mappings for both AFD and NSL/APNI/APC completed

**Comment by charvolant** [comment]
Check handling of excluded species for AFD. Carbo ater is excluded but doesn't seem to have made it through to the final taxon.csv list.

**Comment by charvolant** [comment]
Carbo ater now properly in taxon.csv It's listed as an excluded name of Aves and Phalacrocorax (Phalacrocorax) Brisson, 1760

It will be interesting to see what the name matcher makes of that.

**Comment by charvolant** [comment]
Ware encodings. Stuff passed through Mac Excel may end up encoded in Mac OS Roman encoding https://en.wikipedia.org/wiki/Mac_OS_Roman This (a) can't handle some of the characters in author's names if they have the ill-manners to come from somewhere other than Western Europe and (b) isn't automatically detected by non-Mac operating systems. This causes a problem for AFD where the name disambiguation table and name table don't agree on author names.

**Comment by charvolant** [comment]
Notes from current discussions on getting remaining names

Fungi - Check with Tom, Check with Neils (Moss) - Doug to contact directly
Bie built from the bottom nightly (or whatever) - reason for doing this is that images change
Have to change taxonID to refer to concept rather than name (Doug to do)
Dave to find sources of catalogue of life stuff -- fish and bacteria

Things to find

"Animalia" - AFD
"Bacteria" - CoL
"Chromista" - AusFungi
"Fungi" - AusFungi
"PROTISTA" - AFD
"Plantae" - APC
"Protozoa" - Index Fungorum
"Viruses" - CoL
Fish - TBD

**Comment by charvolant** [comment]
Niels and Tom have provided data for AusFungi and AusMoss.

Initial mapping for AusFungi completed. There are a few niggles that have shown up and a possible encoding issue with author's names, with some names possibly garbled as they migrated between databases. Things are otherwise pretty schmick-looking.

**Comment by charvolant** [comment]
AusMoss has invalid names that point to the accepted name. See https://github.com/AtlasOfLivingAustralia/bie-index/issues/17 for an intial thought about how to handle this.

**Comment by charvolant** [comment]
Initial mapping for AusMoss completed. Mappings have been arranged so that the higher-level kingdom/phylum type stuff uses the APNI IDs, rather than the AusMoss IDs in preparation for linking the whole lot together.

**Comment by charvolant** [comment]
Bacteria and Virus data from catalogue of life added

**Comment by charvolant** [comment]
Notes from discussion at APNI/APC

* APNI/APC are working on a simple export that will make import easier. The result will look very much like a DwCA and require minimal processing and before being imported into the name index. *Doug to supply examples of 'easy' imports*
* The supplied file will contain both things in the APC and things that haven't made their way in there yet (such as orchids). The taxonID for an APC species is the corresponding concept. The taxonID for a non-APC species is the scientificNameID. The preferred parent-child tree is the APC tree. Non-APC species use the parallel APNI tree. *Doug to implement in processing*
* An option when searching to switch between 'as processed' and 'as supplied' would make things a lot easier for people searching for things in herbaria and the like. That way, they can look in the ALA for the name on the label. It's possible to do this at the moment, but really difficult for a non-super user. *Doug to create appropriate issue*
* Include direct links to NSL pages that can be referenced from the species page with an NSL logo. It's possible to do this indirectly via the LSID at the moment but it's not at all obvious. Links to the NSL name and current concept should be included. This seems to be partially handled already, if you go to the species page http://bie.ala.org.au/species/Acacia+dealbata then there are direct linke to the CHAH species page https://biodiversity.org.au/nsl/services/instance/apni/604698 and other links for synonyms. *Doug to investigate*
* Handling cultivars, hybrids and such like. These need to be clearly flagged and also do not fit neatly into the tree.
* Handling pro parte synonyms. At the moment, ala-name-matching handles uncomfortable synonyms by flagging them as a possible erroneous match. This really doesn't work cleanly and it would be good if we can consider a more sophisticated handling of multiple valid matches.

**Comment by charvolant** [comment]
'as-supplied' search raised as an issue in biocache-hub https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/155

**Comment by charvolant** [comment]
No! Your pain is not over yet. Comparing the existing name index with what's been generated shows a number of gaps:

* Data for species such as http://bie.ala.org.au/search?q=Malacosteus+australis which has a record from Codes for Australian Aquatic Biota http://www.marine.csiro.au/caabsearch/caab_search.caab_report?spcode=37110003 Contacting the custodian on http://www.marine.csiro.au/caab/ for a database dump
* Higher-order taxa from CoL, such as Stephanoma need to be included
* Also missing fungi species such as Anthracoidea hostianae
* But, good news everyone! Species such as Venus cumingii are in the AFD. However, the CoL has the author and name munged together.

**Comment by charvolant** [comment]
First try at CAAB data sent to John and Daniel for vetting

**Comment by charvolant** [comment]
CoL virus names have a (what appears to be) spurious colon in the genus name. This isn't present in the ICTV virus source so it looks like a stuff up in CoL. Fixing in pre-processing.

**Comment by charvolant** [comment]
AFD references.csv has some encoding problems: what looks like embedded newlines without enclosing quotes.

**Comment by charvolant** [comment]
APNI data has been delivered in new form and mapped to ALA

**Comment by charvolant** [comment]
Next time we do this, there's probably a better way of loading the data. At the moment, the Talend job does the honours for working out which source gets to be the authority for a name. This gets more and more and more and more and more complicated.

Instead, what should be done is that the Talend processing just produces cleaned DwCAs of the names, with a taxonomicStatus of ignored for stuff that shouldn't be in the final list. A separate program then takes all the sources and does the resolution between them, working out what gets priority and slotting everything together.

The INMRG homonym list is also a few years out of date and the person looking after it has retired. We can process what we've got to produce homonym indexes.

**Comment by charvolant** [comment]
Tested against current supplied names for the ALA and a single data resource.

**Comment by charvolant** [comment]
Things turning up:

* *Neobatrachus sudelli* synonnym for *Neobatrachus sudellae* marked as misapplied. Results go to higher taxon
* *Ardea alba* now a miscellaneous literature name, restricted to non-Australian birds. Results go to higher taxon.
* *Cereopsis novaehollandiae* ends up as unranked. The proper species is now *Cereopsis novaehollandiae novaehollandiae* and we end up with a parent-child synonym problem

**Comment by charvolant** [comment]
* *Canis lupus dingo* is ending up as a higher match of *Canis lupus* rather than being redirected to *Canis familiaris* (Which is what AFD says it is at the moment, please don't hit me!)

**Comment by charvolant** [comment]
Ensure names with naughty diacritics are being matched, eg. *Aleochara haemorrhoïdalis*

**Comment by charvolant** [comment]
To remove embedded newlines in free-text fields use

mv name.csv name.csv.orig
awk -v RS='"[^"]*"' -v ORS= '{gsub(/\n/, " ", RT); print $0  RT}' name.csv.orig > name.csv

**Comment by charvolant** [comment]
This is it folks. Over the top. Indexes and source data available at http://biocache.ala.org.au/archives/nameindexes/20160309/

**Comment by nielsklazenga** [comment]
Great work Doug. The CoL archive, is that based on the most recent version of CoL (from last December)?

**Comment by charvolant** [comment]
@nielsklazenga Yes, I downloaded it on 15-16 of January

**Comment by charvolant** [comment]
Thoughts about how to improve index construction at https://github.com/AtlasOfLivingAustralia/bie-index/wiki/Index-building-re-design

**Comment by charvolant** [comment]
APNI has a number of Fungi names in the names section. Since these are all names not put into APC, they get put into the Plantae bucket. What we're going to do is treat AusFungi as the name source and eliminate these names from the APNI taxon file.

**Comment by charvolant** [comment]
New indexes that correct the AusFungi, AusMoss and APNI overlap at http://biocache.ala.org.au/archives/nameindexes/20160322/

**Comment by charvolant** [comment]
Test bie and biocache available, during office hours, at:

* http://bie-aws.ala.org.au/bie
* http://biocache-aws.ala.org.au/biocache

The ALA biocache has been copied, reprocessed and re-index.

Checking iconic species for signs of deviation.

**Comment by charvolant** [comment]
specieslist-webapp needs to be updated to cope with new taxon ids that are urls. Also, the re-match seems to only partially work.

**Comment by charvolant** [comment]
The mysql tables for specieslist-webapp appear to be encoded as latin1. This will now cause problems since we have common names like Kōkihi.

**Comment by charvolant** [comment]
Copied bie, biocache, lists and SDS up on AWS

**Comment by charvolant** [comment]
Updated iconic species preferred images - http://lists.ala.org.au/speciesListItem/list/dr4778 and ingested them into BIE. There are a couple of oddities that need to be investigated:

* Two species will not "take" for some reason.
* The list server does not re-match images if there is already an image present.

**Comment by charvolant** [comment]
Converting species list to full UTF-8

```
alter database specieslist character set utf8;
alter table species_list convert to character set utf8;
alter table species_list_item convert to character set utf8;
alter table list_typeo  convert to character set utf8;
alter table species_list_item_species_listkvp convert to character set utf8;
alter table species_listkvp convert to character set utf8;
alter table species_list_item convert to character set utf8;
```

To see if the conversion has taken use 'show full columns species_list_item`

**Comment by charvolant** [comment]
In production
