### ISSUE TITLE
Loaded occurrence datasets without licence information

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/data-management#934]
At the time of writing there are 55 datasets loaded into the Atlas with no licence information:

https://collections.ala.org.au/public/datasets#filters=resourceType%3Arecords%3BlicenseType%3Aother%3Bstatus%3AdataAvailable

A good proportion of these are from BioCollect, but there are also some for AVH and other providers.
* https://collections.ala.org.au/public/showDataResource/dr2287

**Comment by djtfmartin** [comment]
I've reduced this down to 7 datasets now. BioCollect licencing was provided at the record level.

This still includes 2 OZCAM datasets and 1 AVH dataset without licences.

<img width="760" alt="Screenshot 2023-07-01 at 8 03 38 am" src="https://github.com/AtlasOfLivingAustralia/data-management/assets/444897/7872b534-709e-4ab4-a4eb-adbaa269b7c4">


cc @nielsklazenga @elywallis

**Comment by djtfmartin** [comment]
I've changed the AVH and OZCAM datasets to [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/legalcode) as this is what GBIF has them set to (im not sure how GBIF has determined that). If this is incorrect we can republish to GBIF.

**Comment by nielsklazenga** [comment]
Thanks Dave, CC BY 4.0 is correct for the BRI data resource.

**Comment by djtfmartin** [comment]
Licenses are attached to all datasets now

**Comment by peggynewman** [comment]
@patkyn @sadeghim @cha801p @rosemaryjoconnor make sure that incoming data always has a license either in the license field on the data resource, or per record in the occurrences.
