### ISSUE TITLE
Data load: Zoos Victoria Moth Tracker observation records dataset

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#935]
Helpdesk ticket: https://support.ehelp.edu.au/a/tickets/179620

**Comment by cha801p** [comment]
Zoos Victoria Moth Tracker is now loaded on databox: https://collections-test.ala.org.au/public/show/dr21670

**Comment by cha801p** [comment]
Asked the data provider to provide URLs for images to load on ALA.

**Comment by cha801p** [comment]
Data loaded on Prod with images:
https://collections.ala.org.au/public/show/dr22371
