### ISSUE TITLE
Helpdesk #180209 GBIF/ALA duplicate registration with suspicious country

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#946]
Investigate:
We noticed two relatively recent registrations coming in through ALA, both for the same entity (“Northern Territory Government”). In addition to the duplication, both entries are identified as belonging to “Andorra”.

There are quite a few entries belonging to ALA / endorsed by the Atlas of Living Australia that do not give any country at all, intermingled with entries that are correctly assigned to Australia.

Possible scripting error somewhere?

**Comment by peggynewman** [comment]
This was resolved with a collectory update
