### ISSUE TITLE
Update APII image

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#948]
This record has an outdated image attached: https://biocache.ala.org.au/occurrences/187fffe8-a80c-4caa-af64-134b6a0163ec

This entry for the same record on APII shows the updated image: https://canbr.gov.au/photo/apii/id/wae/235

Strategy as discussed in standup is to delete the image and allow it to be re-ingested, as the filename seems to be the same.

**Comment by sadeghim** [comment]
Deleted the image, purged deleted images in image-service and triggered re-ingest for APII and it should be fine tomorrow after indexing finishes.

**Comment by peggynewman** [comment]
https://images.ala.org.au/image/49826b12-81d0-452d-9bc0-5b115ec07aff it's landed

**Comment by sadeghim** [comment]
Record is updated now.
