### ISSUE TITLE
SA Museum data upload: 2023-08-07

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#955]
From helpdesk ticket https://support.ehelp.edu.au/a/tickets/182267

The most recent data upload for the South Australian Museum should be obtainable from:
 (file attached)
 
This is a complete replacement for our data, apart from the tissue collection which was recently sent separately.
 
I have not had the capacity yet to change how quote marks are escaped in the export script so there will still be a few occurrences of \" in the data

[2023-08-07-SAM-DWC-EXPORT.zip](https://github.com/AtlasOfLivingAustralia/data-management/files/12297369/2023-08-07-SAM-DWC-EXPORT.zip)

**Comment by rosemaryjoconnor** [comment]
This is part of SAMA for mobilisation Issue: #941

**Comment by rosemaryjoconnor** [comment]
Loaded in Production 10/08/2023.
Data needs cleaning before upload due to escape characters in CSV that python read csv doesn't handle too well. Documented in code. 
Source code to go in databox
