### ISSUE TITLE
Museum Victoria data reload

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/data-management#96]
Contacted by Ursula to indicate that many of the MV records have mangled data. Investigation shows that 80% of their records have a number of unused fields that have irrelevant contents.

Plan of attack is to organise a full reload of the data.  Prior to load, all fields except Institute, Collection, Catalogue number and Associated Media are to be deleted using the delete field tool and then apply a full reload over the top.

**Comment by m-hope** [comment]
Data has been provided via SFTP and can be found here: <"\\fsact01-cdc\CSIRO\CES\Share\Themes\Biodiversity\1173-BRABA\Projects\Current\R336601001 _ALA\ALA Data\File Store\Occurrence\OZCAM\dr342 - Museum Victoria\complete load March 2015\MV-export-20150331-dataonly.zip">

**Comment by m-hope** [comment]
Data analysis and required corrections have been provided...

**Comment by sadeghim** [comment]
Data profiling and preliminary checks done. Loading it into the test server.

**Comment by sadeghim** [comment]
Testing was successful, moving to the production environment.

**Comment by sadeghim** [comment]
Successfully loaded and waiting for indexing.

**Comment by sadeghim** [comment]
Loaded and checked!
