### ISSUE TITLE
QVMAG images problem

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#966]
We had another recent upload of data onto your platform and once again all our insect images appear to have disappeared.
It is most likely the same issue as before. Can you look into this please?

**Comment by peggynewman** [comment]
Perhaps the DwCA was loaded without a multimedia file? There are plenty of images in the image service. 
Records: https://biocache.ala.org.au/occurrence/search?q=data_resource_uid%3Adr345&qualityProfile=ALA&disableAllQualityFilters=true

Images: https://images.ala.org.au/?fq=dataResourceUid:dr345

**Comment by peggynewman** [comment]
There is no license info on this data or dataset - please resolve this.

**Comment by cha801p** [comment]
**Ticket Update:**

**Issue Identified:** The most recent data ingestion did not include the multimedia.csv file.

**Resolution:** To address this, I have re-ingested the latest DwCA (Darwin Core Archive) along with the multimedia.csv file.

**Steps Taken:**

Obtained the images.csv by selecting "Download results" from the following URL: https://images.ala.org.au/?fq=dataResourceUid:dr345
The downloaded CSV was then aligned and merged with the existing multimedia.csv.
New identifiers were incorporated into the multimedia.csv file.
Please consult the following link for guidance on editing the CSV: https://confluence.csiro.au/display/ALASD/Loading+images#:~:text=Loading%20images%20sent%20by%20a%20data%20provider
The data was subsequently re-ingested into the production environment.
**Validation:**
You can verify the successful upload of images in batches by visiting the following link: https://images.ala.org.au/admin/batchUpload/392836323

**Comment by peggynewman** [comment]
Thanks for this level of detail Raj, I appreciate it

**Comment by cha801p** [comment]
**RESOLVED**
**Validation:** Images have appeared on ALA. 
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr345#tab_recordImages
