### ISSUE TITLE
Soft delete Marine Molluscs of Tasmania (dr733)

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#969]
See https://support.ehelp.edu.au/a/tickets/183798

DR needs to be taken down.

This dataset has 37 citations in GBIF.

Collectory

- [x] Make a note of the GBIF registry key: https://www.gbif.org/dataset/84aa5ee4-f762-11e1-a439-00145eb45e9a
- [x] Click Delete from GBIF 
- [x] untick `Should be shared with GBIF ? : yes`
- [x] mark data resource as private
- [x] remove records in SOLR
- [x] remove records in ES
- [x] delete AVRO
- [x] do not retain DwCA (if retained, the reinterpretation phase will fail)
- [x] set retain UUID to true is fine

SG suggests that the wording would be "dataset is now largely subsumed into the TMAG dataset". Add this to the DR metadata.

**Comment by cha801p** [comment]
**GBIF registry key:** 3d5d2fc8-05bb-4d16-afb2-9d61a891e2d5 [https://www.gbif.org/dataset/3d5d2fc8-05bb-4d16-afb2-9d61a891e2d5]
