### ISSUE TITLE
Update dr19813-FeralScan fetcher and RASD to handle sensitive data

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#971]
Update the FeralScan fetcher to:
- Pull all sensitive (including deer, pig, wild dog) data from FeralScan that we can access securely via the API
- Retain a copy of the raw data on S3 [ala-uploaded-datasets](https://s3.console.aws.amazon.com/s3/buckets/ala-uploaded-datasets?region=ap-southeast-2&tab=properties)
- Obfuscate the dataset as required and publish the DwCA to production

After this is done, work with Feralscan to set up a RASD metadata statement and a process for providing authorised access to the data

**Comment by rosemaryjoconnor** [comment]
Code complete and tested in databox-dev and databox. Pull request initiated with Mahmoud as reviewer. 
Have yet to contact Feralscan re RASD metadata statement.

**Comment by rosemaryjoconnor** [comment]
Additional coding required to output DWCA with complete dataset.

**Comment by rosemaryjoconnor** [comment]
Code completed and in github develop branch as at: 24/10/2023
Not yet in master branch/production

**Comment by rosemaryjoconnor** [comment]
19/12/2023

- FeralScan now in production with successful write of raw data to S3 bucket: **s3://ala-uploaded-datasets/ala/dr19813** 
- Data checked. Obfuscations and exclusion **Deer,** **Pig** and **Wild dog** correctly
- DWCA on S3 confirmed as full dataset

**Comment by peggynewman** [comment]
Waiting on me to check on with Cam

**Comment by peggynewman** [comment]
Superceded by https://github.com/AtlasOfLivingAustralia/data-management/issues/1008
