### ISSUE TITLE
Change QVMAG licence from UNSPECIFIED to CC BY-NC 4.0

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#981]
All QVMAG imagery on ALA is licenced under Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
Please update the data to reflect this.

Should be able to update collectory license field and reload.

**Comment by cha801p** [comment]
**Ticket Update:** October 2, 2023 (1:30 PM)

**Issue Resolved:** Change QVMAG licence from UNSPECIFIED to CC BY-NC 4.0

**Resolution:**  Reload data on biocache - with updated licence CC BY-NC 4.0

**Actions Taken:**

1. Data was loaded on databox after updating the licence on collectory-test
2. While repeating the same process on biocache - "load_images" was set to "true"
3. Data was reloaded on biocache

**Validation:**

- [ ] Updated licence information appears for each record on biocache
- [ ] NO problem caused in indexing
