### ISSUE TITLE
dr22433: turtleSat - Citizen Science

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/data-management#987]
**1 Million Turtles Citizen Science Data** 

- Turtle Sightings
- Turtle Nesting

**Comment by rosemaryjoconnor** [comment]
**Meeting 17/10/2023**

Data is held on same database as FeralScan, unlike Feralscan images to be provided

- 2 new dataresources to be created as the information for each is quite different:

1.    Turtle sightings data
2.    Turtle nesting data

- API access should be ready within a few weeks
- Image URLs will be provided for each occurrence record
- RS and MN to provide scientific name and flag any records requiring generalisation
- Licencing DP advised to use same licence as Feralscan - CC NC
- ROC to provide example of metadata required

Most of the feralscan code can be utilised for processing, it looks straightforward.

**Comment by rosemaryjoconnor** [comment]
There is the possibility of another dataset Wombat Sightings to be available from the same server. MN to provide information regarding that.

**Comment by rosemaryjoconnor** [comment]
16/11/2023 Emailed for update

**Comment by rosemaryjoconnor** [comment]
16/11/2023 - user responded. No update re ETA for API as yet

**Comment by rosemaryjoconnor** [comment]
- [ ] Email user late Jan 2024 for update re API

**Comment by rosemaryjoconnor** [comment]
30/01/2024 - MN replied. Work is starting on the new API this week.

**Comment by rosemaryjoconnor** [comment]
**04/03/2024**
- MN responded. New API should go live this week, will be in touch with details.

**Comment by rosemaryjoconnor** [comment]
**08/03/2024**

- Code tested and working well.
- Image URLs are accessible publicly but ingest  fails with 401 error.
- Load of occurrences only successful on databox: https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr22433

**Comment by rosemaryjoconnor** [comment]
**27/03/2024**

- Images loading correctly
- Occurrences and images successful on databoxhttps://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr22433
- Emailed MN - still require metadata before move to Prod

**Comment by peggynewman** [comment]
What a lovely dataset - @erinroger check it out!
@rosemaryjoconnor a couple of things:
- `basisOfRecord` = Human Observation
- `common name` should be mapped to `vernacularName`
- `date entered` - I would probably map this to `modifiedDate` what do you think?
- there are [two bodgy spatial records](https://biocache-test.ala.org.au/occurrence/search?q=data_resource_uid%3Adr22433&qualityProfile=ALA&disableAllQualityFilters=true&fq=spatiallyValid%3A%22false%22#tab_recordsView) they may want to know about, but they can be flagged and I don't think we need to wait for them to be fixed
- there is some roadkill appearing in the biocache gallery, should probably go into bie and make sure that they don't appear as the feature image for the species once this is loaded

**Comment by peggynewman** [comment]
recordedByID has a .0 in the DwCA - is this as supplied by the 1MillionTurtles API?

**Comment by rosemaryjoconnor** [comment]
**11/04/2024**
**Test**
- [ ] Metadata updated in Collectory
- [ ] Data and images loaded
- [ ] Emailed MN and RS to re checking metadata

**To do in Prod:**
- [ ] Create new DR 
- [ ] Add metadata
- [ ] Preingest and load

**Comment by rosemaryjoconnor** [comment]
**12/04/2024**

MN has responded. They'd like weekly updates

To Do:
- [ ]  Create new fetcher
- [ ] Test databox - dr22433
- [ ] Upload to Prod - dr26161

**Comment by rosemaryjoconnor** [comment]
**29/04/2024**
- [ ]  Prod pregingest/Load complete - 21,243 records 8,189 images
- [ ] SOLR Index finished
- [ ] Pull request github
- [ ] turtleSat fetcher in Prod
- [ ] Monthly schedule set

**Comment by rosemaryjoconnor** [comment]
**01/07/2024**
- [ ] turtleSat fetcher live in prod
- [ ] Successful prod run.
- [ ] Monthly schedule set

**Comment by rosemaryjoconnor** [comment]
**02/07/2024**

dwcahandler cannot determine mimetype of image URLs provided. 
turtleSat fetcher needs to be updated to create multimedia.csv as well as occurrence.csv

**Comment by rosemaryjoconnor** [comment]
**09/07/2024**
- [ ]  turtleSat Fetcher updated and live on schedule
