### ISSUE TITLE
Glenelg Hopkins Soundscape Project - Frog Calls (Birdlife Australia)

### ISSUE THREAD

**Issue by cha801p** [AtlasOfLivingAustralia/data-management#988]

**Comment by peggynewman** [comment]
Nice work!
https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr22185&qualityProfile=ALA#tab_recordsView

Ask for some metadata from the provider:
- description: how the data was collected, what equipment was used, what were the target species
- contact for the dataset, and whether we can make this publicly available. 

Data:
Change the identificationRemarks to `Recording not assessed for ....`

**Comment by cha801p** [comment]
**Ticket Update:** November 28, 2023 (11 AM)

**Issue:** Required to load a new dataset.

**Actions Taken:**

- [ ] Changed the identificationRemarks to Recording not assessed for....
- [ ] Fixed the date format
- [ ] Reloaded the data 
- [ ] The test link was sent to the data provider on - 14th November 2023
- [ ] Follow-up email sent to the data provider on - 28 November 2023

**Status: Waiting for the customer**

**Comment by cha801p** [comment]
Ticket Update: December 14, 2023 (3:30 AM)

Data has been loaded on Prod

Actions Taken:

- [ ] Prod links have been sent to the data provider
- [ ] Asked the data provider if he would be interested in speaking to our Comms Advisor about posting on social media about the data being loaded to the ALA

Status: Waiting for the customer

**Comment by cha801p** [comment]
No reply from the data provider regarding socials post
