### ISSUE TITLE
Bionet data stateConservation and countryConservation

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#989]
In BioNet data, values for stateConservation and countryConservation are provided. This means that there are values that show `Not Listed` which are difficult to understand.

In the BioNet fetcher, remove these fields. The fields are not standard Darwin Core, they are in the ALA namespace. In the ALA, the values are populated from the state and EPBC list. 

* [stateConservation Not Listed](https://biocache.ala.org.au/occurrences/search?q=*%3A*&qualityProfile=ALA&qc=-_nest_parent_%3A*&fq=country_conservation%3A%22Not+Listed%22#tab_mapView)
* [countryConservation Not Listed](https://biocache.ala.org.au/occurrences/search?q=*%3A*&qualityProfile=ALA&qc=-_nest_parent_%3A*&fq=country_conservation%3A%22Not+Listed%22#tab_mapView)

Next Wednesday, there will be demos to consultants to show them how to use these conservation status fields. It would be good if this could be done asap - by Tuesday. Perhaps the fields could be manually removed until we can put through a preingestion change?

**Comment by peggynewman** [comment]
This work has been done and is in the pre-ingestion release. When we deploy that it will be ready to go into prod

**Comment by sadeghim** [comment]
Waiting for the index tomorrow.

**Comment by patkyn** [comment]
Index now cleared from raw conservation status for bionet data
```
SEVERE- The new index doesn't have any record for stateConservation="Endangered Population"
SEVERE- The new index doesn't have any record for stateConservation="Endangered Population, Vulnerable" 
SEVERE- The new index doesn't have any record for stateConservation="Not Listed"
