### ISSUE TITLE
Data load: WA Boneseed observations

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#992]
From https://support.ehelp.edu.au/a/tickets/189948

Dataset and metadata are attached to ticket above.

**Comment by cha801p** [comment]
**Ticket Update:** November 28, 2023 (5 PM)

**Issue:** New dataset to load.

Solution: Successfully load the new dataset into biocache.

**Actions Taken:** Successfully loaded the data on the test environment

- [ ] Data was thoroughly reviewed and restructured
- [ ] Duplicates check run
- [ ] Columns renamed
- [ ] eventDate column created 
- [ ] DwcA created to load it to collectory-test
- [ ] Data loaded on: https://biocache-test.ala.org.au/occurrence/search?q=data_resource_uid%3Adr22243&qualityProfile=ALA


**Communication:** A test link to the data was sent to the data provider - 28 November 2023

**Issues Encountered:**

- [ ] Resolved issues related to date ranges
- [ ] Despite multiple reloads, dates persisted in non-standard formats

**Status: Waiting for the customer**

**Comment by cha801p** [comment]
https://collections.ala.org.au/public/show/dr25294

**Comment by cha801p** [comment]
Link sent to data provider.
