### ISSUE TITLE
ReInterpretation of BASE data dr10487

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#994]
the BASE dataset, dr10487, is an eDNA dataset, but somehow the `Environmental DNA` contentType field is missing from the data. I've added it now to the collectory. Please rerun the interpretation and index for dr10487 such that it picks up the change in collectory and creates a content type field in the data. Then it will be excluded correctly by the data quality profiles.

**Comment by cha801p** [comment]
**Ticket Update:** December 14, 2023 (3 PM)

**Problem:** ReInterpretation of BASE data dr10487

**Solution:** Successful ReInterpretation of dr10487

**Actions Taken:** 
- [ ] Data was reinterpreted (Ran Ingest_large_datasets DAG with "skip_dwca_to_verbatim": "true")
- [ ] Environmental DNA is NOT added to the records

**Possible Solution:** 
- contentType is not a DwC term so need to add this to the occurrence.csv to associate it with every record
- Current DwCA is poorly structured and needs restructure before ingestion

**Comment by peggynewman** [comment]
This might be a problem with the DQ filters. I've created a ticket on the systems team board.
https://github.com/orgs/AtlasOfLivingAustralia/projects/15/views/15?pane=issue&itemId=47637256

I'm going to close this now. The contentTypes are there in SOLR.
