### ISSUE TITLE
Data load: BDBSA 12/2023

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-management#996]
https://support.ehelp.edu.au/a/tickets/190677

The SA Department for Environment and Water has created an updated version of the SA Flora (BDBSA) and SA Fauna (BDBSA) records on the ALA FTP site.
Please update the datasets metadata with the month and year of this extraction - 12/2023

**Comment by rosemaryjoconnor** [comment]
1. Data load complete
2. Index successful
3. Collectory dates updates

**Record counts:**

- dr365-SA Fauna: 1,738,164
- dr366-SA Flora:  2,040,591
